# coding: utf-8

"""
    Aspose.Storage for Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class FileExist(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_exist': 'bool',
        'is_folder': 'bool'
    }

    attribute_map = {
        'is_exist': 'IsExist',
        'is_folder': 'IsFolder'
    }

    def __init__(self, is_exist=None, is_folder=None):
        """
        FileExist - a model defined in Swagger
        """

        self._is_exist = None
        self._is_folder = None
        self.discriminator = None

        self.is_exist = is_exist
        self.is_folder = is_folder

    @property
    def is_exist(self):
        """
        Gets the is_exist of this FileExist.

        :return: The is_exist of this FileExist.
        :rtype: bool
        """
        return self._is_exist

    @is_exist.setter
    def is_exist(self, is_exist):
        """
        Sets the is_exist of this FileExist.

        :param is_exist: The is_exist of this FileExist.
        :type: bool
        """
        if is_exist is None:
            raise ValueError("Invalid value for `is_exist`, must not be `None`")

        self._is_exist = is_exist

    @property
    def is_folder(self):
        """
        Gets the is_folder of this FileExist.

        :return: The is_folder of this FileExist.
        :rtype: bool
        """
        return self._is_folder

    @is_folder.setter
    def is_folder(self, is_folder):
        """
        Sets the is_folder of this FileExist.

        :param is_folder: The is_folder of this FileExist.
        :type: bool
        """
        if is_folder is None:
            raise ValueError("Invalid value for `is_folder`, must not be `None`")

        self._is_folder = is_folder

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, FileExist):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
