- package: {{ PIPELINE_MODEL_NAME }}
  version: {{ PIPELINE_MODEL_TAG }}
  author-email:
  tags: [{{ PIPELINE_MODEL_NAME }}, {{ PIPELINE_MODEL_TAG }}, {{ PIPELINE_MODEL_TYPE }}, model]

# -------------------------------------------------------------------
# base (shared config)
# -------------------------------------------------------------------

- config: base
  operations:
    train:
      description: 'Train'
      cmd: 'pipeline_train'
        model_dir:
          description: Model dir
          default: .
    evaluate:
      description: 'Evaluate'
      cmd: 'pipeline_train'
      requires:
        - trained-model
  resources:
    trained-model:
      private: yes
      sources:
        - operation: train
          select:
            - model.ckpt.*
            - checkpoint

- model: {{ PIPELINE_MODEL_NAME }}
  extends: base
  params:
    train_cmd: pipeline_train
    model_desc: {{ PIPELINE_MODEL_NAME }}
    model_name: {{ PIPELINE_MODEL_NAME }}
    model_tag: {{ PIPELINE_MODEL_TAG }}
    model_type: {{ PIPELINE_MODEL_TYPE }}
    model_runtime: {{ PIPELINE_MODEL_RUNTIME }}
    model_chip: {{ PIPELINE_MODEL_CHIP }}
