# Map of valid labels for each component in your project
infrastructure:
- "jenkins"
- "polarion"
- "documentation"
- "tooling"
- "provider-gce"
- "provider-rhevm"
- "provider-vmware"
- "provider-osp"
- "provider-rhos"
- "provider-azure"
- "provider-ec2"
- "provider-scvmm"
- "provider-cm"
- "infra-gce"
- "infra-rhevm"
- "infra-vmware"
- "infra-rhos"
- "infra-ec2"
- "other"
testing:
- "cloudforms"
- "satforms"
- "vmass"
- "cfme-5.9"
- "cfme-5.8"
- "upstream"
- "miq-demo"
- "on-qa"
- "pteam"
- "templates"
- "other"
management:
- "cloudforms"
- "satforms"
- "vmass"
- "meeting"
- "bug-work"
- "jira"
- "other"
automation:
- "cloudforms"
- "satforms"
- "vmass"
- "framework"
- "auto-test-fix"
- "new-test"
- "pr-review"
- "results-review"
- "other"
documentation:
- "polarion"
- "bug-work"
- "automation"
- "mojo"
- "other"
training:
- "personal"
- "other"
