
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cfab929fabfa13ad6b4a45c42002a9086edcfd9e",
 "version": "0.1.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
