- nodeset:
    name: zuul-functional-temp-master
    nodes:
      - name: controller
        label: ubuntu-xenial
      - name: node1
        label: ubuntu-xenial
      - name: node2
        label: ubuntu-xenial
    groups:
      - name: node
        nodes:
          - node1
          - node2

- job:
    name: zuul-stream-functional
    parent: multinode
    nodeset: zuul-functional-temp-master
    pre-run: playbooks/zuul-stream/pre.yaml
    run: playbooks/zuul-stream/functional.yaml
    post-run:
      - playbooks/zuul-stream/post.yaml
      - playbooks/zuul-stream/post-ara.yaml
    required-projects:
      - openstack/ara
    files:
      - zuul/ansible/.*
      - playbooks/zuul-stream/.*
      - requirements.txt

- job:
    name: zuul-tox-remote
    parent: tox
    vars:
      tox_envlist: remote
      tox_environment:
        ZUUL_SSH_KEY: /home/zuul/.ssh/id_rsa
        ZUUL_REMOTE_IPV4: "{{ nodepool.interface_ip }}"
        ZUUL_REMOTE_KEEP: "true"

- project:
    check:
      jobs:
        - build-sphinx-docs:
            irrelevant-files:
              - zuul/cmd/migrate.py
              - playbooks/zuul-migrate/.*
            vars:
              sphinx_python: python3
        - tox-pep8
        - tox-py35:
            irrelevant-files:
              - zuul/cmd/migrate.py
              - playbooks/zuul-migrate/.*
        - tox-py36:
            nodeset: ubuntu-bionic
            irrelevant-files:
              - zuul/cmd/migrate.py
              - playbooks/zuul-migrate/.*
        - build-javascript-content:
            success-url: 'npm/html/status.html'
            files:
              - package.json
              - webpack.config.js
              - yarn.lock
              - web/.*
            vars:
              javascript_content_dir: zuul/web/static
              npm_command: build:dist -- --define ZUUL_API_URL="'https://zuul.openstack.org'"
        - nodejs-npm-run-lint:
            vars:
                node_version: 8
            success-url: 'npm/reports/bundle.html'
            files:
              - package.json
              - webpack.config.js
              - yarn.lock
              - web/.*
        - zuul-stream-functional
        - zuul-tox-remote
        - nodepool-zuul-functional:
            voting: false
    gate:
      jobs:
        - build-sphinx-docs:
            irrelevant-files:
              - zuul/cmd/migrate.py
              - playbooks/zuul-migrate/.*
            vars:
              sphinx_python: python3
        - tox-pep8
        - tox-py35:
            irrelevant-files:
              - zuul/cmd/migrate.py
              - playbooks/zuul-migrate/.*
        - tox-py36:
            nodeset: ubuntu-bionic
            irrelevant-files:
              - zuul/cmd/migrate.py
              - playbooks/zuul-migrate/.*
        - build-javascript-content:
            success-url: 'npm/html/status.html'
            files:
              - package.json
              - webpack.config.js
              - yarn.lock
              - web/.*
            vars:
              javascript_content_dir: zuul/web/static
              npm_command: build:dist -- --define ZUUL_API_URL="'https://zuul.openstack.org'"
        - nodejs-npm-run-lint:
            vars:
                node_version: 8
            success-url: 'npm/reports/bundle.html'
            files:
              - package.json
              - webpack.config.js
              - yarn.lock
              - web/.*
        - zuul-stream-functional
        - zuul-tox-remote
    post:
      jobs:
        - publish-zuul-docs
        - publish-openstack-sphinx-docs-infra-python3
        - publish-openstack-python-branch-tarball
        - publish-openstack-javascript-content:
            vars:
                node_version: 8
    release:
      jobs:
        - publish-zuul-docs
        - publish-openstack-sphinx-docs-infra-python3
