language: python

matrix:
  include:
    - python: "2.7"
      virtualenv:
        system_site_packages: true
      addons:
        apt:
          packages:
            - python-scipy

    - python: "3.6"
    # PyPy versions
    - python: pypy
    - python: pypy3

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - time

install:
  - pip install .
  - pip install coveralls

# command to run tests
script: nosetests --with-coverage --cover-package=rebench

after_success:
  coveralls
