# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(949, 773)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(750, 710, 181, 16))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(30, 280, 901, 421))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 96, 26))
        self.page.setObjectName(_fromUtf8("page"))
        self.pushButton_loadAddCase = QtGui.QPushButton(self.page)
        self.pushButton_loadAddCase.setGeometry(QtCore.QRect(772, 48, 75, 23))
        self.pushButton_loadAddCase.setObjectName(_fromUtf8("pushButton_loadAddCase"))
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(110, 30, 51, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_14 = QtGui.QLabel(self.page)
        self.label_14.setGeometry(QtCore.QRect(510, 31, 71, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_V_yEd = QtGui.QLineEdit(self.page)
        self.lineEdit_V_yEd.setGeometry(QtCore.QRect(350, 49, 68, 20))
        self.lineEdit_V_yEd.setObjectName(_fromUtf8("lineEdit_V_yEd"))
        self.label_35 = QtGui.QLabel(self.page)
        self.label_35.setGeometry(QtCore.QRect(30, 80, 621, 20))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 51, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_T_Ed = QtGui.QLineEdit(self.page)
        self.lineEdit_T_Ed.setEnabled(False)
        self.lineEdit_T_Ed.setGeometry(QtCore.QRect(510, 50, 68, 20))
        self.lineEdit_T_Ed.setObjectName(_fromUtf8("lineEdit_T_Ed"))
        self.layoutWidget = QtGui.QWidget(self.page)
        self.layoutWidget.setGeometry(QtCore.QRect(710, 90, 86, 170))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_loadSeletedON = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_loadSeletedON.setObjectName(_fromUtf8("pushButton_loadSeletedON"))
        self.verticalLayout_2.addWidget(self.pushButton_loadSeletedON)
        self.pushButton_loadSeletedOFF = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_loadSeletedOFF.setObjectName(_fromUtf8("pushButton_loadSeletedOFF"))
        self.verticalLayout_2.addWidget(self.pushButton_loadSeletedOFF)
        self.pushButton_loadAllON = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_loadAllON.setObjectName(_fromUtf8("pushButton_loadAllON"))
        self.verticalLayout_2.addWidget(self.pushButton_loadAllON)
        self.pushButton_loadAllOFF = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_loadAllOFF.setObjectName(_fromUtf8("pushButton_loadAllOFF"))
        self.verticalLayout_2.addWidget(self.pushButton_loadAllOFF)
        self.pushButton_loadDelAll = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_loadDelAll.setObjectName(_fromUtf8("pushButton_loadDelAll"))
        self.verticalLayout_2.addWidget(self.pushButton_loadDelAll)
        self.pushButton_loadDelSelected = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_loadDelSelected.setObjectName(_fromUtf8("pushButton_loadDelSelected"))
        self.verticalLayout_2.addWidget(self.pushButton_loadDelSelected)
        self.lineEdit_N_Ed = QtGui.QLineEdit(self.page)
        self.lineEdit_N_Ed.setGeometry(QtCore.QRect(110, 49, 67, 20))
        self.lineEdit_N_Ed.setObjectName(_fromUtf8("lineEdit_N_Ed"))
        self.label_10 = QtGui.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(430, 30, 61, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.listWidget_loadcases = QtGui.QListWidget(self.page)
        self.listWidget_loadcases.setGeometry(QtCore.QRect(30, 100, 651, 141))
        self.listWidget_loadcases.setObjectName(_fromUtf8("listWidget_loadcases"))
        self.lineEdit_M_yEd = QtGui.QLineEdit(self.page)
        self.lineEdit_M_yEd.setGeometry(QtCore.QRect(190, 49, 68, 20))
        self.lineEdit_M_yEd.setObjectName(_fromUtf8("lineEdit_M_yEd"))
        self.lineEdit_V_zEd = QtGui.QLineEdit(self.page)
        self.lineEdit_V_zEd.setGeometry(QtCore.QRect(430, 49, 68, 20))
        self.lineEdit_V_zEd.setObjectName(_fromUtf8("lineEdit_V_zEd"))
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(190, 30, 61, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_Name = QtGui.QLineEdit(self.page)
        self.lineEdit_Name.setGeometry(QtCore.QRect(30, 49, 67, 20))
        self.lineEdit_Name.setObjectName(_fromUtf8("lineEdit_Name"))
        self.lineEdit_M_zEd = QtGui.QLineEdit(self.page)
        self.lineEdit_M_zEd.setGeometry(QtCore.QRect(270, 49, 68, 20))
        self.lineEdit_M_zEd.setObjectName(_fromUtf8("lineEdit_M_zEd"))
        self.label_8 = QtGui.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(270, 30, 61, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_12 = QtGui.QLabel(self.page)
        self.label_12.setGeometry(QtCore.QRect(350, 30, 61, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton_loadEditSelected = QtGui.QPushButton(self.page)
        self.pushButton_loadEditSelected.setGeometry(QtCore.QRect(691, 48, 75, 23))
        self.pushButton_loadEditSelected.setObjectName(_fromUtf8("pushButton_loadEditSelected"))
        self.checkBox_stability = QtGui.QCheckBox(self.page)
        self.checkBox_stability.setGeometry(QtCore.QRect(590, 50, 101, 18))
        self.checkBox_stability.setObjectName(_fromUtf8("checkBox_stability"))
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 96, 26))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.comboBox_sectiongroups = QtGui.QComboBox(self.page_2)
        self.comboBox_sectiongroups.setGeometry(QtCore.QRect(690, 31, 201, 21))
        self.comboBox_sectiongroups.setMaxVisibleItems(20)
        self.comboBox_sectiongroups.setObjectName(_fromUtf8("comboBox_sectiongroups"))
        self.line_3 = QtGui.QFrame(self.page_2)
        self.line_3.setGeometry(QtCore.QRect(670, 30, 20, 291))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.listWidget_typelist = QtGui.QListWidget(self.page_2)
        self.listWidget_typelist.setGeometry(QtCore.QRect(690, 100, 81, 171))
        self.listWidget_typelist.setObjectName(_fromUtf8("listWidget_typelist"))
        self.listWidget_sectnamelist = QtGui.QListWidget(self.page_2)
        self.listWidget_sectnamelist.setGeometry(QtCore.QRect(780, 100, 111, 171))
        self.listWidget_sectnamelist.setObjectName(_fromUtf8("listWidget_sectnamelist"))
        self.textBrowser_FindSectionResults = QtGui.QTextBrowser(self.page_2)
        self.textBrowser_FindSectionResults.setGeometry(QtCore.QRect(10, 30, 651, 271))
        self.textBrowser_FindSectionResults.setObjectName(_fromUtf8("textBrowser_FindSectionResults"))
        self.pushButton_FindSections = QtGui.QPushButton(self.page_2)
        self.pushButton_FindSections.setGeometry(QtCore.QRect(690, 280, 201, 23))
        self.pushButton_FindSections.setToolTip(_fromUtf8(""))
        self.pushButton_FindSections.setObjectName(_fromUtf8("pushButton_FindSections"))
        self.label = QtGui.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 301, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton_ApllySelected = QtGui.QPushButton(self.page_2)
        self.pushButton_ApllySelected.setGeometry(QtCore.QRect(690, 310, 201, 23))
        self.pushButton_ApllySelected.setObjectName(_fromUtf8("pushButton_ApllySelected"))
        self.label_18 = QtGui.QLabel(self.page_2)
        self.label_18.setGeometry(QtCore.QRect(690, 70, 74, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.comboBox_Find_from = QtGui.QComboBox(self.page_2)
        self.comboBox_Find_from.setEnabled(True)
        self.comboBox_Find_from.setGeometry(QtCore.QRect(771, 65, 47, 20))
        self.comboBox_Find_from.setMaximumSize(QtCore.QSize(61, 16777215))
        self.comboBox_Find_from.setObjectName(_fromUtf8("comboBox_Find_from"))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.label_19 = QtGui.QLabel(self.page_2)
        self.label_19.setGeometry(QtCore.QRect(823, 70, 16, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.comboBox_Find_to = QtGui.QComboBox(self.page_2)
        self.comboBox_Find_to.setEnabled(True)
        self.comboBox_Find_to.setGeometry(QtCore.QRect(843, 65, 47, 20))
        self.comboBox_Find_to.setMaximumSize(QtCore.QSize(71, 16777215))
        self.comboBox_Find_to.setObjectName(_fromUtf8("comboBox_Find_to"))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 901, 340))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.textBrowser_SummaryReport = QtGui.QTextBrowser(self.page_3)
        self.textBrowser_SummaryReport.setGeometry(QtCore.QRect(10, 10, 881, 291))
        self.textBrowser_SummaryReport.setObjectName(_fromUtf8("textBrowser_SummaryReport"))
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 150, 164, 121))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_29 = QtGui.QLabel(self.layoutWidget1)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout.addWidget(self.label_29, 0, 0, 1, 1)
        self.lineEdit_L = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_L.setObjectName(_fromUtf8("lineEdit_L"))
        self.gridLayout.addWidget(self.lineEdit_L, 0, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.layoutWidget1)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout.addWidget(self.label_30, 1, 0, 1, 1)
        self.lineEdit_k_ycr = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_k_ycr.setObjectName(_fromUtf8("lineEdit_k_ycr"))
        self.gridLayout.addWidget(self.lineEdit_k_ycr, 1, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.layoutWidget1)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout.addWidget(self.label_31, 2, 0, 1, 1)
        self.lineEdit_k_zcr = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_k_zcr.setObjectName(_fromUtf8("lineEdit_k_zcr"))
        self.gridLayout.addWidget(self.lineEdit_k_zcr, 2, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.layoutWidget1)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout.addWidget(self.label_32, 3, 0, 1, 1)
        self.lineEdit_k_LT = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_k_LT.setObjectName(_fromUtf8("lineEdit_k_LT"))
        self.gridLayout.addWidget(self.lineEdit_k_LT, 3, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(34, 20, 40, 20))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(30, 90, 65, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.lineEdit_SectionMark = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_SectionMark.setEnabled(True)
        self.lineEdit_SectionMark.setGeometry(QtCore.QRect(80, 20, 151, 20))
        self.lineEdit_SectionMark.setObjectName(_fromUtf8("lineEdit_SectionMark"))
        self.pushButton_calculate = QtGui.QPushButton(self.centralwidget)
        self.pushButton_calculate.setGeometry(QtCore.QRect(30, 120, 191, 23))
        self.pushButton_calculate.setObjectName(_fromUtf8("pushButton_calculate"))
        self.lineEdit_SectionFigure = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_SectionFigure.setGeometry(QtCore.QRect(120, 60, 81, 20))
        self.lineEdit_SectionFigure.setObjectName(_fromUtf8("lineEdit_SectionFigure"))
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(34, 60, 80, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.comboBox_SteelGrade = QtGui.QComboBox(self.centralwidget)
        self.comboBox_SteelGrade.setGeometry(QtCore.QRect(120, 90, 60, 20))
        self.comboBox_SteelGrade.setObjectName(_fromUtf8("comboBox_SteelGrade"))
        self.pushButton_BrowseSection = QtGui.QPushButton(self.centralwidget)
        self.pushButton_BrowseSection.setGeometry(QtCore.QRect(210, 60, 16, 21))
        self.pushButton_BrowseSection.setObjectName(_fromUtf8("pushButton_BrowseSection"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(240, 20, 691, 251))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.graphicsView = QtGui.QGraphicsView(self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(10, 20, 661, 191))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.pushButton_zoom_in = QtGui.QPushButton(self.tab)
        self.pushButton_zoom_in.setGeometry(QtCore.QRect(620, 40, 21, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_zoom_in.setPalette(palette)
        self.pushButton_zoom_in.setObjectName(_fromUtf8("pushButton_zoom_in"))
        self.pushButton_zoom_out = QtGui.QPushButton(self.tab)
        self.pushButton_zoom_out.setGeometry(QtCore.QRect(620, 70, 21, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_zoom_out.setPalette(palette)
        self.pushButton_zoom_out.setObjectName(_fromUtf8("pushButton_zoom_out"))
        self.label_DrawInfo1 = QtGui.QLabel(self.tab)
        self.label_DrawInfo1.setGeometry(QtCore.QRect(20, 30, 611, 21))
        self.label_DrawInfo1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_DrawInfo1.setObjectName(_fromUtf8("label_DrawInfo1"))
        self.label_DrawInfo2 = QtGui.QLabel(self.tab)
        self.label_DrawInfo2.setGeometry(QtCore.QRect(21, 189, 641, 16))
        self.label_DrawInfo2.setObjectName(_fromUtf8("label_DrawInfo2"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.textBrowser_ElementProperties = QtGui.QTextBrowser(self.tab_2)
        self.textBrowser_ElementProperties.setGeometry(QtCore.QRect(10, 10, 671, 201))
        self.textBrowser_ElementProperties.setObjectName(_fromUtf8("textBrowser_ElementProperties"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.textBrowser_SectionResistance = QtGui.QTextBrowser(self.tab_3)
        self.textBrowser_SectionResistance.setGeometry(QtCore.QRect(10, 10, 661, 201))
        self.textBrowser_SectionResistance.setObjectName(_fromUtf8("textBrowser_SectionResistance"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.textBrowser_ElementResistance = QtGui.QTextBrowser(self.tab_4)
        self.textBrowser_ElementResistance.setGeometry(QtCore.QRect(10, 10, 661, 201))
        self.textBrowser_ElementResistance.setObjectName(_fromUtf8("textBrowser_ElementResistance"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.textBrowser_ElementCheckResults = QtGui.QTextBrowser(self.tab_5)
        self.textBrowser_ElementCheckResults.setGeometry(QtCore.QRect(10, 10, 671, 201))
        self.textBrowser_ElementCheckResults.setObjectName(_fromUtf8("textBrowser_ElementCheckResults"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 949, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setEnabled(True)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuOption = QtGui.QMenu(self.menubar)
        self.menuOption.setObjectName(_fromUtf8("menuOption"))
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout_STRUTHON_CENCRERE_MONO = QtGui.QAction(MainWindow)
        self.actionAbout_STRUTHON_CENCRERE_MONO.setObjectName(_fromUtf8("actionAbout_STRUTHON_CENCRERE_MONO"))
        self.actionSave_project = QtGui.QAction(MainWindow)
        self.actionSave_project.setObjectName(_fromUtf8("actionSave_project"))
        self.actionOpen_project = QtGui.QAction(MainWindow)
        self.actionOpen_project.setObjectName(_fromUtf8("actionOpen_project"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionLicense = QtGui.QAction(MainWindow)
        self.actionLicense.setObjectName(_fromUtf8("actionLicense"))
        self.actionReport_language = QtGui.QAction(MainWindow)
        self.actionReport_language.setObjectName(_fromUtf8("actionReport_language"))
        self.actionCalculate = QtGui.QAction(MainWindow)
        self.actionCalculate.setObjectName(_fromUtf8("actionCalculate"))
        self.menuMenu.addAction(self.actionSave_project)
        self.menuMenu.addAction(self.actionOpen_project)
        self.menuMenu.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuOption.addAction(self.actionReport_language)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(2)
        self.comboBox_Find_from.setCurrentIndex(0)
        self.comboBox_Find_to.setCurrentIndex(9)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "STRUTHON.STEEL.MONO.SECTION", None))
        self.pushButton_loadAddCase.setText(_translate("MainWindow", "Add loadcase", None))
        self.label_4.setText(_translate("MainWindow", "N_Ed[kN]", None))
        self.label_14.setText(_translate("MainWindow", "T_Ed[kNm]", None))
        self.lineEdit_V_yEd.setText(_translate("MainWindow", "0.0", None))
        self.label_35.setText(_translate("MainWindow", "No.,  Name,      N_Ed[kN],   M_yEd[kNm],   M_zEd[kNm],    V_yEd[kN],    V_zEd[kN],    T_Ed[kNm],  stabilitycheck[],    active[]", None))
        self.label_5.setText(_translate("MainWindow", "Name", None))
        self.lineEdit_T_Ed.setText(_translate("MainWindow", "0.0", None))
        self.pushButton_loadSeletedON.setText(_translate("MainWindow", "Selected ON", None))
        self.pushButton_loadSeletedOFF.setText(_translate("MainWindow", "Selected OFF", None))
        self.pushButton_loadAllON.setText(_translate("MainWindow", "All ON", None))
        self.pushButton_loadAllOFF.setText(_translate("MainWindow", "All OFF", None))
        self.pushButton_loadDelAll.setText(_translate("MainWindow", "Delete all", None))
        self.pushButton_loadDelSelected.setText(_translate("MainWindow", "Delete selected", None))
        self.lineEdit_N_Ed.setText(_translate("MainWindow", "0.0", None))
        self.label_10.setText(_translate("MainWindow", "V_zEd[kNm]", None))
        self.lineEdit_M_yEd.setText(_translate("MainWindow", "0.0", None))
        self.lineEdit_V_zEd.setText(_translate("MainWindow", "0.0", None))
        self.label_3.setText(_translate("MainWindow", "M_yEd[kNm]", None))
        self.lineEdit_Name.setText(_translate("MainWindow", "Noname", None))
        self.lineEdit_M_zEd.setText(_translate("MainWindow", "0.0", None))
        self.label_8.setText(_translate("MainWindow", "M_zEd[kNm]", None))
        self.label_12.setText(_translate("MainWindow", "V_yEd[kNm]", None))
        self.pushButton_loadEditSelected.setText(_translate("MainWindow", "Edit selected", None))
        self.checkBox_stability.setText(_translate("MainWindow", "Stabilitycheck[]", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Loads", None))
        self.pushButton_FindSections.setText(_translate("MainWindow", "FIND SECTIONS", None))
        self.label.setText(_translate("MainWindow", "Check results for selected section :", None))
        self.pushButton_ApllySelected.setText(_translate("MainWindow", "APPLY SELECTED", None))
        self.label_18.setText(_translate("MainWindow", "Capacity factor", None))
        self.comboBox_Find_from.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Find_from.setItemText(1, _translate("MainWindow", "0.1", None))
        self.comboBox_Find_from.setItemText(2, _translate("MainWindow", "0.3", None))
        self.comboBox_Find_from.setItemText(3, _translate("MainWindow", "0.4", None))
        self.comboBox_Find_from.setItemText(4, _translate("MainWindow", "0.5", None))
        self.comboBox_Find_from.setItemText(5, _translate("MainWindow", "0.6", None))
        self.comboBox_Find_from.setItemText(6, _translate("MainWindow", "0.7", None))
        self.comboBox_Find_from.setItemText(7, _translate("MainWindow", "0.8", None))
        self.comboBox_Find_from.setItemText(8, _translate("MainWindow", "0.9", None))
        self.comboBox_Find_from.setItemText(9, _translate("MainWindow", "1.0", None))
        self.label_19.setText(_translate("MainWindow", "to", None))
        self.comboBox_Find_to.setItemText(0, _translate("MainWindow", "0.1", None))
        self.comboBox_Find_to.setItemText(1, _translate("MainWindow", "0.2", None))
        self.comboBox_Find_to.setItemText(2, _translate("MainWindow", "0.3", None))
        self.comboBox_Find_to.setItemText(3, _translate("MainWindow", "0.4", None))
        self.comboBox_Find_to.setItemText(4, _translate("MainWindow", "0.5", None))
        self.comboBox_Find_to.setItemText(5, _translate("MainWindow", "0.6", None))
        self.comboBox_Find_to.setItemText(6, _translate("MainWindow", "0.7", None))
        self.comboBox_Find_to.setItemText(7, _translate("MainWindow", "0.8", None))
        self.comboBox_Find_to.setItemText(8, _translate("MainWindow", "0.9", None))
        self.comboBox_Find_to.setItemText(9, _translate("MainWindow", "1.0", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Find section", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Summary report", None))
        self.label_29.setText(_translate("MainWindow", "L [m] - ", None))
        self.lineEdit_L.setText(_translate("MainWindow", "0.0", None))
        self.label_30.setText(_translate("MainWindow", "k_ycr [ ] -", None))
        self.lineEdit_k_ycr.setText(_translate("MainWindow", "0.0", None))
        self.label_31.setText(_translate("MainWindow", "k_zcr [ ] -", None))
        self.lineEdit_k_zcr.setText(_translate("MainWindow", "0.0", None))
        self.label_32.setText(_translate("MainWindow", "k_LT [ ] -", None))
        self.lineEdit_k_LT.setText(_translate("MainWindow", "0.0", None))
        self.label_28.setText(_translate("MainWindow", "Name - ", None))
        self.label_27.setText(_translate("MainWindow", "Steel grade - ", None))
        self.lineEdit_SectionMark.setText(_translate("MainWindow", "Noname", None))
        self.pushButton_calculate.setText(_translate("MainWindow", "APLLY AND CALCULATE [Ctrl+Q]", None))
        self.pushButton_calculate.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.label_26.setText(_translate("MainWindow", "Section - ", None))
        self.pushButton_BrowseSection.setText(_translate("MainWindow", "..", None))
        self.pushButton_zoom_in.setText(_translate("MainWindow", "+", None))
        self.pushButton_zoom_out.setText(_translate("MainWindow", "-", None))
        self.label_DrawInfo1.setText(_translate("MainWindow", "DrawInfo1", None))
        self.label_DrawInfo2.setText(_translate("MainWindow", "DrawInfo2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Element drawing", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Element Properties", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Section Resistances", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Element resistances", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "ELEMENT CHECK RESULTS", None))
        self.menuMenu.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuOption.setTitle(_translate("MainWindow", "Option", None))
        self.actionAbout_STRUTHON_CENCRERE_MONO.setText(_translate("MainWindow", "About STRUTHON CENCRERE MONO", None))
        self.actionSave_project.setText(_translate("MainWindow", "Save project", None))
        self.actionSave_project.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionOpen_project.setText(_translate("MainWindow", "Open project", None))
        self.actionOpen_project.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionLicense.setText(_translate("MainWindow", "License", None))
        self.actionReport_language.setText(_translate("MainWindow", "Report language", None))
        self.actionCalculate.setText(_translate("MainWindow", "Calculate", None))

