# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
        key: deps-{{ .Branch}}-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: |
            sudo apt-get install opencv
            pip install -r requirements.txt

      - save_cache:
        key: deps-{{ .Branch}}-{{ checksum "requirements.txt" }}
        paths:
          - "venv"

      - run:
          name: Type check
          command: |
            mypy

      - run:
          name: Run tests
          command: |
            tox
