
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.17'
version_full = 'f4d98fcc4d85f76806763fab64ae9eca2155ddfa'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

