__version__ = "0.0.4"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.0.4)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '5df2ebec805806ad4caf16c185f5ba20e1ba73c3'
__git_head_subject__ = u'Finished Release v0.0.4'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2018-06-10 11:40:04'
