language: python
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install coveralls pytest
script:
- coverage run -m pytest
deploy:
  provider: pypi
  user: choppsv1
  password:
    secure: 4HPSQscdca7V8O2j11ctIYKmRZrdEci/jH0aAlDs7BMOrow1OAVRhYFI3BXl6CNUqu4hhWDrjPc3YUtKOHQXLkTKsCUjtkIzx+EZKX2FbPScOnAqjN4tBreZBR4LJ2+FrOHZJwJbJjSoCXk2tE9vFBub1Kw9wuNLuS/i/pLtAI0jZ7ENuJ4kI4oidpnHLIP0ijbVgAmXRImHxPQGMLLQKfcbGNx6JNEyPkQO+e+SmZtj/dR7OJPmbuupa4m62Wz/Mstig3qRFMw45CqNUk16b5V6xaABh+Py5++3KfKdi0IMJEoBDx1keXeI+Mnj/AFDJvcPAK/5lglcfZPrGSqNB4J48TY3A3CS3Ia1vHF5bslIlsP6ox/evwY64kzE6IqvhhKanJ/Pu7qHhPoNYn9NGg9e92T0wXkzHyNyg0bjxN19D9eQIPmmvY1PIR6vR5Dt+O+cWLoUFNrQtDE2Fr4b3rNsyzIeWkRJ5N7dCPfIL78HC2E+ervSQkhmj7A3VvTjWmfL4TSAmUcyWOnK32ZmRrTuX4IBReQs5NxrsfJsob5vzWspGw7CPFsvHW6XjrOwJ5X1mRssqgpdsM7AyI9WPoLVui2dr3Z70ozVo10YO9judNSCfOIzVdGxaCnVcgtJRGBCxEr4naeGy+BrT/z4gK71K4fcPh8qs/qDy9MmF2Y=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
  distributions: sdist bdist_wheel
  edge:
    branch: v1.8.45
env:
  global:
    secure: 4HPSQscdca7V8O2j11ctIYKmRZrdEci/jH0aAlDs7BMOrow1OAVRhYFI3BXl6CNUqu4hhWDrjPc3YUtKOHQXLkTKsCUjtkIzx+EZKX2FbPScOnAqjN4tBreZBR4LJ2+FrOHZJwJbJjSoCXk2tE9vFBub1Kw9wuNLuS/i/pLtAI0jZ7ENuJ4kI4oidpnHLIP0ijbVgAmXRImHxPQGMLLQKfcbGNx6JNEyPkQO+e+SmZtj/dR7OJPmbuupa4m62Wz/Mstig3qRFMw45CqNUk16b5V6xaABh+Py5++3KfKdi0IMJEoBDx1keXeI+Mnj/AFDJvcPAK/5lglcfZPrGSqNB4J48TY3A3CS3Ia1vHF5bslIlsP6ox/evwY64kzE6IqvhhKanJ/Pu7qHhPoNYn9NGg9e92T0wXkzHyNyg0bjxN19D9eQIPmmvY1PIR6vR5Dt+O+cWLoUFNrQtDE2Fr4b3rNsyzIeWkRJ5N7dCPfIL78HC2E+ervSQkhmj7A3VvTjWmfL4TSAmUcyWOnK32ZmRrTuX4IBReQs5NxrsfJsob5vzWspGw7CPFsvHW6XjrOwJ5X1mRssqgpdsM7AyI9WPoLVui2dr3Z70ozVo10YO9judNSCfOIzVdGxaCnVcgtJRGBCxEr4naeGy+BrT/z4gK71K4fcPh8qs/qDy9MmF2Y=
