
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-23T16:46:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "60cfb0e0665c1ab72b38c8243f04b0539b07a3b5",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
