
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-31T15:11:45-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a1e95634018555d3eb4651fab43a82d0a74f0e5b",
 "version": "0.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
