
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-30T10:03:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "bff7ae4105a0942f69a676df7f1feba8425f2702",
 "version": "0.8.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
