sudo: required
dist: trusty
language: python
python:
  - '3.6'
services:
  - docker
addons:
  apt:
    packages:
      - parallel
      - openvswitch-switch
cache:
  pip: true
# Run with 4 test shards (can't seem to schedule more).
env:
  global:
    - FAUCET_TEST_IMG=faucet/tests
    - MATRIX_SHARDS=4
  matrix:
    - MATRIX_SHARD=sanity
    - MATRIX_SHARD=0
    - MATRIX_SHARD=1
    - MATRIX_SHARD=2
    - MATRIX_SHARD=3
install:
  - pip3 install -q -r requirements.txt -r test-requirements.txt
  - python3 setup.py -q sdist
  - pip3 install -q dist/*tar.gz
  - pip3 show faucet
script:
  - ./run-travis-test.sh
deploy:
  provider: pypi
  user: faucet
  password:
    secure: I3vR7947jTkA5KWls6q/TZMvz8+9dvK5s+bfWvl9kT5WAVId4ym72nc22hLeSKQdwlYenxgVDnRT1XhJSYstTaLXHL6GbS10CFO838kbSb6Y1rzHiyuaaRBmlTj20drwGELIGMQj9fe8dY9XyVThQAX/FXsCQw3+71anQfH0a0use3eK8/o9HHWH5DJyuqiKSPmCG7m5hEHjmXeVSp2F9/yuO+xX/qbtAavSd7/3lP65U32AtZJLAr7d/yYobfrXKV/AYiYCl5uk+tYXHvwHp0pLwFA9pQ230IfKQsSNlS71vypWeTFG31chfmsLBDl/B3L2t0euiOdMaI5qLpW8vIYjDncjATxBeiHBWdumdPEnzTr8RtdeCV8TFBbgPa0Mg9CuEFAOs1bJvwz3JLwjSbGYggXFBdv+iKDXtHsu8zXZDrCTsRd0W7XjrJ5pjMpzhEmBPd8sUS6NYZtJUbnhtIYQqJZx4scQ9Ikw2mAyOQl2tqcaYF6lKjqwqSSl7Pd0LK+YPShSzqOCacSGFqybe8EbwJWdnGzV6RmIlcnHu56qyya/Q1lkvQo4/9yYjNdWA+qP42WWtLC0Ua5wt2h69TD2fuf0xkRiwaojFpNQRP892dUu4r+fUkdGCgJZOt22kP18387o/7T6GY0ka/j2srch1I13alv/+Xx/mNiupQk=
  on:
    repo: faucetsdn/faucet
    tags: true
