
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-21T21:39:38-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "004aebb187a330075e1eb206e854b27c5c0a1ffb",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
