"""
Author: qiacai
"""

"""
Constants to use for ada
"""

"""
Constants for algorithms
"""
ALGORITHM_DEFAULT_CALCULATOR_PERCENTILE_PERCENT = 50

ALGORITHM_DEFAULT_TRANSFORMER_OFFSET_VALUE = 0.0

ALGORITHM_DEFAULT_TRANSFORMER_SCALE_VALUE = 1.0

ALGORITHM_DEFAULT_TRANSFORMER_OFFSET_TIME = 0

ALGORITHM_DEFAULT_TRANSFORMER_SMOOTHING_FACTOR = 0.2

ALGORITHM_DEFAULT_TRANSFORMER_SEASONAL_DECOMPOSE_FREQ = 24

ALGORITHM_DEFAULT_TRANSFORMER_SEASONAL_DECOMPOSE_TREND_ONLY = False

ALGORITHM_DEFAULT_TRANSFORMER_SEASONAL_DECOMPOSE_FILLNA = False