---
  Docker.run_container:
  -
    description: An example of 'images' context configured to pull several images
    args:
      command: bar
      image_name: foo
    context:
      images@docker:
        names: [ubuntu, fedora]
