---
version: 2
title: Check listing networks.
subtasks:
- title: Run a single workload with listing existing docker networks
  scenario:
    Docker.list_networks: {}
  contexts:
    networks@docker:
    - {}
    - {}
  runner:
    constant:
      concurrency: 2
      times: 10
