
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "745e92cadffa190a8d264f74c7a14e400a3f92c3",
 "version": "2.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
