[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.poetry]
name = "rtd-flinx-shim"
version = "0.1.3"
description = "Trick Read the Docs into running Flinx."
authors = ["Oliver Steele <steele@osteele.com>"]
readme = "README.rst"
repository = "https://github.com/osteele/rtd-flinx-shim"
classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = ">=3.0"
flinx = "^0.1.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
rtd-flynx = 'rtd_flinx_shim:cli'
sphinx-build = 'rtd_flinx_shim:cli'
