
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-29T13:26:34-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0b7172235f5201ed71b0424a6eb377e9ac9907d",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
