
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-17T22:38:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e0c3c8f274534b30a8941c9f2db70711c77aaae4",
 "version": "5.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
