# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat Mar 11 23:12:30 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(383, 791)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_info = QtGui.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(20, 720, 331, 20))
        self.label_info.setObjectName(_fromUtf8("label_info"))
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(20, 10, 351, 641))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 351, 393))
        self.page.setObjectName(_fromUtf8("page"))
        self.layoutWidget = QtGui.QWidget(self.page)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 291, 331))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_loadRFEMxls = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_loadRFEMxls.setObjectName(_fromUtf8("pushButton_loadRFEMxls"))
        self.verticalLayout.addWidget(self.pushButton_loadRFEMxls)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_loadMecwaycsv = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_loadMecwaycsv.setEnabled(True)
        self.pushButton_loadMecwaycsv.setObjectName(_fromUtf8("pushButton_loadMecwaycsv"))
        self.horizontalLayout_5.addWidget(self.pushButton_loadMecwaycsv)
        self.pushButton_loadMecwayclipboard = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_loadMecwayclipboard.setObjectName(_fromUtf8("pushButton_loadMecwayclipboard"))
        self.horizontalLayout_5.addWidget(self.pushButton_loadMecwayclipboard)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.pushButton_loadROBOTcsv = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_loadROBOTcsv.setEnabled(True)
        self.pushButton_loadROBOTcsv.setObjectName(_fromUtf8("pushButton_loadROBOTcsv"))
        self.verticalLayout.addWidget(self.pushButton_loadROBOTcsv)
        self.textBrowser_loaddata = QtGui.QTextBrowser(self.layoutWidget)
        self.textBrowser_loaddata.setObjectName(_fromUtf8("textBrowser_loaddata"))
        self.verticalLayout.addWidget(self.textBrowser_loaddata)
        self.pushButton_clearData = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_clearData.setObjectName(_fromUtf8("pushButton_clearData"))
        self.verticalLayout.addWidget(self.pushButton_clearData)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 351, 393))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.layoutWidget1 = QtGui.QWidget(self.page_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 20, 291, 155))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton_plot3D = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_plot3D.setEnabled(True)
        self.pushButton_plot3D.setObjectName(_fromUtf8("pushButton_plot3D"))
        self.verticalLayout_4.addWidget(self.pushButton_plot3D)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboBox_SelectViewPoint = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_SelectViewPoint.setObjectName(_fromUtf8("comboBox_SelectViewPoint"))
        self.horizontalLayout.addWidget(self.comboBox_SelectViewPoint)
        self.pushButton_AutoSet = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_AutoSet.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_AutoSet.setObjectName(_fromUtf8("pushButton_AutoSet"))
        self.horizontalLayout.addWidget(self.pushButton_AutoSet)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.pushButton_PlotPreview = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_PlotPreview.setObjectName(_fromUtf8("pushButton_PlotPreview"))
        self.verticalLayout_2.addWidget(self.pushButton_PlotPreview)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.pushButton_plotThickness = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_plotThickness.setEnabled(True)
        self.pushButton_plotThickness.setObjectName(_fromUtf8("pushButton_plotThickness"))
        self.verticalLayout_4.addWidget(self.pushButton_plotThickness)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 351, 393))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.tabWidget = QtGui.QTabWidget(self.page_2)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 331, 381))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.pushButton_Apllytopanel = QtGui.QPushButton(self.tab)
        self.pushButton_Apllytopanel.setGeometry(QtCore.QRect(20, 280, 291, 27))
        self.pushButton_Apllytopanel.setObjectName(_fromUtf8("pushButton_Apllytopanel"))
        self.comboBox_cracklimn = QtGui.QComboBox(self.tab)
        self.comboBox_cracklimn.setGeometry(QtCore.QRect(236, 233, 78, 27))
        self.comboBox_cracklimn.setObjectName(_fromUtf8("comboBox_cracklimn"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(260, 70, 37, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.comboBox_dn = QtGui.QComboBox(self.tab)
        self.comboBox_dn.setGeometry(QtCore.QRect(236, 163, 78, 27))
        self.comboBox_dn.setObjectName(_fromUtf8("comboBox_dn"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(30, 230, 111, 31))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.comboBox_concreteclass = QtGui.QComboBox(self.tab)
        self.comboBox_concreteclass.setGeometry(QtCore.QRect(151, 96, 161, 27))
        self.comboBox_concreteclass.setObjectName(_fromUtf8("comboBox_concreteclass"))
        self.lineEdit_ap = QtGui.QLineEdit(self.tab)
        self.lineEdit_ap.setGeometry(QtCore.QRect(152, 198, 78, 27))
        self.lineEdit_ap.setObjectName(_fromUtf8("lineEdit_ap"))
        self.comboBox_steelclass = QtGui.QComboBox(self.tab)
        self.comboBox_steelclass.setGeometry(QtCore.QRect(151, 129, 161, 27))
        self.comboBox_steelclass.setObjectName(_fromUtf8("comboBox_steelclass"))
        self.comboBox_dp = QtGui.QComboBox(self.tab)
        self.comboBox_dp.setGeometry(QtCore.QRect(152, 163, 78, 27))
        self.comboBox_dp.setObjectName(_fromUtf8("comboBox_dp"))
        self.lineEdit_an = QtGui.QLineEdit(self.tab)
        self.lineEdit_an.setGeometry(QtCore.QRect(236, 198, 78, 27))
        self.lineEdit_an.setObjectName(_fromUtf8("lineEdit_an"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(70, 160, 66, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(70, 200, 69, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(170, 70, 38, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.comboBox_cracklimp = QtGui.QComboBox(self.tab)
        self.comboBox_cracklimp.setGeometry(QtCore.QRect(152, 233, 78, 27))
        self.comboBox_cracklimp.setObjectName(_fromUtf8("comboBox_cracklimp"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 99, 101, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(28, 129, 101, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.layoutWidget2 = QtGui.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 311, 29))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_15 = QtGui.QLabel(self.layoutWidget2)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_2.addWidget(self.label_15)
        self.lineEdit_PanelName = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_PanelName.setObjectName(_fromUtf8("lineEdit_PanelName"))
        self.horizontalLayout_2.addWidget(self.lineEdit_PanelName)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.textBrowser_panelprop = QtGui.QTextBrowser(self.tab_2)
        self.textBrowser_panelprop.setEnabled(True)
        self.textBrowser_panelprop.setGeometry(QtCore.QRect(10, 20, 301, 311))
        self.textBrowser_panelprop.setObjectName(_fromUtf8("textBrowser_panelprop"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 351, 393))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.layoutWidget3 = QtGui.QWidget(self.page_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 50, 291, 335))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton_plot_nx = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_plot_nx.setObjectName(_fromUtf8("pushButton_plot_nx"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_nx)
        self.pushButton_plot_ny = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_plot_ny.setObjectName(_fromUtf8("pushButton_plot_ny"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_ny)
        self.pushButton_plot_nxy = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_plot_nxy.setObjectName(_fromUtf8("pushButton_plot_nxy"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_nxy)
        self.pushButton_plot_mx = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_plot_mx.setObjectName(_fromUtf8("pushButton_plot_mx"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_mx)
        self.pushButton_plot_my = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_plot_my.setObjectName(_fromUtf8("pushButton_plot_my"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_my)
        self.pushButton_plot_mxy = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_plot_mxy.setObjectName(_fromUtf8("pushButton_plot_mxy"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_mxy)
        self.line = QtGui.QFrame(self.layoutWidget3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.pushButton_plot_equNX = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_plot_equNX.setObjectName(_fromUtf8("pushButton_plot_equNX"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_equNX)
        self.pushButton_plot_equNY = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_plot_equNY.setObjectName(_fromUtf8("pushButton_plot_equNY"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_equNY)
        self.pushButton_plot_equMX = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_plot_equMX.setObjectName(_fromUtf8("pushButton_plot_equMX"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_equMX)
        self.pushButton_plot_equMY = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_plot_equMY.setObjectName(_fromUtf8("pushButton_plot_equMY"))
        self.verticalLayout_3.addWidget(self.pushButton_plot_equMY)
        self.layoutWidget4 = QtGui.QWidget(self.page_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 10, 291, 29))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_16 = QtGui.QLabel(self.layoutWidget4)
        self.label_16.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_3.addWidget(self.label_16)
        self.comboBox_activeloadcase = QtGui.QComboBox(self.layoutWidget4)
        self.comboBox_activeloadcase.setObjectName(_fromUtf8("comboBox_activeloadcase"))
        self.horizontalLayout_3.addWidget(self.comboBox_activeloadcase)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_8 = QtGui.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 351, 393))
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.label_17 = QtGui.QLabel(self.page_8)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 241, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.layoutWidget5 = QtGui.QWidget(self.page_8)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 51, 337, 95))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_CutPeak = QtGui.QCheckBox(self.layoutWidget5)
        self.checkBox_CutPeak.setObjectName(_fromUtf8("checkBox_CutPeak"))
        self.gridLayout.addWidget(self.checkBox_CutPeak, 0, 0, 1, 1)
        self.comboBox_CutPeakSize = QtGui.QComboBox(self.layoutWidget5)
        self.comboBox_CutPeakSize.setObjectName(_fromUtf8("comboBox_CutPeakSize"))
        self.gridLayout.addWidget(self.comboBox_CutPeakSize, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 0, 2, 1, 1)
        self.checkBox_Smooth = QtGui.QCheckBox(self.layoutWidget5)
        self.checkBox_Smooth.setObjectName(_fromUtf8("checkBox_Smooth"))
        self.gridLayout.addWidget(self.checkBox_Smooth, 1, 0, 1, 1)
        self.comboBox_SmoothWidth = QtGui.QComboBox(self.layoutWidget5)
        self.comboBox_SmoothWidth.setObjectName(_fromUtf8("comboBox_SmoothWidth"))
        self.gridLayout.addWidget(self.comboBox_SmoothWidth, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 1, 2, 1, 1)
        self.checkBox_BarAnchoring = QtGui.QCheckBox(self.layoutWidget5)
        self.checkBox_BarAnchoring.setEnabled(False)
        self.checkBox_BarAnchoring.setObjectName(_fromUtf8("checkBox_BarAnchoring"))
        self.gridLayout.addWidget(self.checkBox_BarAnchoring, 2, 0, 1, 1)
        self.comboBox_BarAnchoringLength = QtGui.QComboBox(self.layoutWidget5)
        self.comboBox_BarAnchoringLength.setEnabled(False)
        self.comboBox_BarAnchoringLength.setObjectName(_fromUtf8("comboBox_BarAnchoringLength"))
        self.gridLayout.addWidget(self.comboBox_BarAnchoringLength, 2, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.layoutWidget5)
        self.label_43.setEnabled(False)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout.addWidget(self.label_43, 2, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.page_8)
        self.label_21.setGeometry(QtCore.QRect(10, 160, 331, 20))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.toolBox.addItem(self.page_8, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 351, 393))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.label_38 = QtGui.QLabel(self.page_5)
        self.label_38.setGeometry(QtCore.QRect(20, 60, 81, 21))
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.page_5)
        self.label_39.setGeometry(QtCore.QRect(17, 90, 81, 31))
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.line_4 = QtGui.QFrame(self.page_5)
        self.line_4.setGeometry(QtCore.QRect(111, 126, 178, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_10 = QtGui.QLabel(self.page_5)
        self.label_10.setGeometry(QtCore.QRect(130, 30, 57, 17))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.page_5)
        self.label_11.setGeometry(QtCore.QRect(210, 30, 71, 17))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.pushButton_plotApx = QtGui.QPushButton(self.page_5)
        self.pushButton_plotApx.setGeometry(QtCore.QRect(112, 57, 85, 27))
        self.pushButton_plotApx.setObjectName(_fromUtf8("pushButton_plotApx"))
        self.pushButton_plotApy = QtGui.QPushButton(self.page_5)
        self.pushButton_plotApy.setGeometry(QtCore.QRect(203, 57, 85, 27))
        self.pushButton_plotApy.setObjectName(_fromUtf8("pushButton_plotApy"))
        self.pushButton_plotAnx = QtGui.QPushButton(self.page_5)
        self.pushButton_plotAnx.setGeometry(QtCore.QRect(112, 92, 85, 27))
        self.pushButton_plotAnx.setObjectName(_fromUtf8("pushButton_plotAnx"))
        self.pushButton_plotAny = QtGui.QPushButton(self.page_5)
        self.pushButton_plotAny.setGeometry(QtCore.QRect(203, 92, 85, 27))
        self.pushButton_plotAny.setObjectName(_fromUtf8("pushButton_plotAny"))
        self.pushButton_plot_crackx = QtGui.QPushButton(self.page_5)
        self.pushButton_plot_crackx.setGeometry(QtCore.QRect(109, 150, 85, 27))
        self.pushButton_plot_crackx.setObjectName(_fromUtf8("pushButton_plot_crackx"))
        self.pushButton_plot_cracky = QtGui.QPushButton(self.page_5)
        self.pushButton_plot_cracky.setGeometry(QtCore.QRect(200, 150, 85, 27))
        self.pushButton_plot_cracky.setObjectName(_fromUtf8("pushButton_plot_cracky"))
        self.pushButton_plot_ksieffx = QtGui.QPushButton(self.page_5)
        self.pushButton_plot_ksieffx.setGeometry(QtCore.QRect(109, 185, 85, 27))
        self.pushButton_plot_ksieffx.setObjectName(_fromUtf8("pushButton_plot_ksieffx"))
        self.pushButton_plot_ksieffy = QtGui.QPushButton(self.page_5)
        self.pushButton_plot_ksieffy.setGeometry(QtCore.QRect(200, 185, 85, 27))
        self.pushButton_plot_ksieffy.setObjectName(_fromUtf8("pushButton_plot_ksieffy"))
        self.pushButton_plot_mimosx = QtGui.QPushButton(self.page_5)
        self.pushButton_plot_mimosx.setGeometry(QtCore.QRect(109, 220, 85, 27))
        self.pushButton_plot_mimosx.setObjectName(_fromUtf8("pushButton_plot_mimosx"))
        self.pushButton_plot_mimosy = QtGui.QPushButton(self.page_5)
        self.pushButton_plot_mimosy.setGeometry(QtCore.QRect(200, 220, 85, 27))
        self.pushButton_plot_mimosy.setObjectName(_fromUtf8("pushButton_plot_mimosy"))
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 351, 393))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.label_12 = QtGui.QLabel(self.page_6)
        self.label_12.setGeometry(QtCore.QRect(30, 10, 58, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.page_6)
        self.label_13.setGeometry(QtCore.QRect(240, 10, 58, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tableWidget_Apscale = QtGui.QTableWidget(self.page_6)
        self.tableWidget_Apscale.setGeometry(QtCore.QRect(10, 31, 81, 281))
        self.tableWidget_Apscale.setObjectName(_fromUtf8("tableWidget_Apscale"))
        self.tableWidget_Apscale.setColumnCount(0)
        self.tableWidget_Apscale.setRowCount(0)
        self.tableWidget_Anscale = QtGui.QTableWidget(self.page_6)
        self.tableWidget_Anscale.setGeometry(QtCore.QRect(220, 30, 81, 281))
        self.tableWidget_Anscale.setObjectName(_fromUtf8("tableWidget_Anscale"))
        self.tableWidget_Anscale.setColumnCount(0)
        self.tableWidget_Anscale.setRowCount(0)
        self.label_scaleUnit = QtGui.QLabel(self.page_6)
        self.label_scaleUnit.setGeometry(QtCore.QRect(107, 10, 91, 20))
        self.label_scaleUnit.setObjectName(_fromUtf8("label_scaleUnit"))
        self.label_scaleUnit_2 = QtGui.QLabel(self.page_6)
        self.label_scaleUnit_2.setGeometry(QtCore.QRect(100, 30, 111, 20))
        self.label_scaleUnit_2.setObjectName(_fromUtf8("label_scaleUnit_2"))
        self.layoutWidget6 = QtGui.QWidget(self.page_6)
        self.layoutWidget6.setGeometry(QtCore.QRect(110, 70, 101, 85))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_14 = QtGui.QLabel(self.layoutWidget6)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_6.addWidget(self.label_14)
        self.pushButton_ApllyToScale = QtGui.QPushButton(self.layoutWidget6)
        self.pushButton_ApllyToScale.setObjectName(_fromUtf8("pushButton_ApllyToScale"))
        self.verticalLayout_6.addWidget(self.pushButton_ApllyToScale)
        self.pushButton_spaceing = QtGui.QPushButton(self.layoutWidget6)
        self.pushButton_spaceing.setObjectName(_fromUtf8("pushButton_spaceing"))
        self.verticalLayout_6.addWidget(self.pushButton_spaceing)
        self.layoutWidget7 = QtGui.QWidget(self.page_6)
        self.layoutWidget7.setGeometry(QtCore.QRect(110, 230, 101, 52))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_2 = QtGui.QLabel(self.layoutWidget7)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.comboBox_presetAscale = QtGui.QComboBox(self.layoutWidget7)
        self.comboBox_presetAscale.setObjectName(_fromUtf8("comboBox_presetAscale"))
        self.verticalLayout_5.addWidget(self.comboBox_presetAscale)
        self.layoutWidget8 = QtGui.QWidget(self.page_6)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 320, 87, 62))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.pushButton_mapApx = QtGui.QPushButton(self.layoutWidget8)
        self.pushButton_mapApx.setObjectName(_fromUtf8("pushButton_mapApx"))
        self.verticalLayout_11.addWidget(self.pushButton_mapApx)
        self.pushButton_mapApy = QtGui.QPushButton(self.layoutWidget8)
        self.pushButton_mapApy.setObjectName(_fromUtf8("pushButton_mapApy"))
        self.verticalLayout_11.addWidget(self.pushButton_mapApy)
        self.layoutWidget9 = QtGui.QWidget(self.page_6)
        self.layoutWidget9.setGeometry(QtCore.QRect(220, 320, 87, 62))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.pushButton_mapAnx = QtGui.QPushButton(self.layoutWidget9)
        self.pushButton_mapAnx.setAutoFillBackground(False)
        self.pushButton_mapAnx.setObjectName(_fromUtf8("pushButton_mapAnx"))
        self.verticalLayout_12.addWidget(self.pushButton_mapAnx)
        self.pushButton_mapAny = QtGui.QPushButton(self.layoutWidget9)
        self.pushButton_mapAny.setObjectName(_fromUtf8("pushButton_mapAny"))
        self.verticalLayout_12.addWidget(self.pushButton_mapAny)
        self.toolBox.addItem(self.page_6, _fromUtf8(""))
        self.page_7 = QtGui.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 351, 393))
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.pushButton_SaveToDXF = QtGui.QPushButton(self.page_7)
        self.pushButton_SaveToDXF.setGeometry(QtCore.QRect(30, 10, 271, 27))
        self.pushButton_SaveToDXF.setObjectName(_fromUtf8("pushButton_SaveToDXF"))
        self.textBrowser_report = QtGui.QTextBrowser(self.page_7)
        self.textBrowser_report.setEnabled(True)
        self.textBrowser_report.setGeometry(QtCore.QRect(30, 74, 271, 241))
        self.textBrowser_report.setObjectName(_fromUtf8("textBrowser_report"))
        self.label_20 = QtGui.QLabel(self.page_7)
        self.label_20.setGeometry(QtCore.QRect(30, 50, 111, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.toolBox.addItem(self.page_7, _fromUtf8(""))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(20, 700, 341, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.layoutWidget10 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget10.setGeometry(QtCore.QRect(40, 670, 291, 27))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_progressText = QtGui.QLabel(self.layoutWidget10)
        self.label_progressText.setMinimumSize(QtCore.QSize(150, 0))
        self.label_progressText.setText(_fromUtf8(""))
        self.label_progressText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_progressText.setObjectName(_fromUtf8("label_progressText"))
        self.horizontalLayout_4.addWidget(self.label_progressText)
        self.progressBar = QtGui.QProgressBar(self.layoutWidget10)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_4.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 383, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSave = QtGui.QMenu(self.menubar)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.menuCaltulate = QtGui.QMenu(self.menubar)
        self.menuCaltulate.setObjectName(_fromUtf8("menuCaltulate"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_projekt = QtGui.QAction(MainWindow)
        self.actionSave_projekt.setEnabled(False)
        self.actionSave_projekt.setObjectName(_fromUtf8("actionSave_projekt"))
        self.actionOpen_projekt = QtGui.QAction(MainWindow)
        self.actionOpen_projekt.setObjectName(_fromUtf8("actionOpen_projekt"))
        self.actionAll_loadcases = QtGui.QAction(MainWindow)
        self.actionAll_loadcases.setObjectName(_fromUtf8("actionAll_loadcases"))
        self.actionActieve_loadcase = QtGui.QAction(MainWindow)
        self.actionActieve_loadcase.setObjectName(_fromUtf8("actionActieve_loadcase"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuSave.addAction(self.actionSave)
        self.menuSave.addAction(self.actionOpen)
        self.menuCaltulate.addAction(self.actionAll_loadcases)
        self.menuCaltulate.addAction(self.actionActieve_loadcase)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuCaltulate.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(4)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "STRUTHON.CONCRETE.PANEL", None))
        self.label_info.setText(_translate("MainWindow", "StruthonConcretePanel ver.0.1 ( www.struthon.org)                                                                                   ", None))
        self.pushButton_loadRFEMxls.setText(_translate("MainWindow", "Load from RFEM Dlubal xls output file", None))
        self.pushButton_loadMecwaycsv.setText(_translate("MainWindow", "Load Mecway csv output file", None))
        self.pushButton_loadMecwayclipboard.setText(_translate("MainWindow", "or clipboard", None))
        self.pushButton_loadROBOTcsv.setText(_translate("MainWindow", "Load from Robot csv output file", None))
        self.pushButton_clearData.setText(_translate("MainWindow", "Clear data", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", ">>> Import solver data", None))
        self.pushButton_plot3D.setText(_translate("MainWindow", "Show 3d geometry", None))
        self.label.setText(_translate("MainWindow", "Select view point for plots", None))
        self.pushButton_AutoSet.setText(_translate("MainWindow", "Auto set", None))
        self.pushButton_PlotPreview.setText(_translate("MainWindow", "Plot preview", None))
        self.pushButton_plotThickness.setText(_translate("MainWindow", "Panel thickness plot", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", ">>> Geometry and view point set", None))
        self.pushButton_Apllytopanel.setText(_translate("MainWindow", "Aplly to panel", None))
        self.label_5.setText(_translate("MainWindow", "Side n", None))
        self.label_9.setText(_translate("MainWindow", "cracklim [mm]", None))
        self.label_7.setText(_translate("MainWindow", "d [mm]", None))
        self.label_8.setText(_translate("MainWindow", "a [mm]", None))
        self.label_4.setText(_translate("MainWindow", "Side p", None))
        self.label_3.setText(_translate("MainWindow", "Concrete", None))
        self.label_6.setText(_translate("MainWindow", "Steel", None))
        self.label_15.setText(_translate("MainWindow", "Name", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "edit", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", ">>> Panel properties", None))
        self.pushButton_plot_nx.setText(_translate("MainWindow", "nx force", None))
        self.pushButton_plot_ny.setText(_translate("MainWindow", "ny force", None))
        self.pushButton_plot_nxy.setText(_translate("MainWindow", "nxy force", None))
        self.pushButton_plot_mx.setText(_translate("MainWindow", "mx momenet", None))
        self.pushButton_plot_my.setText(_translate("MainWindow", "my moment", None))
        self.pushButton_plot_mxy.setText(_translate("MainWindow", "mxy moment", None))
        self.pushButton_plot_equNX.setText(_translate("MainWindow", "equ_NX", None))
        self.pushButton_plot_equNY.setText(_translate("MainWindow", "equ_NY", None))
        self.pushButton_plot_equMX.setText(_translate("MainWindow", "equ_MX", None))
        self.pushButton_plot_equMY.setText(_translate("MainWindow", "equ_MY", None))
        self.label_16.setText(_translate("MainWindow", "Active loadcase", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", ">>> Plot internal force and set active loadcase", None))
        self.label_17.setText(_translate("MainWindow", "An Ap reinforcement options", None))
        self.checkBox_CutPeak.setText(_translate("MainWindow", "Cut peak with size -", None))
        self.label_18.setText(_translate("MainWindow", "*h", None))
        self.checkBox_Smooth.setText(_translate("MainWindow", "Smooth with width -", None))
        self.label_19.setText(_translate("MainWindow", "*h", None))
        self.checkBox_BarAnchoring.setText(_translate("MainWindow", "Include anchoring -", None))
        self.label_43.setText(_translate("MainWindow", "*fi*Areq/Aprov", None))
        self.label_21.setText(_translate("MainWindow", "Reinforcement need to be recalculate after channges.", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_8), _translate("MainWindow", ">>>Reinforcement options", None))
        self.label_38.setText(_translate("MainWindow", "Side  p >>", None))
        self.label_39.setText(_translate("MainWindow", "Side n >>", None))
        self.label_10.setText(_translate("MainWindow", "Dir. x", None))
        self.label_11.setText(_translate("MainWindow", "Dir.y", None))
        self.pushButton_plotApx.setText(_translate("MainWindow", "Apx", None))
        self.pushButton_plotApy.setText(_translate("MainWindow", "Apy", None))
        self.pushButton_plotAnx.setText(_translate("MainWindow", "Anx", None))
        self.pushButton_plotAny.setText(_translate("MainWindow", "Any", None))
        self.pushButton_plot_crackx.setText(_translate("MainWindow", "crackx", None))
        self.pushButton_plot_cracky.setText(_translate("MainWindow", "cracky", None))
        self.pushButton_plot_ksieffx.setText(_translate("MainWindow", "ksieffx", None))
        self.pushButton_plot_ksieffy.setText(_translate("MainWindow", "ksieffy", None))
        self.pushButton_plot_mimosx.setText(_translate("MainWindow", "mimosx", None))
        self.pushButton_plot_mimosy.setText(_translate("MainWindow", "mimosy", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", ">>> Plot results", None))
        self.label_12.setText(_translate("MainWindow", "Side p", None))
        self.label_13.setText(_translate("MainWindow", "Side n", None))
        self.label_scaleUnit.setText(_translate("MainWindow", "TextLabel", None))
        self.label_scaleUnit_2.setText(_translate("MainWindow", "(per meter value)", None))
        self.label_14.setText(_translate("MainWindow", "Edit scale", None))
        self.pushButton_ApllyToScale.setText(_translate("MainWindow", "Aplly to scale", None))
        self.pushButton_spaceing.setText(_translate("MainWindow", "+spacing", None))
        self.label_2.setText(_translate("MainWindow", "Preset scale", None))
        self.pushButton_mapApx.setText(_translate("MainWindow", "Ax map", None))
        self.pushButton_mapApy.setText(_translate("MainWindow", "Ay map", None))
        self.pushButton_mapAnx.setText(_translate("MainWindow", "Ax map", None))
        self.pushButton_mapAny.setText(_translate("MainWindow", "Ay map", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("MainWindow", ">>> Reinforcement map", None))
        self.pushButton_SaveToDXF.setText(_translate("MainWindow", "Save rcmaps to DXF", None))
        self.label_20.setText(_translate("MainWindow", "Calculation report", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("MainWindow", ">>> Report", None))
        self.menuSave.setTitle(_translate("MainWindow", "File", None))
        self.menuCaltulate.setTitle(_translate("MainWindow", "Calculate", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionSave_projekt.setText(_translate("MainWindow", "Save projekt", None))
        self.actionOpen_projekt.setText(_translate("MainWindow", "Open projekt", None))
        self.actionAll_loadcases.setText(_translate("MainWindow", "All loadcases", None))
        self.actionAll_loadcases.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionActieve_loadcase.setText(_translate("MainWindow", "Actieve loadcase", None))
        self.actionActieve_loadcase.setShortcut(_translate("MainWindow", "Ctrl+W", None))
        self.actionSave.setText(_translate("MainWindow", "Save SCPdata", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionOpen.setText(_translate("MainWindow", "Open SCPdata", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

