__version__ = "0.1.29"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.1.29)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'df25c162fd3eef07f15dbd4f3f504b01acc9ea6e'
__git_head_subject__ = u'Finished Release v0.1.29'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2018-06-10 12:57:34'
