# Units for DVM parameters as expected by BeamOptikDLL.
# The following two formats are accepted for units:
#
#   func-name: unit name
#   func-name: dictionary of {unit name: power}
#
# Valid unit names are from ``unum.units``.
units:
  kl:       m^-1
  ks:       m^-1
  angle:    rad
  dax:      rad
  ax:       rad
