
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-11T07:53:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "96d3cf3633ce1a0ea909d0e82feb6b68fc8def58",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
