[tool.poetry]
name = "mypackage12930123912903"
version = "0.1.2"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "~2.7"

[tool.poetry.dev-dependencies]
pytest = "^3.5"
