---
- name: Creating the configuration directory
  file:
    path: /etc/rabbitmq
    state: directory

- name: Copying the configuration
  template:
    src: "rabbitmq.config.j2"
    dest: "/etc/rabbitmq/{{ item.agent_id }}.config"
  loop: "{{ current_bus_conf }}"
  when: item.machine == inventory_hostname


# This generates the mapping host:ip
# this is necessary for rabbitmq node (short names)
# to resolve their names in the cluster
- name: Building the list of rabbit hosts (DNS)
  set_fact:
    etc_hosts: "{{ etc_hosts | default({}) | combine( {hostvars[item].ansible_hostname: hostvars[item]['ansible_' + control_network].ipv4.address} ) }}"
  loop: "{{ ansible_play_hosts }}"


# Code duplicated ahead
# This might be factorize using loop and loop_control
# when using ansible >= 2.7
# 
- include: start_single_rabbitmq.yml
  loop: 
    - "{{ current_bus_conf[0] }}"
  when: item.machine == inventory_hostname

- include: start_single_rabbitmq.yml
  loop: "{{ current_bus_conf[1:] }}"
  when: item.machine == inventory_hostname

# For an unknown reason the plugin isn't loaded automatically as before
- name: Enabling the management interface
  command: "docker exec {{ item.agent_id }} rabbitmq-plugins enable rabbitmq_management"
  loop: "{{ current_bus_conf }}"
  when: item.machine == inventory_hostname



