BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBB gettext(u'Delete 2FA device') BBBBBBBB
BBBBB BBBBBBB
     gettext(u'Two Factor Settings') 
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX XXX XXXX XX XXXXXX XXX XXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
            BBBBBBBBBB
        XXXXXXX
    XXXXXX
BBBBBBBB
