version: "3.5"

networks:
  traefik-net:
    external: true

services:
  main:
    image: strapdata/bench
    deploy:
      restart_policy:
        condition: none
    networks:
      - traefik-net
    volumes:
      - type: bind
        source: /etc/docker-context.sh
        target: /etc/profile.d/docker-context.sh
        read_only: true
      - type: bind
        source: /root/.cassandra/cqlshrc
        target: /root/.cassandra/cqlshrc
        read_only: true
      - type: bind
        source: /root/.curlrc
        target: /root/.curlrc
        read_only: true
      - type: bind
        source: /etc/cassandra
        target: /etc/cassandra
        read_only: true
      - type: bind
        source: /var/lib/cassandra
        target: /var/lib/cassandra
    environment:
      ELASSANDRA_LOAD_CQLSHRC: "true"
      STRAPMARK_USER: "admin"
      STRAPMARK_PASSWORD: "changeit"
      STRESS_WARMUP: "false"
