homeassistant:
  name: AIS dom
  unit_system: metric
  time_zone: Europe/Warsaw
  packages: !include_dir_named ais_packages/

# ais-dom cloud functionality
ais_cloud:
ais_ai_service:
ais_knowledge_service:
ais_shell_command:
ais_yt_service:


# for restore_state on input_select (radio stations etc.)
recorder:
  purge_keep_days: 5
  include:
    domains:
      - sensor
      - switch
      - media_player
  exclude:
    entities:
      - sensor.time
      - sensor.since_last_boot_templated
      - sensor.since_last_boot
      - input_select.radio_type
      - input_select.radio_station_name
      - input_select.radio_player
      - input_select.podcast_type
      - input_select.podcast_name
      - input_select.podcast_track
      - input_select.podcast_player
      - input_select.rss_news_category
      - input_select.rss_news_channel
      - input_select.rss_news_item
      - input_select.rss_news_player
      - input_select.ais_youtube_track_name
      - input_select.ais_music_player
      - input_select.book_autor
      - input_select.book_name
      - input_select.book_chapter
      - input_select.book_player
history:
  include:
    domains:
      - sensor
      - switch
      - media_player
  exclude:
    entities:
      - sensor.time
      - sensor.since_last_boot_templated
      - sensor.since_last_boot
      - input_select.radio_type
      - input_select.radio_station_name
      - input_select.radio_player
      - input_select.podcast_type
      - input_select.podcast_name
      - input_select.podcast_track
      - input_select.podcast_player
      - input_select.rss_news_category
      - input_select.rss_news_channel
      - input_select.rss_news_item
      - input_select.rss_news_player
      - input_select.ais_youtube_track_name
      - input_select.ais_music_player
      - input_select.book_autor
      - input_select.book_name
      - input_select.book_chapter
      - input_select.book_player

media_extractor:

# Enables the frontend
frontend:
  # development_repo: /home/andrzej/home-assistant-polymer
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-ais-microphone.html
    - /local/custom_ui/state-card-tiles.html
    - /local/custom_ui/state-card-text.html
    - /local/custom_ui/state-card-robot-disco.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html
    - /local/custom_ui/state-card-ais-microphone.html
    - /local/custom_ui/state-card-text.html
    - /local/custom_ui/state-card-robot-disco.html
  themes:
    ais:
      primary-color: "#FF9800"

# Enables configuration UI
config:

http:
   # api_password: xxx
   base_url: localhost:8123
   # ssl_certificate: /data/data/pl.sviete.dom/files/home/AIS/certificate.pem
   # ssl_key: /data/data/pl.sviete.dom/files/home/AIS/privkey.pem


# Track the sun
sun:

# AIS Service for AI
# Allows you to issue voice commands
conversation:
mqtt: !include mqtt.yaml
automation:  !include automations.yaml
