
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-14T10:27:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c09bbc6edfd1a01a521d2ab048df337572e970f",
 "version": "0.8.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
