
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-06T14:41:33-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "aecfbac8ad8c5582cf4f3116278de695601eb4c8",
 "version": "v1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
