version: '2.2'

services:
    mongo:
        image: mongo:${DOCKER_MONGO_VERSION}
        container_name: ${COMPOSE_PROJECT_NAME}_mongo
        hostname: ${COMPOSE_PROJECT_NAME}_mongo
        networks: [stakkr]
        volumes:
            - ${COMPOSE_BASE_DIR}/data/mongo:/data/db
