---
- name: "Inventory Filter Testing"
  hosts: localhost
  gather_facts: false
  vars:
    data: '../examples/topologies/duffy_3node_cluster.yml'
    state: present
    output:
      output:
        data:
         topology_name: "duffy_3node_cluster"
    resources_file: '../examples/topologies/duffy_topology_output.yml'
    layout_file: '../examples/topologies/duffy_3node_inventory_layout.yml'
    topology_outputs_duffy: "{{ topology_outputs['duffy_res'] }}"
    topology_outputs_os_server: "{{ topology_outputs['os_server_res'] }}"
    topology_outputs_os_volume: "{{ topology_outputs['os_volume_res'] }}"
    topology_outputs_os_object: "{{ topology_outputs['os_obj_res'] }}"
    topology_outputs_os_heat: "{{ topology_outputs['os_heat_res'] }}"
    topology_outputs_os_keypair: "{{ topology_outputs['os_keypair_res'] }}"
    topology_outputs_aws_ec2: "{{ topology_outputs['ec2_res'] }}"
    topology_outputs_aws_s3: "{{ topology_outputs['aws_s3_res'] }}"
    topology_outputs_aws_ec2_key: "{{ topology_outputs['aws_ec2_key_res'] }}"
    topology_outputs_aws_cfn: "{{ topology_outputs['aws_cfn_res'] }}"
    topology_outputs_gcloud_gce: "{{ topology_outputs['gcloud_gce_res'] }}"
  roles:
    - { role: 'inventory_gen', when: state == 'present' }
