image: python:3.6
before_script:
  - pip install tox
stages:
  - style
  - test
  - deploy

flake8:
  stage: style
  script:
    - tox -e flake8

.job_template: &unittests
  stage: test
  script:
    - tox

py34-django1.11:
  <<: *unittests
  image: python:3.4
  variables:
    TOXENV: django111

py35-django1.11:
  <<: *unittests
  image: python:3.5
  variables:
    TOXENV: django111

py36-django1.11:
  <<: *unittests
  image: python:3.6
  variables:
    TOXENV: django111

postgres:
  <<: *unittests
  image: python:3.6
  services:
    - postgres
  variables:
    TOXENV: django111-postgres
    DATABASE_URL: postgres://postgres@postgres:5432

mysql:
  <<: *unittests
  image: python:3.6
  services:
    - mysql:5.7
  variables:
    TOXENV: django111-mysql
    MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    DATABASE_URL: mysql://root@mysql:3306

live:
  <<: *unittests
  image: python:3.6
  before_script:
    - pip install tox
    - echo -e $AFIP_TEST_KEY > testapp/test.key
    - echo -e $AFIP_TEST_CRT > testapp/test.crt
  variables:
    TOXENV: live
  allow_failure: true

docs:
  stage: test
  script:
    - tox -e docs

pypi:
  stage: deploy
  script:
    - pip install twine wheel
    - python setup.py sdist bdist_wheel
    - twine upload --config-file .pypirc -u $PYPI_USER -p $PYPI_PASSWORD dist/*
  only:
    - tags
  environment:
    name: PyPI
    url: https://pypi.python.org/pypi/django-afip
