
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-25T08:33:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "531778904cf854e4a3181b8de5f6c3faf88d1c1c",
 "version": "0.1.8-alpha"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
