
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: [--safe, --quiet, --line-length=79]
      python_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-ast
    -   id: mixed-line-ending
    -   id: debug-statements
    -   id: flake8
        additional_dependencies: [flake8-bugbear]
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.2.0
    hooks:
    - id: pyupgrade
