
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-13T10:45:35-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e950d0c9df2b08fa0af446589bc0eece4e5ce11",
 "version": "0.13.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
