[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "flinx"
author = "Oliver Steele"
author-email = "steele@osteele.com"
home-page = "https://github.com/osteele/flinx"
classifiers = [
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Topic :: Documentation",
    "Topic :: Documentation :: Sphinx",
    "Topic :: Software Development :: Documentation",
    ]
description-file = "./README.rst"
requires = ["flit" , "Sphinx"]
requires-python = ">=3.5"

[tool.flit.scripts]
flinx = "flinx:main"

[tool.flit.metadata.urls]
Documentation = "https://flinx.readthedocs.io/en/latest/"
