
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-06T11:01:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b037b6de63cac278c7ddcf02bb38ff6928e93de1",
 "version": "1.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
