language: python
sudo: false
python:
  - 3.6
  - pypy3
script:
  - sphinx-build -b doctest -d docs/_build/doctrees docs docs/_build/html
  - coverage run -m zope.testrunner --test-path=src
after_success:
  - coveralls
notifications:
  email: dev-regression-tests@nextthought.com

install:
  - pip install -U pip --upgrade-strategy=eager
  - pip install -U setuptools --upgrade-strategy=eager
  - pip install -U coveralls coverage --upgrade-strategy=eager
  - pip install -U -e ".[test,docs]" --upgrade-strategy=eager

cache: pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
