name: climlab
channels:
  - conda-forge
  - defaults
dependencies:
    - python=3.6
    - numpy
    - scipy
    - netCDF4
    - xarray
    - sphinx
    - matplotlib
    - ipython
    - jupyter
    - future
    - sphinx_rtd_theme
    #- nbsphinx
    - sphinxcontrib-bibtex
    - numpydoc
