[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
dist-name = "rtd-flinx-shim"
module = "rtd_flinx_shim"
author = "Oliver Steele"
author-email = "steele@osteele.com"
home-page = "https://github.com/osteele/rtd-flinx-shim"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Topic :: Documentation :: Sphinx",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules"
    ]
description-file = "./README.rst"
requires = ["flinx"]
requires-python = ">=3.0"

[tool.poetry]
name = "rtd-flinx-shim"
version = "0.1.0"
description = "Trick RTD into using with Flinx."
authors = ["Oliver Steele <steele@osteele.com>"]
readme = "README.rst"
repository = "https://github.com/osteele/rtd-flinx-shim"

classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = ">=3.0"
flinx = "^0.1.1"

[tool.poetry.dev-dependencies]
keyring = "^12.2"

[tool.poetry.scripts]
rtd_flynx = 'rtd_flinx_shim:main'
