---
- name: Destroy qdrouterd(s)
  docker_container:
    name: "{{ item.router_id }}"
    state: absent
    force_kill: yes
  with_items: "{{ bus_conf }}"
  when: item.machine == inventory_hostname

- name: Destroy associated volumes
  docker_volume:
    name: "oo-qdr-{{ item.router_id }}-logs"
    state: absent
  with_items: "{{ bus_conf }}"
  when: item.machine == inventory_hostname

- name: Destroy the web gui
  docker_container:
    image: msimonin/qpid-dispatch-gui
    name: qpid-dispatch-gui
    state: absent
    force_kill: yes
  when: inventory_hostname == groups['bus'][0]

- name: Destroy Websockify AMQP listener
  docker_container:
    name: websockify
    state: absent
    force_kill: yes
  when: inventory_hostname == groups['bus'][0]
