sudo: required
dist: trusty
services: docker
language: python
python: 3.5
cache:
  timeout: 600

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

notifications:
  webhooks:
    urls:
      - secure: "0sb4pr3j+oKITR6A3dfrX7+ZE3kJ73hmDMaHgzM6wuQ+KiXMlGcFWEkWCOPUkF/oYeTRlTct27oXj+RKkOaebF6sZ24SwCyKq/zpoawIjmDNi1IqIyqh90UZ1F0FpV+SZL93ge6L3+W5a+ruCDDrlBStAUUH9s1tuWft2LTxewGCdrOm/ZYtEdPGcQ5qjtXP7ZMikkJ7eYIppFfmM9oAL3eiq9FoVxX1X+S4BdIBG8IrZLmiTkvWe7cTZItzAcMzEco2+TnqjUgJ6lV0Ud0lr7iP5WcW2n34MDirQgA2YfJMPMqRUlb3wZ+o/cUrW/G3Qri4e9U9vidgH1G/cfNiER6YKHNt9izWvF7RImBs7wS+Zcmpq90ADXdCDKlCH9YIicngf8vJ7dSXGn+j1Aoba5yvImPK4eueay7SJFfWR29ClsHQgkhfXBCHaO2yHMTbo5ondCP5TcQVkqeuZvKpEG8IsFYQu9v4O9qzePcKF65SimIxIlvf76J8eHJtn+VguV8Dxa+5ixNNJalLcDlwWdlJm26A729fZ4Pl+JWdpTcn72yzRoCPXYh1L0oZzZDx8fp1W0RuvDW0sVwVhod4O63NtMbW58L9g5LjzeQ7EFlUlEDR8v+x8oCowir7T9NGAnGdO/gvVd3rJODf9olNyqZ53nHHRwFc+wtF8lKqDy4="

########################
########################
jobs:
  include:
  ######################## XENIAL - OLD COMPILER (Useful for Raspberry Pi)
  - stage: build+test
    os: linux
    env:
    - CMAKE_ARGS='-DBUILD_TESTS=ON'
    - TEST='TRUE'
    - CC_VER="4.9"
    - PLATFORM='xenial'
    script: "./travis/build.sh"

  ######################## XENIAL - TESTS
  - stage: build+test
    os: linux
    env:
    - CMAKE_ARGS='-DBUILD_TESTS=ON'
    - TEST='TRUE'
    - CC_VER="5"
    - PLATFORM='xenial'
    script: "./travis/build.sh"

  ######################## XENIAL - PYQRLLIB
  - stage: build+test
    os: linux
    env:
    - CMAKE_ARGS='-DBUILD_PYTHON=ON'
    - TEST='TRUE'
    - CC_VER="5"
    - PLATFORM='xenial'
    script: "./travis/build.sh"

  ######################## XENIAL-EMSCRIPTEN
  - stage: build+test
    os: linux
    env:
    - PLATFORM='xenial-emscripten'
    script: "./travis/build.sh"

#  ######################## OSX + TESTS
#  - stage: build+test
#    os: osx
#    if: branch = master
#    env:
#    - CMAKE_ARGS='-DBUILD_TESTS=ON'
#    - TEST='TRUE'
#    script:
#    - "./travis/build.sh"
#
#  ######################## OSX - PYQRLLIB
#  - stage: build+test
#    os: osx
#    if: branch = master
#    env:
#    - CMAKE_ARGS='-DBUILD_PYTHON=ON'
#    script:
#    - "./travis/build.sh"

  ########################
  - stage: publish
    if: tag =~ ^v
    os: linux
    env:
    - CC_VER="5"
    - PLATFORM='xenial'
    - DEPLOY='TRUE'
    script:
    - sudo pip install -U pip setuptools twine
    - "./travis/build.sh"

    deploy:
      provider: pypi
      skip_cleanup: true
      user: jleni
      password:
        secure: LEHilAb+FXCKVvd1/AEmVlUPyf8sOVYt/rMLZPr3bMEiwgK//lFJWlBPli9+G9ed4HjDpq/YFGpTKsRs9Etl4MWSnEJwYJPL0qBTWRCvEn1Py1kTI68dqRKR6oLpssj2BsLpuZvLt+2kE9PVvLSTGbwUGrnvob2AX2suUZcxnZD2q25TOnbZS2/M2F7SOy/0rVn6jlvGPwhMbdsmiLBStsx4rdiu84e1aryUDELSNTP7GtX61dmZs3et2Tpfz7uHXF++mxuT4hzjRe6mUKbtBekCy5EuAzI8vUTmys/m0llmB++gORSLeM22jfpGyfT7AxlkAxO3vlX3XLIythPIYcAEEjBA2xdt8GRlLWH3XLJJYWVEQgdA21sQLuQEGBepc44oKsdUH5t1Ok7kBYjvtQWJCa1/gv+GowKnU5159iJe6MBL9iJqzaz+tbGqKbQHpCvkPlNmipEBKVUANIx7IoXc/tHruCJtjp/vX4hbbOcT4674UaCcHtWpM3ME6EafC2r/nHNNA7rLoX1CP0RCrbSZJOGzhTZlyY9lB0qAmJe+3NDVSiY+6wO2qDFDN7nSl7BUBppPWHkhCVdXq3647RJB31djCguNfnjJLT7hoKkFTMFrrpkpvYUdPkJUAPqh3VZdl+esfMQnHctqBk0D8B+0lX6IJ9v8I5R/kyBs7/g=
      on:
        tags: true
        all_branches: true

  ########################
  - stage: publish
    if: tag =~ ^v
    os: linux
    env:
    - PLATFORM='xenial-emscripten'
    script:
    - "./travis/build.sh"
    - "./travis/patch_npmversion.sh"

    before_deploy: npm version

    deploy:
      provider: npm
      skip_cleanup: true
      email: "info@theqrl.org"
      api_key: $NPM_API_KEY
      on:
        tags: true
        all_branches: true
