# Config file for automatic testing at travis-ci.org

language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
matrix:
  allow_failures:
    - python: "nightly"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install flake8 coveralls coverage

before_script:
  - touch README.txt

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=mongodbforms setup.py test
  - flake8 .

after_success: coveralls

#  vim: set ts=4 sw=2 tw=80 et :
