# coding: utf-8

"""
    CERN Unified Storage API

    A unified storage API for all data-storage back-ends.

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.volume_read import VolumeRead


class TestVolumeRead(unittest.TestCase):
    """ VolumeRead unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVolumeRead(self):
        """
        Test VolumeRead
        """
        model = swagger_client.models.volume_read.VolumeRead()


if __name__ == '__main__':
    unittest.main()
