# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_framework.django_helpers.model_helpers.model_fields.unix_epoch_date_time_field
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True)),
                ('created_at', django_framework.django_helpers.model_helpers.model_fields.unix_epoch_date_time_field.UnixEpochDateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated', django_framework.django_helpers.model_helpers.model_fields.unix_epoch_date_time_field.UnixEpochDateTimeField(auto_now=True)),
                ('current_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('expire_at', django_framework.django_helpers.model_helpers.model_fields.unix_epoch_date_time_field.UnixEpochDateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True)),
                ('created_at', django_framework.django_helpers.model_helpers.model_fields.unix_epoch_date_time_field.UnixEpochDateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated', django_framework.django_helpers.model_helpers.model_fields.unix_epoch_date_time_field.UnixEpochDateTimeField(auto_now=True)),
                ('username', models.CharField(db_index=True, max_length=254, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('security_code', models.CharField(blank=True, max_length=255, null=True)),
                ('security_code_valid_until', django_framework.django_helpers.model_helpers.model_fields.unix_epoch_date_time_field.UnixEpochDateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
