# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: record.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='record.proto',
  package='datahub.record.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x0crecord.proto\x12\x14\x64\x61tahub.record.proto\"(\n\nStringPair\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"\x1a\n\tFieldData\x12\r\n\x05value\x18\x01 \x01(\x0c\"H\n\x10RecordAttributes\x12\x34\n\nattributes\x18\x01 \x03(\x0b\x32 .datahub.record.proto.StringPair\";\n\nRecordData\x12-\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1f.datahub.record.proto.FieldData\"\x80\x02\n\x0bRecordEntry\x12\x10\n\x08shard_id\x18\x01 \x01(\t\x12\x10\n\x08hash_key\x18\x02 \x01(\t\x12\x15\n\rpartition_key\x18\x03 \x01(\t\x12\x0e\n\x06\x63ursor\x18\x04 \x01(\t\x12\x13\n\x0bnext_cursor\x18\x05 \x01(\t\x12\x10\n\x08sequence\x18\x06 \x01(\x03\x12\x13\n\x0bsystem_time\x18\x07 \x01(\x03\x12:\n\nattributes\x18\x08 \x01(\x0b\x32&.datahub.record.proto.RecordAttributes\x12.\n\x04\x64\x61ta\x18\t \x02(\x0b\x32 .datahub.record.proto.RecordData\"G\n\x11PutRecordsRequest\x12\x32\n\x07records\x18\x01 \x03(\x0b\x32!.datahub.record.proto.RecordEntry\"H\n\x0c\x46\x61iledRecord\x12\r\n\x05index\x18\x01 \x02(\x05\x12\x12\n\nerror_code\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"f\n\x12PutRecordsResponse\x12\x14\n\x0c\x66\x61iled_count\x18\x01 \x01(\x05\x12:\n\x0e\x66\x61iled_records\x18\x02 \x03(\x0b\x32\".datahub.record.proto.FailedRecord\"5\n\x11GetRecordsRequest\x12\x0e\n\x06\x63ursor\x18\x01 \x02(\t\x12\x10\n\x05limit\x18\x02 \x01(\x05:\x01\x31\"\x8b\x01\n\x12GetRecordsResponse\x12\x13\n\x0bnext_cursor\x18\x01 \x02(\t\x12\x14\n\x0crecord_count\x18\x02 \x02(\x05\x12\x16\n\x0estart_sequence\x18\x03 \x01(\x03\x12\x32\n\x07records\x18\x04 \x03(\x0b\x32!.datahub.record.proto.RecordEntry')
)




_STRINGPAIR = _descriptor.Descriptor(
  name='StringPair',
  full_name='datahub.record.proto.StringPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='datahub.record.proto.StringPair.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='datahub.record.proto.StringPair.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=78,
)


_FIELDDATA = _descriptor.Descriptor(
  name='FieldData',
  full_name='datahub.record.proto.FieldData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='datahub.record.proto.FieldData.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=106,
)


_RECORDATTRIBUTES = _descriptor.Descriptor(
  name='RecordAttributes',
  full_name='datahub.record.proto.RecordAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attributes', full_name='datahub.record.proto.RecordAttributes.attributes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=180,
)


_RECORDDATA = _descriptor.Descriptor(
  name='RecordData',
  full_name='datahub.record.proto.RecordData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='datahub.record.proto.RecordData.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=241,
)


_RECORDENTRY = _descriptor.Descriptor(
  name='RecordEntry',
  full_name='datahub.record.proto.RecordEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shard_id', full_name='datahub.record.proto.RecordEntry.shard_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash_key', full_name='datahub.record.proto.RecordEntry.hash_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partition_key', full_name='datahub.record.proto.RecordEntry.partition_key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cursor', full_name='datahub.record.proto.RecordEntry.cursor', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_cursor', full_name='datahub.record.proto.RecordEntry.next_cursor', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='datahub.record.proto.RecordEntry.sequence', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='system_time', full_name='datahub.record.proto.RecordEntry.system_time', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='datahub.record.proto.RecordEntry.attributes', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='datahub.record.proto.RecordEntry.data', index=8,
      number=9, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=500,
)


_PUTRECORDSREQUEST = _descriptor.Descriptor(
  name='PutRecordsRequest',
  full_name='datahub.record.proto.PutRecordsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='datahub.record.proto.PutRecordsRequest.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=573,
)


_FAILEDRECORD = _descriptor.Descriptor(
  name='FailedRecord',
  full_name='datahub.record.proto.FailedRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='datahub.record.proto.FailedRecord.index', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='datahub.record.proto.FailedRecord.error_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='datahub.record.proto.FailedRecord.error_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=575,
  serialized_end=647,
)


_PUTRECORDSRESPONSE = _descriptor.Descriptor(
  name='PutRecordsResponse',
  full_name='datahub.record.proto.PutRecordsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='failed_count', full_name='datahub.record.proto.PutRecordsResponse.failed_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failed_records', full_name='datahub.record.proto.PutRecordsResponse.failed_records', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=649,
  serialized_end=751,
)


_GETRECORDSREQUEST = _descriptor.Descriptor(
  name='GetRecordsRequest',
  full_name='datahub.record.proto.GetRecordsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cursor', full_name='datahub.record.proto.GetRecordsRequest.cursor', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit', full_name='datahub.record.proto.GetRecordsRequest.limit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=753,
  serialized_end=806,
)


_GETRECORDSRESPONSE = _descriptor.Descriptor(
  name='GetRecordsResponse',
  full_name='datahub.record.proto.GetRecordsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='next_cursor', full_name='datahub.record.proto.GetRecordsResponse.next_cursor', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='record_count', full_name='datahub.record.proto.GetRecordsResponse.record_count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_sequence', full_name='datahub.record.proto.GetRecordsResponse.start_sequence', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='records', full_name='datahub.record.proto.GetRecordsResponse.records', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=809,
  serialized_end=948,
)

_RECORDATTRIBUTES.fields_by_name['attributes'].message_type = _STRINGPAIR
_RECORDDATA.fields_by_name['data'].message_type = _FIELDDATA
_RECORDENTRY.fields_by_name['attributes'].message_type = _RECORDATTRIBUTES
_RECORDENTRY.fields_by_name['data'].message_type = _RECORDDATA
_PUTRECORDSREQUEST.fields_by_name['records'].message_type = _RECORDENTRY
_PUTRECORDSRESPONSE.fields_by_name['failed_records'].message_type = _FAILEDRECORD
_GETRECORDSRESPONSE.fields_by_name['records'].message_type = _RECORDENTRY
DESCRIPTOR.message_types_by_name['StringPair'] = _STRINGPAIR
DESCRIPTOR.message_types_by_name['FieldData'] = _FIELDDATA
DESCRIPTOR.message_types_by_name['RecordAttributes'] = _RECORDATTRIBUTES
DESCRIPTOR.message_types_by_name['RecordData'] = _RECORDDATA
DESCRIPTOR.message_types_by_name['RecordEntry'] = _RECORDENTRY
DESCRIPTOR.message_types_by_name['PutRecordsRequest'] = _PUTRECORDSREQUEST
DESCRIPTOR.message_types_by_name['FailedRecord'] = _FAILEDRECORD
DESCRIPTOR.message_types_by_name['PutRecordsResponse'] = _PUTRECORDSRESPONSE
DESCRIPTOR.message_types_by_name['GetRecordsRequest'] = _GETRECORDSREQUEST
DESCRIPTOR.message_types_by_name['GetRecordsResponse'] = _GETRECORDSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StringPair = _reflection.GeneratedProtocolMessageType('StringPair', (_message.Message,), dict(
  DESCRIPTOR = _STRINGPAIR,
  __module__ = 'record_pb2'
  # @@protoc_insertion_point(class_scope:datahub.record.proto.StringPair)
  ))
_sym_db.RegisterMessage(StringPair)

FieldData = _reflection.GeneratedProtocolMessageType('FieldData', (_message.Message,), dict(
  DESCRIPTOR = _FIELDDATA,
  __module__ = 'record_pb2'
  # @@protoc_insertion_point(class_scope:datahub.record.proto.FieldData)
  ))
_sym_db.RegisterMessage(FieldData)

RecordAttributes = _reflection.GeneratedProtocolMessageType('RecordAttributes', (_message.Message,), dict(
  DESCRIPTOR = _RECORDATTRIBUTES,
  __module__ = 'record_pb2'
  # @@protoc_insertion_point(class_scope:datahub.record.proto.RecordAttributes)
  ))
_sym_db.RegisterMessage(RecordAttributes)

RecordData = _reflection.GeneratedProtocolMessageType('RecordData', (_message.Message,), dict(
  DESCRIPTOR = _RECORDDATA,
  __module__ = 'record_pb2'
  # @@protoc_insertion_point(class_scope:datahub.record.proto.RecordData)
  ))
_sym_db.RegisterMessage(RecordData)

RecordEntry = _reflection.GeneratedProtocolMessageType('RecordEntry', (_message.Message,), dict(
  DESCRIPTOR = _RECORDENTRY,
  __module__ = 'record_pb2'
  # @@protoc_insertion_point(class_scope:datahub.record.proto.RecordEntry)
  ))
_sym_db.RegisterMessage(RecordEntry)

PutRecordsRequest = _reflection.GeneratedProtocolMessageType('PutRecordsRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUTRECORDSREQUEST,
  __module__ = 'record_pb2'
  # @@protoc_insertion_point(class_scope:datahub.record.proto.PutRecordsRequest)
  ))
_sym_db.RegisterMessage(PutRecordsRequest)

FailedRecord = _reflection.GeneratedProtocolMessageType('FailedRecord', (_message.Message,), dict(
  DESCRIPTOR = _FAILEDRECORD,
  __module__ = 'record_pb2'
  # @@protoc_insertion_point(class_scope:datahub.record.proto.FailedRecord)
  ))
_sym_db.RegisterMessage(FailedRecord)

PutRecordsResponse = _reflection.GeneratedProtocolMessageType('PutRecordsResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUTRECORDSRESPONSE,
  __module__ = 'record_pb2'
  # @@protoc_insertion_point(class_scope:datahub.record.proto.PutRecordsResponse)
  ))
_sym_db.RegisterMessage(PutRecordsResponse)

GetRecordsRequest = _reflection.GeneratedProtocolMessageType('GetRecordsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETRECORDSREQUEST,
  __module__ = 'record_pb2'
  # @@protoc_insertion_point(class_scope:datahub.record.proto.GetRecordsRequest)
  ))
_sym_db.RegisterMessage(GetRecordsRequest)

GetRecordsResponse = _reflection.GeneratedProtocolMessageType('GetRecordsResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETRECORDSRESPONSE,
  __module__ = 'record_pb2'
  # @@protoc_insertion_point(class_scope:datahub.record.proto.GetRecordsResponse)
  ))
_sym_db.RegisterMessage(GetRecordsResponse)


# @@protoc_insertion_point(module_scope)
