
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-08T17:46:51+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "69e8bd8491e96458e46457cb6ba1bf3472b20634",
 "version": "0.0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
