
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-28T10:02:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4b479e172ca02fb5d16532db70fde1e89caa5c35",
 "version": "0.0.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
