
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9c38d928490ea00bc54cbf40fbc9bdd9e7ae62f2",
 "version": "1.0.0.post.dev732"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
