
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-21T16:07:15-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "2dfe4b7902c8307191961b3a675f5bc25585a1fe",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
