language: python
sudo: false
os:
- linux
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -U pip
- pip install -U setuptools
- pip install -U tox
- pip install -U tox-travis
- pip install python-coveralls
- pip install coverage
script:
- tox -v --recreate
after_success:
- coveralls
deploy:
  provider: pypi
  user: levinoecker
  password:
    secure: zdTuqSbWgCg1A2HpDPYCNAUxxRGjXjICxHlkQuFpmPRLOjvhGHfd0tvsV1VY6eyx8XWb3tKsi2zEVN9UtKlajwyeuMAGOyi52SeQ9j6ZCmXNji+aj/CCBMEy6hscAntY8tlcmq61Sfk7wDogQjj/OjC70vCKMVnKM/5Jfha9O7BUMADhPxD7J2yepViACkICcPGM0YqBDz3gOrZSLdBmkrjklIMwK7+WoswEc/W926iMFvcx7O4svMUsbdFhfrj/s6WgmyB5/PCRJFxCRYSZv84gIMF+QiQYluLZd3+NyBt0p9+sS5d2BSaTUz3Q4lZZdvqvEnrmkA+41AuZQTZ4Ws838q63IbNorvHnfjbzHSSha4eEVaGY+8obGaCQ2lNTyGY/tyIAFp2umjbtITS3D+PWghVe4TbCjWL/tC8ucRrZmeokKupHLBiy70X+S/uD7wxrT84NXjfAWFuHehcWVOYXQdqR4aDfkrvW2vNokUp7uaKR6dvfi2FioVKk7tq7U8tBqFP+JG4i9ttXY6dbsPZjBQUSyDUdEiqSsh1GCBokx/L1NpOO8F20zNDylRpkn2CI+cx9NhB9shR7GaEJ02yj5sdwlL/z8uIq8rMVgMIWR710gC2GzgeyGMvNvWTpNB/uQVg9hz6v+tpxkC1MhA2nG3BXljIoDDMBEEMPX7o=
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true
    python: '3.6'
