language: python
python:
  - "3.3"
  - "3.4"
  - "3.6"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install python-coveralls pytest-cov"
  - "python setup.py install"
script: py.test tests/ --doctest-modules  -v --cov egcg_core --cov-report term-missing
after_success:
  - coveralls
# branches:
#   only:
#     - master
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
