language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3.5-5.8.0
env:
  - PYTEST=2.8.7
  - PYTEST=2.9.2
  - PYTEST=3.0.7
  - PYTEST=3.1.3
  - PYTEST=3.2.1
  - PYTEST=3.3.2
  - PYTEST=3.4.2
  - PYTEST=3.5.1
  - PYTEST=3.6.0
install:
  - pip install -q pytest==$PYTEST
  - pip install -q -e .
script: py.test
