
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-26T12:46:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3b798c7d9d82197089f3b113e1bfa076b2dcff2b",
 "version": "2.0.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
