
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e2fdee3fc68f273a63f12ba565dacaea6078f083",
 "version": "0.9.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
