
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-11T20:30:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b7d23b5236f3c6af08df0984c674ffaa5bde3d8",
 "version": "v0.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
