
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-15T12:59:01-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5464b0d3cfa764378c55f59473719c315a054a68",
 "version": "4.1.1a6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
