"""LICENSE
Copyright 2015 Hermann Krumrey <hermann@krumreyh.com>

This file is part of manga-dl.

manga-dl is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

manga-dl is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with manga-dl.  If not, see <http://www.gnu.org/licenses/>.
LICENSE"""


class MangaPage(object):
    """
    Class that models a page in a Manga chapter
    """

    page_number = -1
    """
    The page's page number
    """

    image_url = ""
    """
    The URL to the page's image
    """

    page_name = ""
    """
    The page's name. Is normally generated by the get_page_name method
    """

    def __init__(self, page_number: int, image_url: str) -> None:
        """
        Initializes the Manga Page with a page number and an image URL

        :param page_number: the page number
        :param image_url: the image URL
        :return: None
        """
        self.page_number = page_number
        self.image_url = image_url

    def set_page_name(self, name: str) -> None:
        """
        Sets the page's name

        :param name: the name of the page
        :return: None
        """
        self.page_name = name

    def get_page_name(self) -> str:
        """
        Generates a Page name for this page based on the page number, or
        returns the page name previously set by the set_page_name method.

        :return: the page name as a string
        """
        return self.page_name if self.page_name != "" \
            else "Page " + str(self.page_number).zfill(3)
