"""LICENSE
Copyright 2015 Hermann Krumrey <hermann@krumreyh.com>

This file is part of manga-dl.

manga-dl is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

manga-dl is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with manga-dl.  If not, see <http://www.gnu.org/licenses/>.
LICENSE"""

# import
from typing import List
from manga_dl.entities.MangaChapter import MangaChapter


class MangaVolume(object):
    """
    Class that models a Manga chapter.

    Contains a list of chapters
    """

    chapters = []
    """
    List of Manga chapters in this volume
    """

    volume_number = -1
    """
    The volume's Volume Number
    """

    volume_name = ""
    """
    The volume's name. Is normally generated by the get_volume_name method
    """

    def __init__(self, volume_number: int, chapters: List[MangaChapter]) \
            -> None:
        """
        Initializes a Manga volume with a list of chapters

        :param volume_number: The volume number of this volume
        :param chapters: the chapters belonging to this volume
        :return: None
        """
        self.volume_number = volume_number
        self.chapters = chapters

    def set_volume_name(self, name: str) -> None:
        """
        Sets the volume's name

        :param name: the name of the volume
        :return:  None
        """
        self.volume_name = name

    def get_volume_name(self) -> str:
        """
        Generates a Volume name for this volume based on the volume number,
        or returns the volume name previously set by the set_volume_name
        method.

        :return: the volume name as a string
        """
        return self.volume_name if self.volume_name != "" \
            else "Volume " + str(self.volume_number).zfill(2)

    def get_chapters(self) -> List[MangaChapter]:
        """
        :return: a list of manga chapters belonging to this volume
        """
        return self.chapters
