language: python

sudo: false

matrix:
  include:
    - python: '3.4'
      env: PYQT4=true ORANGE="3.7.0"

    - python: '3.5'
      env: PYQT5=true ORANGE="3.7.0"

    - python: '3.5'
      env: PYQT5=true ORANGE="release"

    - python: '3.5'
      env: PYQT5=true ORANGE="master"

cache:
    apt: true
    pip: true
    directories:
        - $TRAVIS_BUILD_DIR/pyqt

install:
    # Update pip to be able to install wheel dependencies
    - pip install -U pip wheel
    - source $TRAVIS_BUILD_DIR/.travis/install_pyqt.sh
    - source $TRAVIS_BUILD_DIR/.travis/install_orange.sh
    - pip install -e .

script:
    # Screen must be 24bpp lest pyqt5 crashes, see pytest-dev/pytest-qt/35
    - export XVFBARGS="-screen 0 1280x1024x24"
    - catchsegv xvfb-run -a -s "$XVFBARGS" python setup.py test
