
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-26T10:11:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "752fb4243f8ea67db9c7a9c5841c8cac4c1e139f",
 "version": "2.2.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
