# Generated by Django 2.0 on 2017-12-11 05:38

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyHealth',
            fields=[
                ('state', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
                ('severity', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
                ('history', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
                ('uid', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeartHealthTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(db_index=True)),
                ('time', models.DateTimeField()),
                ('heartrate', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SleepHealthTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(db_index=True)),
                ('time', models.DateTimeField()),
                ('hours', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmokeHealthTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(db_index=True)),
                ('time', models.DateTimeField()),
                ('smokes', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
