# Generated by Django 2.0 on 2017-12-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyhealth',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bodyhealth',
            name='uid',
            field=models.IntegerField(db_index=True),
        ),
    ]
