# Generated by Django 2.0.3 on 2018-06-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signoff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentconsent',
            name='signed_name',
            field=models.TextField(default='', help_text='The name entered in the signature box when the user signed this document.'),
            preserve_default=False,
        ),
    ]
