
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ffcf2cd8879ad2a32216c4e2bee8cde131e8d8ff",
 "version": "0.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
