
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-15T08:10:48-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "aee2e41100230675baeeee8dba38edd7c3b80017",
 "version": "1.22.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
