
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-07T15:35:59-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5f4abbd62a3983c8e30b0c03ed69e8de8039e967",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
