#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['neonrvm']

package_data = \
{'': ['*']}

install_requires = \
['numpy']

setup(name='neonrvm',
      version='0.2.0',
      description='Python bindings for the neonrvm machine learning library.',
      author='Siavash Eliasi',
      author_email='siavashserver@gmail.com',
      url='https://github.com/siavashserver/neonrvm',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3',
     )
