# Lets run on the new infrastructure
sudo: false

# We're having issues on the default Trusty setup, lets wait for now
dist: precise

language: python

install:
  - pip install tox codecov coveralls

defaults:
  - &main_test_script
    stage: testing
    before_script:
    # Make a MariaDB database
    # Fix wierdness with MariaDB on Travis - https://github.com/mozilla/kitsune/pull/2453/commits/229db28973f00dfc4fa7b386f266caf3417966a0  
      - if [[ $DB == mariadb ]]; then ./aristotle_mdr/tests/bin/prep_mysql.sh ; fi
      - if [[ $SEARCH == elastic ]]; then sudo service elasticsearch start && sleep 10; fi
    # Make a posgres database
      - if [[ $DB == postgres* ]]; then ./aristotle_mdr/tests/bin/prep_psql.sh; fi

    script:
      - |
        case "$DB" in
          mariadb) export DATABASE_URL=mysql://travis:@localhost:3306/aristotle_test_db;;
         postgres) export DATABASE_URL=postgresql://postgres:@localhost/aristotle_test_db;;
           sqlite) export DATABASE_URL=sqlite:///./db.db;;
                *) export DATABASE_URL=sqlite:///./db.db;;
        esac
        echo "Running script with DATABASE_URL="$DATABASE_URL
        echo "Running script with DB="$DB
        tox -e dj$DJANGO_VERSION-test-linux-db-$DB-search-$SEARCH --skip-missing-interpreters
    services:
      - postgresql
      - redis-server
      - elasticsearch
      - mariadb
    addons:
      apt:
        sources:
          - elasticsearch-2.x
        packages:
          - elasticsearch
      code_climate:
        repo_token: ac63d774ebdd641ef502acf1588b36248726a28a50e4e1f4ba4295a157477f54
      mariadb: '10.1'

  - &main_test_script_py36
      python: 3.6
      <<: *main_test_script

  - &test_accessibility_py36
    stage: accessibility
    python: 3.6
    script: tox -e ally-$ALLY --skip-missing-interpreters

jobs:

  include:
    - stage: stylecheck
      python: 3.6
      script: tox -e flake8 --skip-missing-interpreters

    - stage: documentation
      python: 3.6
      script: tox -e docs --skip-missing-interpreters
    

    - stage: testing
      env: DJANGO_VERSION='1.11'  DB=sqlite  SEARCH=elastic
      <<: *main_test_script_py36
    - stage: testing
      env: DJANGO_VERSION='1.11'  DB=postgres  SEARCH=elastic
      <<: *main_test_script_py36
    - stage: testing
      env: DJANGO_VERSION='1.11'  DB=sqlite    SEARCH=whoosh
      <<: *main_test_script_py36
    - stage: testing
      env: DJANGO_VERSION='1.11'  DB=postgres  SEARCH=whoosh
      <<: *main_test_script_py36
    - stage: testing
      env: DJANGO_VERSION='1.11'  DB=mariadb   SEARCH=whoosh
      <<: *main_test_script_py36
    - stage: testing
      env: DJANGO_VERSION='1.11'  DB=mariadb   SEARCH=elastic
      <<: *main_test_script_py36
    
      # Possible failures:
    # - stage: testing
    #   env: DJANGO_VERSION='1.11'  DB=sqlite    SEARCH=whoosh   VARIANT=haystack
    #   <<: *main_test_script_py36
    # - stage: testing
    #   env: DJANGO_VERSION='1.11'  DB=sqlite    SEARCH=elastic  VARIANT=haystack
    #   <<: *main_test_script_py36

  # Test Accessibility
    - <<: *test_accessibility_py36
      env: ALLY=metadata_item
    - <<: *test_accessibility_py36
      env: ALLY=metadata_action
    - <<: *test_accessibility_py36
      env: ALLY=static

    - stage: deploy
      script: true
      deploy:
        provider: pypi
        user: Samuel.Spencer
        skip_upload_docs: true
        password:
          secure: hJVN74vhyDjG22Ei5/gz0g0d/KfaW2kzjx85c3pT+4jmbTOC3OcGN7Exj+/2wEAygvQDmlijRGJ0yldL3IpE0+N7TASs0/6dNf8fMoG0zRTcuu1ywhUhSgqntRGMjRBpbXeVUeb6ydeAciDkrkmfyuGVQd6bXJQeCxcdU1X5iJ+mnbS9Lu1oUfXt6MZroMImwh+ZCvDn95e8QMFbSmO/3OE7CBtBiCaUMemlgzf1THJsw0JoO/GaU37NEjmsnt6xg8EcXRi/h+Pznnr+8LEs6gqcNRg8uS0mh3e6B3ynvovY6Pr8YdAazG6FTFezc3eQWjViQyBxHGbCcY1z0w7bATa+BT18k2/I6dfF6MFoitPtTmJ9tQEB1HOdL/ngJoYEa2TQxxsCal4qqCWNEgP6O5Jl7uK4u1y00wXQ1M3scGmP1kxu+4DWY9ywfnBvbF8SNKLd4qEkdxQIkZBYd7/4aU/3pHFVE1f+J7LSzLt8gIy/hnLCB23T/DEaLnQJDIBlP4Kcpb277vkayVjuRuGNfU5QXf29Sj4PKvXbVS9gtYDY8U5KheOhb7MmWTlq+WfGvyrpgLfasFQDjWGOqs4oJ4LDO4IJ6BG40LX/OozTXoiT1//DcwDU34SJQlfTiTidZMeOq1fdpQNG84Tig2MkuRnmvO8LF5uIS0I6G3GWP6U=
        on:
          branch: master
          distributions: sdist bdist_wheel
          repo: aristotle-mdr/aristotle-metadata-registry

  # allow_failures:
    # - env: DJANGO_VERSION='1.11'  DB=sqlite    SEARCH=whoosh   VARIANT=haystack
    # - env: DJANGO_VERSION='1.11'  DB=sqlite    SEARCH=elastic  VARIANT=haystack


after_success:
  - coveralls
  - codecov
