build: false

services:
  - mssql2016

environment:
  global:
    APPVEYOR: 1
  matrix:
      - DJANGO_VERSION: '1.11'
        DB: mssql
        DATABASE_URL: mssql://sa:Password12!@(local)\SQL2016/master?driver=SQL+Server+Native+Client+11.0
        SEARCH: whoosh
        PYTHON_HOME: "C:/Python35"
      - DJANGO_VERSION: '1.11'
        DB: mssql
        DATABASE_URL: mssql://sa:Password12!@(local)\SQL2016/master?driver=SQL+Server+Native+Client+11.0
        SEARCH: whoosh
        PYTHON_HOME: "C:/Python35-x64"

install:
  - cmd: |
        set PATH=%PYTHON_HOME%;%PYTHON_HOME%\Scripts;%PATH%
        pip install tox

# command to run tests
test_script:
  - cmd: |
        tox -e dj%DJANGO_VERSION%-test-azure-db-%DB%-search-%SEARCH% --skip-missing-interpreters
