
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e701bd2b92a3a89b400e0362423ced6e08941f14",
 "version": "1952"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
