version: '{branch}-{build}'
build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'
matrix:
  fast_finish: true
environment:
  global:
    WITH_ENV: 'cmd /E:ON /V:ON /C .\ci\run_with_env.cmd'
  matrix:
    - TOXENV: check
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64

    - TOXENV: docs
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64

    - TOXENV: 'py27,codecov'
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 32

    - TOXENV: 'py27,codecov'
      PYTHON_HOME: C:\Python27-x64
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 64

    - TOXENV: 'py36,codecov'
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 32

    - TOXENV: 'py36,codecov'
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64

init:
  - ps: echo $env:TOXENV
  - ps: echo "Python $env:PYTHON_VERSION (${env:PYTHON_ARCH}bit) from $env:PYTHON_HOME"
  - ps: ls C:\Python*
install:
  - git submodule update --init --recursive
  - '%PYTHON_HOME%\Scripts\pip install --upgrade tox setuptools virtualenv wheel'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
test_script:
  - '%WITH_ENV% %PYTHON_HOME%\Scripts\tox -v'

on_failure:
  - ps: dir "env:"
  - ps: echo $env:path
  - ps: get-content .tox\*\log\*
artifacts:
  - path: dist\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
