# This file is generated by setup.py. DO NOT EDIT!

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

version = '1.2.1'
git_version = 'c7b60050ad6ae963bf2cc1d0eb3c32b07eb7eeed'
