#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['quayadmin']

package_data = \
{'': ['*']}

install_requires = \
['attrs', 'treq', 'twisted[tls]']

entry_points = \
{'console_scripts': ['quay-admin = quayadmin._impl:script']}

setup(name='quayadmin',
      version='0.1.2',
      description='Do administrative stuff on quay.io.',
      author='Jonathan M. Lange',
      author_email='jml@mumak.net',
      url='https://github.com/jml/quay-admin',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
     )
