---
- name: Common configuration
  hosts: all
  roles:
    - common
    - registry
    - telegraf

- name: Apply role chrony
  hosts:
    - chrony-server
    - chrony
  roles:
    - chrony

- name: Deploy influx
  hosts: influxdb
  roles:
    - influxdb

- name: Deploy the grafana
  hosts: grafana
  roles:
    - grafana

# NOTE(msimonin): The control bus is assumed to be rabbitmq only
# configuration of this bus is taken from the conf
# which let's us envision to enable other driver (e.g qdr) for the 
# control bus (we would need to introduce a control_bus_driver_type variable 
# somewhere to switch over) 
- name: Control-bus deployment
  hosts: control-bus
  roles:
      - rabbitmq
  vars:
    current_bus_conf: "{{ control_bus_conf }}"

- name: RabbitMQ deployment
  hosts:
    - bus
  vars:
    current_bus_conf: "{{ bus_conf }}"
  roles:
    - { role: rabbitmq,
        when: broker == "rabbitmq" }

- name: Qpid dispatch deployment
  hosts:
    - bus
  vars:
    current_bus_conf: "{{ bus_conf }}"
  roles:
    - { role: qdr,
        when: broker == "qdr" }
