BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBB gettext(u'Add new 2FA device') BBBBBBBB
BBBBB BBBBBBB
     gettext(u'Two Factor Settings') 
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            BBBBBBBBBB
            XXX XXXXXXXXXXXXXXX
                XXXX
                    XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                        XXXXXXXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX

                            XXXX XXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                        XXXXXX

                    XXXXXX
                XXXXX
                BBB BBBBB BB BBBB

                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBB
                BBBBBB
                XXX XXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Create') X XXXXXXXXXXXXXX XX
                XXXXX
            XXXXX
        XXXXXXX
    XXXXXX
BBBBBBBB
