# encoding: utf-8

from datetime import datetime as _dt

TZ_ADJUST = (_dt.now() - _dt.utcnow()).seconds

ONE_SECOND = 1
FIVE_SECONDS = 5 * ONE_SECOND
TEN_SECONDS = 2 * FIVE_SECONDS
FIFTEEN_SECONDS = 3 * FIVE_SECONDS
THIRTY_SECONDS = 2 * FIFTEEN_SECONDS
FORTY_FIVE_SECONDS = 3 * FIFTEEN_SECONDS

ONE_MINUTE = 2 * THIRTY_SECONDS
FIVE_MINUTES = 5 * ONE_MINUTE
TEN_MINUTES = 2 * FIVE_MINUTES
FIFTEEN_MINUTES = 3 * FIVE_MINUTES
THIRTY_MINUTES = 2 * FIFTEEN_MINUTES
FORTY_FIVE_MINUTES = 3 * FIFTEEN_MINUTES

ONE_HOUR = 2 * THIRTY_MINUTES
TWO_HOURS = 2 * ONE_HOUR
THREE_HOURS = 3 * ONE_HOUR
FOUR_HOURS = 2 * TWO_HOURS
FIVE_HOURS = 5 * ONE_HOUR
SIX_HOURS = 2 * THREE_HOURS
SEVEN_HOURS = 7 * ONE_HOUR
EIGHT_HOURS = 2 * FOUR_HOURS
NINE_HOURS = 3 * THREE_HOURS
TEN_HOURS = 2 * FIVE_HOURS

TWELVE_HOURS = 2 * SIX_HOURS
EIGHTEEN_HOURS = 3 * SIX_HOURS
TWENTY_FOUR_HOURS = 2 * TWELVE_HOURS
THIRTY_SIX_HOURS = 3 * TWELVE_HOURS
FORTY_EIGHT_HOURS = 2 * TWENTY_FOUR_HOURS

ONE_DAY = TWENTY_FOUR_HOURS
TWO_DAYS = FORTY_EIGHT_HOURS

ONE_WEEK = 7 * ONE_DAY
TWO_WEEKS = 2 * ONE_WEEK

# Constants below here are all based on multiples of one week so may not be exact

ONE_MONTH = 4 * ONE_WEEK
THREE_MONTHS = 13 * ONE_WEEK
SIX_MONTHS = 26 * ONE_WEEK
NINE_MONTHS = 39 * ONE_WEEK

ONE_YEAR = 52 * ONE_WEEK
