package:
  name: pyctest
  version: '0.0.1'

build:
  number: 0
  #ignore_prefix_files: True
  #detect_binary_files_with_prefix: False
  binary_relocation: False

source:
  git_rev: 2a8331da3f3c3a9b377a6ac4f40e1a630bacc626
  git_url: https://github.com/jrmadsen/pyctest.git

requirements:
  host:
  - python
  - setuptools
  - cmake
  - openssl
  run:
  - python
  - openssl

test:
  imports:
  - pyctest
  - pyctest.pyctest
  - pyctest.pycmake

about:
  home: https://jrmadsen.github.io/pyctest/
  license: MIT
  summary: "Python bindings to select portions of CMake/CTest package -- enabling generation of CTests for CDash submission without a CMake build system"
