- package: {{ PIPELINE_MODEL_NAME }}
  version: {{ PIPELINE_MODEL_TAG }}
  author-email:
  tags: [{{ PIPELINE_MODEL_NAME }}, {{ PIPELINE_MODEL_TAG }}, {{ PIPELINE_MODEL_TYPE }}, model]

# -------------------------------------------------------------------
# base (shared config)
# -------------------------------------------------------------------

- config: base
  operations:
    train:
      description: 'Train'
      cmd: 'pipeline_train'
      flags:
        train_steps:
          description: Training steps
          default: 1
        batch_size:
          description: Number of images to include in a training batch
          default: 1
        num_epochs:
          description: Number of epochs
          default: 1
        data_dir:
          description: Training dataset
          default: ./input/training
        model_dir:
          description: Output directory
          default: ./checkpoint
        export_dir:
          description: Export dir
          default: ./pipeline_tfserving
    evaluate:
      description: 'Evaluate'
      cmd: 'pipeline_train --test'
      requires:
        - trained-model
  resources:
    trained-model:
      private: yes
      sources:
        - operation: train
          select:
            - model.ckpt.*
            - checkpoint

- model: {{ PIPELINE_MODEL_NAME }}
  extends: base
  params:
    train_cmd: pipeline_train
    model_desc: {{ PIPELINE_MODEL_NAME }}
    model_name: {{ PIPELINE_MODEL_NAME }}
    model_tag: {{ PIPELINE_MODEL_TAG }}
    model_type: {{ PIPELINE_MODEL_TYPE }}
    model_runtime: {{ PIPELINE_MODEL_RUNTIME }}
    model_chip: {{ PIPELINE_MODEL_CHIP }}
