# -*- coding: utf-8 -*-

figures = {
    'tick': '✔',
	'cross': '✖',
	'star': '★',
	'square': '▇',
	'squareSmall': '◻',
	'squareSmallFilled': '◼',
	'play': '▶',
	'circle': '◯',
	'circleFilled': '◉',
	'circleDotted': '◌',
	'circleDouble': '◎',
	'circleCircle': 'ⓞ',
	'circleCross': 'ⓧ',
	'circlePipe': 'Ⓘ',
	'circleQuestionMark': '?⃝',
	'bullet': '●',
	'dot': '․',
	'line': '─',
	'ellipsis': '…',
	'pointer': '❯',
	'pointerSmall': '›',
	'info': 'ℹ',
	'warning': '⚠',
	'hamburger': '☰',
	'smiley': '㋡',
	'mustache': '෴',
	'heart': '♥',
	'arrowUp': '↑',
	'arrowDown': '↓',
	'arrowLeft': '←',
	'arrowRight': '→',
	'radioOn': '◉',
	'radioOff': '◯',
	'checkboxOn': '☒',
	'checkboxOff': '☐',
	'checkboxCircleOn': 'ⓧ',
	'checkboxCircleOff': 'Ⓘ',
	'questionMarkPrefix': '?⃝'
}
