
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-22T22:35:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5623e8c9075d16d1794d9c9416fc383380f55b0b",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
