- name: "Ensure running as Root"
  assert:
    that:
      - "{{ ansible_user_uid }} == 0"
    msg: "Please run this role as root!"

- name: "Install Glances"
  block:
    - name: "Install `pip3`"
      apt:
        name: python3-pip
        state: latest
        update_cache: yes

    - name: "Upgrade `pip3`"
      pip:
        name: pip
        executable: pip3
        state: latest

    - name: "Install `glances` and `glances` optional dependencies"
      pip:
        name: "{{ item }}"
        executable: pip3
        state: latest
        extra_args: --user
      with_items:
        - glances
        - docker
        - bottle


- name: "Start Glances Web server as Daemon"
  block:
    - name: "Copy `glances.service` file"
      copy:
        src: glances.service
        dest: /etc/systemd/system/glances.service
        owner: root
        mode: 0644

    - name: "Start `glances.service` and set to start on boot"
      service:
        name: glances.service
        state: started
        enabled: yes
    
