os: Windows Server 2012

environment:
  matrix:
    - python_version: "C:\\Python35"
    - python_version: "C:\\Python35-x64"

install:
  - "SET PATH=%python_version%;%python_version%\\Scripts;%PATH%"
  - "python --version"
  - "pip install setuptools"
  - "pip install --upgrade setuptools"
  - "pip install requirements.txt"
  - "pip install -e ."

test_script:
  - "python setup.py test"

build: off