
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c48fac19b8246bc94cbb91eb7acd3a9ac898d5cf",
 "version": "0.8.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
