- name: "register var for async_outputs_os_server"
  set_fact:
    async_outputs_os_server: []

- name: "Wait on jobs"
  include: wait_on_os_server.yml
  vars:
    os_server_group: "{{ item }}"
  with_items:  "{{ topology_outputs['os_server_res'] }}"
