- name: "os_server: wait and update outputs using jobids "
  include: update_os_server_outputs.yml
  when: async

- name: "os_obj: wait and update outputs using jobids "
  include: update_os_obj_outputs.yml
  when: async

- name: "os_volume: wait and update outputs using jobids "
  include: update_os_volume_outputs.yml
  when: async

- name: "os_heat: wait and update outputs using jobids "
  include: update_os_heat_outputs.yml
  when: async

- name: "aws_ec2: wait and update outputs using jobids"
  include: update_aws_ec2_outputs.yml
  when: async

- name: "aws_cfn: wait and update outputs using jobids"
  include: update_aws_cfn_outputs.yml
  when: async

- name: "gcloud_gce: wait and update outputs using jobids"
  include: update_gcloud_gce_outputs.yml
  when: async
