###############################################################################
# Role: Standalone                                                            #
###############################################################################
- name: Standalone
  description: |
    EXPERIMENTAL. A standalone role that a minimal set of services.
    This can be used for testing in a single node configuration with the
    'openstack tripleo deploy --standalone' command.
  CountDefault: 1
  tags:
    - primary
    - controller
  disable_constraints: True
  ServicesDefault:
    - OS::TripleO::Services::Apache
    - OS::TripleO::Services::CACerts
    - OS::TripleO::Services::CertmongerUser
    - OS::TripleO::Services::Collectd
    - OS::TripleO::Services::ContainersLogrotateCrond
    - OS::TripleO::Services::Docker
    - OS::TripleO::Services::DockerRegistry
    - OS::TripleO::Services::Etcd
    - OS::TripleO::Services::HAProxyInternalTLS
    - OS::TripleO::Services::HAProxyPublicTLS
    - OS::TripleO::Services::HAproxy
    - OS::TripleO::Services::Keepalived
    - OS::TripleO::Services::Kernel
    - OS::TripleO::Services::Keystone
    - OS::TripleO::Services::Kubernetes::Master
    - OS::TripleO::Services::Kubernetes::Worker
    - OS::TripleO::Services::LoginDefs
    - OS::TripleO::Services::MasqueradeNetworks
    - OS::TripleO::Services::Memcached
    - OS::TripleO::Services::MySQL
    - OS::TripleO::Services::MySQLClient
    - OS::TripleO::Services::Ntp
    - OS::TripleO::Services::OpenShift::GlusterFS
    - OS::TripleO::Services::OpenShift::Master
    - OS::TripleO::Services::OpenShift::Worker
    - OS::TripleO::Services::OsloMessagingNotify
    - OS::TripleO::Services::OsloMessagingRpc
    - OS::TripleO::Services::Pacemaker
    - OS::TripleO::Services::Redis
    - OS::TripleO::Services::Rhsm
    - OS::TripleO::Services::RsyslogSidecar
    - OS::TripleO::Services::Securetty
    - OS::TripleO::Services::Snmp
    - OS::TripleO::Services::Sshd
    - OS::TripleO::Services::TLSProxyBase
    - OS::TripleO::Services::Tempest
    - OS::TripleO::Services::Timezone
    - OS::TripleO::Services::TripleoFirewall
    - OS::TripleO::Services::TripleoPackages
    - OS::TripleO::Services::Tuned
