language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
  - pypy
  - pypy3.3-5.2-alpha1

install:
  - travis_retry pip install tox-travis

script:
  - travis_retry tox
