
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "142db7f964ec6dc0f1d2ef53ffe75981518357b2",
 "version": "0.18.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
