# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Nov 23 23:41:46 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(698, 691)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.listWidget_typelist = QtGui.QListWidget(self.centralwidget)
        self.listWidget_typelist.setGeometry(QtCore.QRect(10, 70, 151, 161))
        self.listWidget_typelist.setObjectName(_fromUtf8("listWidget_typelist"))
        self.listWidget_sectnamelist = QtGui.QListWidget(self.centralwidget)
        self.listWidget_sectnamelist.setGeometry(QtCore.QRect(180, 70, 161, 161))
        self.listWidget_sectnamelist.setObjectName(_fromUtf8("listWidget_sectnamelist"))
        self.graphicsView_sectionshape = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_sectionshape.setGeometry(QtCore.QRect(10, 430, 331, 181))
        self.graphicsView_sectionshape.setObjectName(_fromUtf8("graphicsView_sectionshape"))
        self.pushButton_FIND = QtGui.QPushButton(self.centralwidget)
        self.pushButton_FIND.setGeometry(QtCore.QRect(370, 590, 321, 20))
        self.pushButton_FIND.setObjectName(_fromUtf8("pushButton_FIND"))
        self.pushButton_loadparamas = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loadparamas.setGeometry(QtCore.QRect(590, 50, 91, 23))
        self.pushButton_loadparamas.setObjectName(_fromUtf8("pushButton_loadparamas"))
        self.label_29 = QtGui.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(20, 10, 56, 23))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_basename = QtGui.QLabel(self.centralwidget)
        self.label_basename.setGeometry(QtCore.QRect(90, 10, 251, 23))
        self.label_basename.setObjectName(_fromUtf8("label_basename"))
        self.label_33 = QtGui.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(370, 20, 91, 23))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(510, 90, 51, 23))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.lineEdit_loadparamas = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_loadparamas.setEnabled(True)
        self.lineEdit_loadparamas.setGeometry(QtCore.QRect(500, 50, 81, 20))
        self.lineEdit_loadparamas.setObjectName(_fromUtf8("lineEdit_loadparamas"))
        self.pushButton_loadsecnameaslected = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loadsecnameaslected.setGeometry(QtCore.QRect(470, 50, 21, 23))
        self.pushButton_loadsecnameaslected.setObjectName(_fromUtf8("pushButton_loadsecnameaslected"))
        self.textBrowser_sectprep = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser_sectprep.setGeometry(QtCore.QRect(10, 240, 331, 151))
        self.textBrowser_sectprep.setObjectName(_fromUtf8("textBrowser_sectprep"))
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(370, 70, 321, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_47 = QtGui.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(370, 350, 56, 23))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.label_currentselected = QtGui.QLabel(self.centralwidget)
        self.label_currentselected.setGeometry(QtCore.QRect(370, 50, 81, 23))
        self.label_currentselected.setObjectName(_fromUtf8("label_currentselected"))
        self.label_info = QtGui.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(10, 630, 671, 20))
        self.label_info.setObjectName(_fromUtf8("label_info"))
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(10, 620, 681, 20))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.label_39 = QtGui.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(610, 90, 71, 23))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_50 = QtGui.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(370, 90, 111, 23))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.label_40 = QtGui.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(590, 390, 91, 23))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(360, 120, 331, 204))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBox_Iz_deltan = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_Iz_deltan.setEnabled(False)
        self.comboBox_Iz_deltan.setMaximumSize(QtCore.QSize(61, 16777215))
        self.comboBox_Iz_deltan.setObjectName(_fromUtf8("comboBox_Iz_deltan"))
        self.comboBox_Iz_deltan.addItem(_fromUtf8(""))
        self.comboBox_Iz_deltan.addItem(_fromUtf8(""))
        self.comboBox_Iz_deltan.addItem(_fromUtf8(""))
        self.comboBox_Iz_deltan.addItem(_fromUtf8(""))
        self.comboBox_Iz_deltan.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_Iz_deltan, 5, 4, 1, 1)
        self.lineEdit_req_b = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_req_b.setEnabled(False)
        self.lineEdit_req_b.setObjectName(_fromUtf8("lineEdit_req_b"))
        self.gridLayout.addWidget(self.lineEdit_req_b, 1, 3, 1, 1)
        self.label_31 = QtGui.QLabel(self.layoutWidget)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout.addWidget(self.label_31, 0, 0, 1, 1)
        self.lineEdit_req_h = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_req_h.setEnabled(False)
        self.lineEdit_req_h.setObjectName(_fromUtf8("lineEdit_req_h"))
        self.gridLayout.addWidget(self.lineEdit_req_h, 0, 3, 1, 1)
        self.comboBox_b_deltan = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_b_deltan.setEnabled(False)
        self.comboBox_b_deltan.setMaximumSize(QtCore.QSize(61, 16777215))
        self.comboBox_b_deltan.setObjectName(_fromUtf8("comboBox_b_deltan"))
        self.comboBox_b_deltan.addItem(_fromUtf8(""))
        self.comboBox_b_deltan.addItem(_fromUtf8(""))
        self.comboBox_b_deltan.addItem(_fromUtf8(""))
        self.comboBox_b_deltan.addItem(_fromUtf8(""))
        self.comboBox_b_deltan.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_b_deltan, 1, 4, 1, 1)
        self.comboBox_b_deltap = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_b_deltap.setEnabled(False)
        self.comboBox_b_deltap.setMaximumSize(QtCore.QSize(71, 16777215))
        self.comboBox_b_deltap.setObjectName(_fromUtf8("comboBox_b_deltap"))
        self.comboBox_b_deltap.addItem(_fromUtf8(""))
        self.comboBox_b_deltap.addItem(_fromUtf8(""))
        self.comboBox_b_deltap.addItem(_fromUtf8(""))
        self.comboBox_b_deltap.addItem(_fromUtf8(""))
        self.comboBox_b_deltap.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_b_deltap, 1, 5, 1, 1)
        self.label_is_mass = QtGui.QLabel(self.layoutWidget)
        self.label_is_mass.setObjectName(_fromUtf8("label_is_mass"))
        self.gridLayout.addWidget(self.label_is_mass, 2, 1, 1, 1)
        self.label_is_Ax = QtGui.QLabel(self.layoutWidget)
        self.label_is_Ax.setObjectName(_fromUtf8("label_is_Ax"))
        self.gridLayout.addWidget(self.label_is_Ax, 3, 1, 1, 1)
        self.comboBox_h_deltap = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_h_deltap.setEnabled(False)
        self.comboBox_h_deltap.setMaximumSize(QtCore.QSize(71, 16777215))
        self.comboBox_h_deltap.setObjectName(_fromUtf8("comboBox_h_deltap"))
        self.comboBox_h_deltap.addItem(_fromUtf8(""))
        self.comboBox_h_deltap.addItem(_fromUtf8(""))
        self.comboBox_h_deltap.addItem(_fromUtf8(""))
        self.comboBox_h_deltap.addItem(_fromUtf8(""))
        self.comboBox_h_deltap.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_h_deltap, 0, 5, 1, 1)
        self.label_is_b = QtGui.QLabel(self.layoutWidget)
        self.label_is_b.setObjectName(_fromUtf8("label_is_b"))
        self.gridLayout.addWidget(self.label_is_b, 1, 1, 1, 1)
        self.comboBox_h_deltan = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_h_deltan.setEnabled(False)
        self.comboBox_h_deltan.setMaximumSize(QtCore.QSize(61, 16777215))
        self.comboBox_h_deltan.setObjectName(_fromUtf8("comboBox_h_deltan"))
        self.comboBox_h_deltan.addItem(_fromUtf8(""))
        self.comboBox_h_deltan.addItem(_fromUtf8(""))
        self.comboBox_h_deltan.addItem(_fromUtf8(""))
        self.comboBox_h_deltan.addItem(_fromUtf8(""))
        self.comboBox_h_deltan.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_h_deltan, 0, 4, 1, 1)
        self.comboBox_mass_deltan = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_mass_deltan.setEnabled(False)
        self.comboBox_mass_deltan.setMaximumSize(QtCore.QSize(61, 16777215))
        self.comboBox_mass_deltan.setObjectName(_fromUtf8("comboBox_mass_deltan"))
        self.comboBox_mass_deltan.addItem(_fromUtf8(""))
        self.comboBox_mass_deltan.addItem(_fromUtf8(""))
        self.comboBox_mass_deltan.addItem(_fromUtf8(""))
        self.comboBox_mass_deltan.addItem(_fromUtf8(""))
        self.comboBox_mass_deltan.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_mass_deltan, 2, 4, 1, 1)
        self.lineEdit_req_mass = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_req_mass.setEnabled(False)
        self.lineEdit_req_mass.setObjectName(_fromUtf8("lineEdit_req_mass"))
        self.gridLayout.addWidget(self.lineEdit_req_mass, 2, 3, 1, 1)
        self.label_52 = QtGui.QLabel(self.layoutWidget)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout.addWidget(self.label_52, 3, 0, 1, 1)
        self.comboBox_mass_deltap = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_mass_deltap.setEnabled(False)
        self.comboBox_mass_deltap.setMaximumSize(QtCore.QSize(71, 16777215))
        self.comboBox_mass_deltap.setObjectName(_fromUtf8("comboBox_mass_deltap"))
        self.comboBox_mass_deltap.addItem(_fromUtf8(""))
        self.comboBox_mass_deltap.addItem(_fromUtf8(""))
        self.comboBox_mass_deltap.addItem(_fromUtf8(""))
        self.comboBox_mass_deltap.addItem(_fromUtf8(""))
        self.comboBox_mass_deltap.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_mass_deltap, 2, 5, 1, 1)
        self.label_35 = QtGui.QLabel(self.layoutWidget)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout.addWidget(self.label_35, 1, 0, 1, 1)
        self.label_is_Iz = QtGui.QLabel(self.layoutWidget)
        self.label_is_Iz.setObjectName(_fromUtf8("label_is_Iz"))
        self.gridLayout.addWidget(self.label_is_Iz, 5, 1, 1, 1)
        self.comboBox_Wz_deltan = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_Wz_deltan.setEnabled(False)
        self.comboBox_Wz_deltan.setMaximumSize(QtCore.QSize(61, 16777215))
        self.comboBox_Wz_deltan.setObjectName(_fromUtf8("comboBox_Wz_deltan"))
        self.comboBox_Wz_deltan.addItem(_fromUtf8(""))
        self.comboBox_Wz_deltan.addItem(_fromUtf8(""))
        self.comboBox_Wz_deltan.addItem(_fromUtf8(""))
        self.comboBox_Wz_deltan.addItem(_fromUtf8(""))
        self.comboBox_Wz_deltan.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_Wz_deltan, 7, 4, 1, 1)
        self.comboBox_Wz_deltap = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_Wz_deltap.setEnabled(False)
        self.comboBox_Wz_deltap.setMaximumSize(QtCore.QSize(71, 16777215))
        self.comboBox_Wz_deltap.setObjectName(_fromUtf8("comboBox_Wz_deltap"))
        self.comboBox_Wz_deltap.addItem(_fromUtf8(""))
        self.comboBox_Wz_deltap.addItem(_fromUtf8(""))
        self.comboBox_Wz_deltap.addItem(_fromUtf8(""))
        self.comboBox_Wz_deltap.addItem(_fromUtf8(""))
        self.comboBox_Wz_deltap.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_Wz_deltap, 7, 5, 1, 1)
        self.comboBox_Iy_deltan = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_Iy_deltan.setEnabled(False)
        self.comboBox_Iy_deltan.setMaximumSize(QtCore.QSize(61, 16777215))
        self.comboBox_Iy_deltan.setObjectName(_fromUtf8("comboBox_Iy_deltan"))
        self.comboBox_Iy_deltan.addItem(_fromUtf8(""))
        self.comboBox_Iy_deltan.addItem(_fromUtf8(""))
        self.comboBox_Iy_deltan.addItem(_fromUtf8(""))
        self.comboBox_Iy_deltan.addItem(_fromUtf8(""))
        self.comboBox_Iy_deltan.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_Iy_deltan, 4, 4, 1, 1)
        self.label_is_Wz = QtGui.QLabel(self.layoutWidget)
        self.label_is_Wz.setObjectName(_fromUtf8("label_is_Wz"))
        self.gridLayout.addWidget(self.label_is_Wz, 7, 1, 1, 1)
        self.lineEdit_req_Wz = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_req_Wz.setEnabled(False)
        self.lineEdit_req_Wz.setObjectName(_fromUtf8("lineEdit_req_Wz"))
        self.gridLayout.addWidget(self.lineEdit_req_Wz, 7, 3, 1, 1)
        self.label_42 = QtGui.QLabel(self.layoutWidget)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout.addWidget(self.label_42, 7, 0, 1, 1)
        self.comboBox_Wy_deltap = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_Wy_deltap.setEnabled(False)
        self.comboBox_Wy_deltap.setMaximumSize(QtCore.QSize(71, 16777215))
        self.comboBox_Wy_deltap.setObjectName(_fromUtf8("comboBox_Wy_deltap"))
        self.comboBox_Wy_deltap.addItem(_fromUtf8(""))
        self.comboBox_Wy_deltap.addItem(_fromUtf8(""))
        self.comboBox_Wy_deltap.addItem(_fromUtf8(""))
        self.comboBox_Wy_deltap.addItem(_fromUtf8(""))
        self.comboBox_Wy_deltap.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_Wy_deltap, 6, 5, 1, 1)
        self.comboBox_Wy_deltan = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_Wy_deltan.setEnabled(False)
        self.comboBox_Wy_deltan.setMaximumSize(QtCore.QSize(61, 16777215))
        self.comboBox_Wy_deltan.setObjectName(_fromUtf8("comboBox_Wy_deltan"))
        self.comboBox_Wy_deltan.addItem(_fromUtf8(""))
        self.comboBox_Wy_deltan.addItem(_fromUtf8(""))
        self.comboBox_Wy_deltan.addItem(_fromUtf8(""))
        self.comboBox_Wy_deltan.addItem(_fromUtf8(""))
        self.comboBox_Wy_deltan.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_Wy_deltan, 6, 4, 1, 1)
        self.lineEdit_req_Wy = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_req_Wy.setEnabled(False)
        self.lineEdit_req_Wy.setObjectName(_fromUtf8("lineEdit_req_Wy"))
        self.gridLayout.addWidget(self.lineEdit_req_Wy, 6, 3, 1, 1)
        self.label_is_Wy = QtGui.QLabel(self.layoutWidget)
        self.label_is_Wy.setObjectName(_fromUtf8("label_is_Wy"))
        self.gridLayout.addWidget(self.label_is_Wy, 6, 1, 1, 1)
        self.label_41 = QtGui.QLabel(self.layoutWidget)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout.addWidget(self.label_41, 6, 0, 1, 1)
        self.comboBox_Iz_deltap = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_Iz_deltap.setEnabled(False)
        self.comboBox_Iz_deltap.setMaximumSize(QtCore.QSize(71, 16777215))
        self.comboBox_Iz_deltap.setObjectName(_fromUtf8("comboBox_Iz_deltap"))
        self.comboBox_Iz_deltap.addItem(_fromUtf8(""))
        self.comboBox_Iz_deltap.addItem(_fromUtf8(""))
        self.comboBox_Iz_deltap.addItem(_fromUtf8(""))
        self.comboBox_Iz_deltap.addItem(_fromUtf8(""))
        self.comboBox_Iz_deltap.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_Iz_deltap, 5, 5, 1, 1)
        self.label_is_h = QtGui.QLabel(self.layoutWidget)
        self.label_is_h.setObjectName(_fromUtf8("label_is_h"))
        self.gridLayout.addWidget(self.label_is_h, 0, 1, 1, 1)
        self.label_51 = QtGui.QLabel(self.layoutWidget)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout.addWidget(self.label_51, 2, 0, 1, 1)
        self.lineEdit_req_Iz = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_req_Iz.setEnabled(False)
        self.lineEdit_req_Iz.setObjectName(_fromUtf8("lineEdit_req_Iz"))
        self.gridLayout.addWidget(self.lineEdit_req_Iz, 5, 3, 1, 1)
        self.lineEdit_req_Ax = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_req_Ax.setEnabled(False)
        self.lineEdit_req_Ax.setObjectName(_fromUtf8("lineEdit_req_Ax"))
        self.gridLayout.addWidget(self.lineEdit_req_Ax, 3, 3, 1, 1)
        self.lineEdit_req_Iy = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_req_Iy.setEnabled(False)
        self.lineEdit_req_Iy.setObjectName(_fromUtf8("lineEdit_req_Iy"))
        self.gridLayout.addWidget(self.lineEdit_req_Iy, 4, 3, 1, 1)
        self.comboBox_Ax_deltap = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_Ax_deltap.setEnabled(False)
        self.comboBox_Ax_deltap.setMaximumSize(QtCore.QSize(71, 16777215))
        self.comboBox_Ax_deltap.setObjectName(_fromUtf8("comboBox_Ax_deltap"))
        self.comboBox_Ax_deltap.addItem(_fromUtf8(""))
        self.comboBox_Ax_deltap.addItem(_fromUtf8(""))
        self.comboBox_Ax_deltap.addItem(_fromUtf8(""))
        self.comboBox_Ax_deltap.addItem(_fromUtf8(""))
        self.comboBox_Ax_deltap.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_Ax_deltap, 3, 5, 1, 1)
        self.label_is_Iy = QtGui.QLabel(self.layoutWidget)
        self.label_is_Iy.setObjectName(_fromUtf8("label_is_Iy"))
        self.gridLayout.addWidget(self.label_is_Iy, 4, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.layoutWidget)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout.addWidget(self.label_38, 4, 0, 1, 1)
        self.comboBox_Ax_deltan = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_Ax_deltan.setEnabled(False)
        self.comboBox_Ax_deltan.setMaximumSize(QtCore.QSize(61, 16777215))
        self.comboBox_Ax_deltan.setObjectName(_fromUtf8("comboBox_Ax_deltan"))
        self.comboBox_Ax_deltan.addItem(_fromUtf8(""))
        self.comboBox_Ax_deltan.addItem(_fromUtf8(""))
        self.comboBox_Ax_deltan.addItem(_fromUtf8(""))
        self.comboBox_Ax_deltan.addItem(_fromUtf8(""))
        self.comboBox_Ax_deltan.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_Ax_deltan, 3, 4, 1, 1)
        self.label_36 = QtGui.QLabel(self.layoutWidget)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout.addWidget(self.label_36, 5, 0, 1, 1)
        self.comboBox_Iy_deltap = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_Iy_deltap.setEnabled(False)
        self.comboBox_Iy_deltap.setMaximumSize(QtCore.QSize(71, 16777215))
        self.comboBox_Iy_deltap.setObjectName(_fromUtf8("comboBox_Iy_deltap"))
        self.comboBox_Iy_deltap.addItem(_fromUtf8(""))
        self.comboBox_Iy_deltap.addItem(_fromUtf8(""))
        self.comboBox_Iy_deltap.addItem(_fromUtf8(""))
        self.comboBox_Iy_deltap.addItem(_fromUtf8(""))
        self.comboBox_Iy_deltap.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_Iy_deltap, 4, 5, 1, 1)
        self.checkBox_h = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_h.setText(_fromUtf8(""))
        self.checkBox_h.setObjectName(_fromUtf8("checkBox_h"))
        self.gridLayout.addWidget(self.checkBox_h, 0, 2, 1, 1)
        self.checkBox_b = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_b.setText(_fromUtf8(""))
        self.checkBox_b.setObjectName(_fromUtf8("checkBox_b"))
        self.gridLayout.addWidget(self.checkBox_b, 1, 2, 1, 1)
        self.checkBox_Wz = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_Wz.setText(_fromUtf8(""))
        self.checkBox_Wz.setObjectName(_fromUtf8("checkBox_Wz"))
        self.gridLayout.addWidget(self.checkBox_Wz, 7, 2, 1, 1)
        self.checkBox_Wy = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_Wy.setText(_fromUtf8(""))
        self.checkBox_Wy.setObjectName(_fromUtf8("checkBox_Wy"))
        self.gridLayout.addWidget(self.checkBox_Wy, 6, 2, 1, 1)
        self.checkBox_Iz = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_Iz.setText(_fromUtf8(""))
        self.checkBox_Iz.setObjectName(_fromUtf8("checkBox_Iz"))
        self.gridLayout.addWidget(self.checkBox_Iz, 5, 2, 1, 1)
        self.checkBox_Iy = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_Iy.setText(_fromUtf8(""))
        self.checkBox_Iy.setObjectName(_fromUtf8("checkBox_Iy"))
        self.gridLayout.addWidget(self.checkBox_Iy, 4, 2, 1, 1)
        self.checkBox_Ax = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_Ax.setText(_fromUtf8(""))
        self.checkBox_Ax.setObjectName(_fromUtf8("checkBox_Ax"))
        self.gridLayout.addWidget(self.checkBox_Ax, 3, 2, 1, 1)
        self.checkBox_mass = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_mass.setText(_fromUtf8(""))
        self.checkBox_mass.setObjectName(_fromUtf8("checkBox_mass"))
        self.gridLayout.addWidget(self.checkBox_mass, 2, 2, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(360, 420, 331, 126))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_is_Vrdz = QtGui.QLabel(self.layoutWidget1)
        self.label_is_Vrdz.setObjectName(_fromUtf8("label_is_Vrdz"))
        self.gridLayout_2.addWidget(self.label_is_Vrdz, 4, 1, 1, 1)
        self.comboBox_Vrdy_deltan = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_Vrdy_deltan.setEnabled(False)
        self.comboBox_Vrdy_deltan.setMaximumSize(QtCore.QSize(61, 16777215))
        self.comboBox_Vrdy_deltan.setObjectName(_fromUtf8("comboBox_Vrdy_deltan"))
        self.comboBox_Vrdy_deltan.addItem(_fromUtf8(""))
        self.comboBox_Vrdy_deltan.addItem(_fromUtf8(""))
        self.comboBox_Vrdy_deltan.addItem(_fromUtf8(""))
        self.comboBox_Vrdy_deltan.addItem(_fromUtf8(""))
        self.comboBox_Vrdy_deltan.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_Vrdy_deltan, 3, 4, 1, 1)
        self.comboBox_Nrd_deltan = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_Nrd_deltan.setEnabled(False)
        self.comboBox_Nrd_deltan.setMaximumSize(QtCore.QSize(61, 16777215))
        self.comboBox_Nrd_deltan.setObjectName(_fromUtf8("comboBox_Nrd_deltan"))
        self.comboBox_Nrd_deltan.addItem(_fromUtf8(""))
        self.comboBox_Nrd_deltan.addItem(_fromUtf8(""))
        self.comboBox_Nrd_deltan.addItem(_fromUtf8(""))
        self.comboBox_Nrd_deltan.addItem(_fromUtf8(""))
        self.comboBox_Nrd_deltan.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_Nrd_deltan, 0, 4, 1, 1)
        self.comboBox_Mrdz_deltap = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_Mrdz_deltap.setEnabled(False)
        self.comboBox_Mrdz_deltap.setMaximumSize(QtCore.QSize(71, 16777215))
        self.comboBox_Mrdz_deltap.setObjectName(_fromUtf8("comboBox_Mrdz_deltap"))
        self.comboBox_Mrdz_deltap.addItem(_fromUtf8(""))
        self.comboBox_Mrdz_deltap.addItem(_fromUtf8(""))
        self.comboBox_Mrdz_deltap.addItem(_fromUtf8(""))
        self.comboBox_Mrdz_deltap.addItem(_fromUtf8(""))
        self.comboBox_Mrdz_deltap.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_Mrdz_deltap, 2, 5, 1, 1)
        self.lineEdit_req_Vrdz = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_req_Vrdz.setEnabled(False)
        self.lineEdit_req_Vrdz.setObjectName(_fromUtf8("lineEdit_req_Vrdz"))
        self.gridLayout_2.addWidget(self.lineEdit_req_Vrdz, 4, 3, 1, 1)
        self.comboBox_Mrdz_deltan = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_Mrdz_deltan.setEnabled(False)
        self.comboBox_Mrdz_deltan.setMaximumSize(QtCore.QSize(61, 16777215))
        self.comboBox_Mrdz_deltan.setObjectName(_fromUtf8("comboBox_Mrdz_deltan"))
        self.comboBox_Mrdz_deltan.addItem(_fromUtf8(""))
        self.comboBox_Mrdz_deltan.addItem(_fromUtf8(""))
        self.comboBox_Mrdz_deltan.addItem(_fromUtf8(""))
        self.comboBox_Mrdz_deltan.addItem(_fromUtf8(""))
        self.comboBox_Mrdz_deltan.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_Mrdz_deltan, 2, 4, 1, 1)
        self.comboBox_Mrdy_deltap = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_Mrdy_deltap.setEnabled(False)
        self.comboBox_Mrdy_deltap.setMaximumSize(QtCore.QSize(71, 16777215))
        self.comboBox_Mrdy_deltap.setObjectName(_fromUtf8("comboBox_Mrdy_deltap"))
        self.comboBox_Mrdy_deltap.addItem(_fromUtf8(""))
        self.comboBox_Mrdy_deltap.addItem(_fromUtf8(""))
        self.comboBox_Mrdy_deltap.addItem(_fromUtf8(""))
        self.comboBox_Mrdy_deltap.addItem(_fromUtf8(""))
        self.comboBox_Mrdy_deltap.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_Mrdy_deltap, 1, 5, 1, 1)
        self.label_is_Vrdy = QtGui.QLabel(self.layoutWidget1)
        self.label_is_Vrdy.setObjectName(_fromUtf8("label_is_Vrdy"))
        self.gridLayout_2.addWidget(self.label_is_Vrdy, 3, 1, 1, 1)
        self.lineEdit_req_Vrdy = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_req_Vrdy.setEnabled(False)
        self.lineEdit_req_Vrdy.setObjectName(_fromUtf8("lineEdit_req_Vrdy"))
        self.gridLayout_2.addWidget(self.lineEdit_req_Vrdy, 3, 3, 1, 1)
        self.label_46 = QtGui.QLabel(self.layoutWidget1)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_2.addWidget(self.label_46, 3, 0, 1, 1)
        self.label_is_Mrdz = QtGui.QLabel(self.layoutWidget1)
        self.label_is_Mrdz.setObjectName(_fromUtf8("label_is_Mrdz"))
        self.gridLayout_2.addWidget(self.label_is_Mrdz, 2, 1, 1, 1)
        self.label_48 = QtGui.QLabel(self.layoutWidget1)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_2.addWidget(self.label_48, 2, 0, 1, 1)
        self.lineEdit_req_Mrdz = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_req_Mrdz.setEnabled(False)
        self.lineEdit_req_Mrdz.setObjectName(_fromUtf8("lineEdit_req_Mrdz"))
        self.gridLayout_2.addWidget(self.lineEdit_req_Mrdz, 2, 3, 1, 1)
        self.comboBox_Mrdy_deltan = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_Mrdy_deltan.setEnabled(False)
        self.comboBox_Mrdy_deltan.setMaximumSize(QtCore.QSize(61, 16777215))
        self.comboBox_Mrdy_deltan.setObjectName(_fromUtf8("comboBox_Mrdy_deltan"))
        self.comboBox_Mrdy_deltan.addItem(_fromUtf8(""))
        self.comboBox_Mrdy_deltan.addItem(_fromUtf8(""))
        self.comboBox_Mrdy_deltan.addItem(_fromUtf8(""))
        self.comboBox_Mrdy_deltan.addItem(_fromUtf8(""))
        self.comboBox_Mrdy_deltan.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_Mrdy_deltan, 1, 4, 1, 1)
        self.lineEdit_req_Nrd = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_req_Nrd.setEnabled(False)
        self.lineEdit_req_Nrd.setObjectName(_fromUtf8("lineEdit_req_Nrd"))
        self.gridLayout_2.addWidget(self.lineEdit_req_Nrd, 0, 3, 1, 1)
        self.label_44 = QtGui.QLabel(self.layoutWidget1)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_2.addWidget(self.label_44, 0, 0, 1, 1)
        self.label_is_Nrd = QtGui.QLabel(self.layoutWidget1)
        self.label_is_Nrd.setObjectName(_fromUtf8("label_is_Nrd"))
        self.gridLayout_2.addWidget(self.label_is_Nrd, 0, 1, 1, 1)
        self.lineEdit_req_Mrdy = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_req_Mrdy.setEnabled(False)
        self.lineEdit_req_Mrdy.setObjectName(_fromUtf8("lineEdit_req_Mrdy"))
        self.gridLayout_2.addWidget(self.lineEdit_req_Mrdy, 1, 3, 1, 1)
        self.comboBox_Nrd_deltap = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_Nrd_deltap.setEnabled(False)
        self.comboBox_Nrd_deltap.setMaximumSize(QtCore.QSize(71, 16777215))
        self.comboBox_Nrd_deltap.setObjectName(_fromUtf8("comboBox_Nrd_deltap"))
        self.comboBox_Nrd_deltap.addItem(_fromUtf8(""))
        self.comboBox_Nrd_deltap.addItem(_fromUtf8(""))
        self.comboBox_Nrd_deltap.addItem(_fromUtf8(""))
        self.comboBox_Nrd_deltap.addItem(_fromUtf8(""))
        self.comboBox_Nrd_deltap.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_Nrd_deltap, 0, 5, 1, 1)
        self.label_is_Mrdy = QtGui.QLabel(self.layoutWidget1)
        self.label_is_Mrdy.setObjectName(_fromUtf8("label_is_Mrdy"))
        self.gridLayout_2.addWidget(self.label_is_Mrdy, 1, 1, 1, 1)
        self.label_45 = QtGui.QLabel(self.layoutWidget1)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_2.addWidget(self.label_45, 1, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.layoutWidget1)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_2.addWidget(self.label_49, 4, 0, 1, 1)
        self.comboBox_Vrdz_deltan = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_Vrdz_deltan.setEnabled(False)
        self.comboBox_Vrdz_deltan.setMaximumSize(QtCore.QSize(61, 16777215))
        self.comboBox_Vrdz_deltan.setObjectName(_fromUtf8("comboBox_Vrdz_deltan"))
        self.comboBox_Vrdz_deltan.addItem(_fromUtf8(""))
        self.comboBox_Vrdz_deltan.addItem(_fromUtf8(""))
        self.comboBox_Vrdz_deltan.addItem(_fromUtf8(""))
        self.comboBox_Vrdz_deltan.addItem(_fromUtf8(""))
        self.comboBox_Vrdz_deltan.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_Vrdz_deltan, 4, 4, 1, 1)
        self.comboBox_Vrdy_deltap = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_Vrdy_deltap.setEnabled(False)
        self.comboBox_Vrdy_deltap.setMaximumSize(QtCore.QSize(71, 16777215))
        self.comboBox_Vrdy_deltap.setObjectName(_fromUtf8("comboBox_Vrdy_deltap"))
        self.comboBox_Vrdy_deltap.addItem(_fromUtf8(""))
        self.comboBox_Vrdy_deltap.addItem(_fromUtf8(""))
        self.comboBox_Vrdy_deltap.addItem(_fromUtf8(""))
        self.comboBox_Vrdy_deltap.addItem(_fromUtf8(""))
        self.comboBox_Vrdy_deltap.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_Vrdy_deltap, 3, 5, 1, 1)
        self.comboBox_Vrdz_deltap = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_Vrdz_deltap.setEnabled(False)
        self.comboBox_Vrdz_deltap.setMaximumSize(QtCore.QSize(71, 16777215))
        self.comboBox_Vrdz_deltap.setObjectName(_fromUtf8("comboBox_Vrdz_deltap"))
        self.comboBox_Vrdz_deltap.addItem(_fromUtf8(""))
        self.comboBox_Vrdz_deltap.addItem(_fromUtf8(""))
        self.comboBox_Vrdz_deltap.addItem(_fromUtf8(""))
        self.comboBox_Vrdz_deltap.addItem(_fromUtf8(""))
        self.comboBox_Vrdz_deltap.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_Vrdz_deltap, 4, 5, 1, 1)
        self.checkBox_Nrd = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_Nrd.setText(_fromUtf8(""))
        self.checkBox_Nrd.setObjectName(_fromUtf8("checkBox_Nrd"))
        self.gridLayout_2.addWidget(self.checkBox_Nrd, 0, 2, 1, 1)
        self.checkBox_Mrdy = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_Mrdy.setText(_fromUtf8(""))
        self.checkBox_Mrdy.setObjectName(_fromUtf8("checkBox_Mrdy"))
        self.gridLayout_2.addWidget(self.checkBox_Mrdy, 1, 2, 1, 1)
        self.checkBox_Mrdz = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_Mrdz.setText(_fromUtf8(""))
        self.checkBox_Mrdz.setObjectName(_fromUtf8("checkBox_Mrdz"))
        self.gridLayout_2.addWidget(self.checkBox_Mrdz, 2, 2, 1, 1)
        self.checkBox_Vrdy = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_Vrdy.setText(_fromUtf8(""))
        self.checkBox_Vrdy.setObjectName(_fromUtf8("checkBox_Vrdy"))
        self.gridLayout_2.addWidget(self.checkBox_Vrdy, 3, 2, 1, 1)
        self.checkBox_Vrdz = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_Vrdz.setText(_fromUtf8(""))
        self.checkBox_Vrdz.setObjectName(_fromUtf8("checkBox_Vrdz"))
        self.gridLayout_2.addWidget(self.checkBox_Vrdz, 4, 2, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(430, 360, 145, 52))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_27 = QtGui.QLabel(self.layoutWidget2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_2.addWidget(self.label_27)
        self.comboBox_SteelGrade = QtGui.QComboBox(self.layoutWidget2)
        self.comboBox_SteelGrade.setObjectName(_fromUtf8("comboBox_SteelGrade"))
        self.horizontalLayout_2.addWidget(self.comboBox_SteelGrade)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_28 = QtGui.QLabel(self.layoutWidget2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout.addWidget(self.label_28)
        self.comboBox_instalility = QtGui.QComboBox(self.layoutWidget2)
        self.comboBox_instalility.setObjectName(_fromUtf8("comboBox_instalility"))
        self.comboBox_instalility.addItem(_fromUtf8(""))
        self.comboBox_instalility.addItem(_fromUtf8(""))
        self.comboBox_instalility.addItem(_fromUtf8(""))
        self.comboBox_instalility.addItem(_fromUtf8(""))
        self.comboBox_instalility.addItem(_fromUtf8(""))
        self.comboBox_instalility.addItem(_fromUtf8(""))
        self.comboBox_instalility.addItem(_fromUtf8(""))
        self.comboBox_instalility.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_instalility)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_zoom_in = QtGui.QPushButton(self.centralwidget)
        self.pushButton_zoom_in.setGeometry(QtCore.QRect(20, 440, 21, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_zoom_in.setPalette(palette)
        self.pushButton_zoom_in.setObjectName(_fromUtf8("pushButton_zoom_in"))
        self.pushButton_zoom_out = QtGui.QPushButton(self.centralwidget)
        self.pushButton_zoom_out.setGeometry(QtCore.QRect(20, 470, 21, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_zoom_out.setPalette(palette)
        self.pushButton_zoom_out.setObjectName(_fromUtf8("pushButton_zoom_out"))
        self.checkBox_PropertiesDescription = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_PropertiesDescription.setGeometry(QtCore.QRect(20, 400, 131, 18))
        self.checkBox_PropertiesDescription.setObjectName(_fromUtf8("checkBox_PropertiesDescription"))
        self.comboBox_sectiongroups = QtGui.QComboBox(self.centralwidget)
        self.comboBox_sectiongroups.setGeometry(QtCore.QRect(10, 40, 331, 20))
        self.comboBox_sectiongroups.setMaxVisibleItems(20)
        self.comboBox_sectiongroups.setObjectName(_fromUtf8("comboBox_sectiongroups"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 698, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuBase = QtGui.QMenu(self.menubar)
        self.menuBase.setObjectName(_fromUtf8("menuBase"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setEnabled(False)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.menuBase.addAction(self.actionLoad)
        self.menubar.addAction(self.menuBase.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBox_Iz_deltan.setCurrentIndex(0)
        self.comboBox_b_deltan.setCurrentIndex(4)
        self.comboBox_b_deltap.setCurrentIndex(0)
        self.comboBox_h_deltap.setCurrentIndex(0)
        self.comboBox_h_deltan.setCurrentIndex(4)
        self.comboBox_mass_deltan.setCurrentIndex(4)
        self.comboBox_mass_deltap.setCurrentIndex(0)
        self.comboBox_Wz_deltan.setCurrentIndex(0)
        self.comboBox_Wz_deltap.setCurrentIndex(4)
        self.comboBox_Iy_deltan.setCurrentIndex(0)
        self.comboBox_Wy_deltap.setCurrentIndex(4)
        self.comboBox_Wy_deltan.setCurrentIndex(0)
        self.comboBox_Iz_deltap.setCurrentIndex(4)
        self.comboBox_Ax_deltap.setCurrentIndex(4)
        self.comboBox_Ax_deltan.setCurrentIndex(0)
        self.comboBox_Iy_deltap.setCurrentIndex(4)
        self.comboBox_Vrdy_deltan.setCurrentIndex(0)
        self.comboBox_Nrd_deltan.setCurrentIndex(0)
        self.comboBox_Mrdz_deltap.setCurrentIndex(4)
        self.comboBox_Mrdz_deltan.setCurrentIndex(0)
        self.comboBox_Mrdy_deltap.setCurrentIndex(4)
        self.comboBox_Mrdy_deltan.setCurrentIndex(0)
        self.comboBox_Nrd_deltap.setCurrentIndex(4)
        self.comboBox_Vrdz_deltan.setCurrentIndex(0)
        self.comboBox_Vrdy_deltap.setCurrentIndex(4)
        self.comboBox_Vrdz_deltap.setCurrentIndex(4)
        self.comboBox_instalility.setCurrentIndex(2)
        QtCore.QObject.connect(self.checkBox_h, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_req_h.setEnabled)
        QtCore.QObject.connect(self.checkBox_h, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_h_deltan.setEnabled)
        QtCore.QObject.connect(self.checkBox_h, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_h_deltap.setEnabled)
        QtCore.QObject.connect(self.checkBox_b, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_req_b.setEnabled)
        QtCore.QObject.connect(self.checkBox_b, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_b_deltan.setEnabled)
        QtCore.QObject.connect(self.checkBox_b, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_b_deltap.setEnabled)
        QtCore.QObject.connect(self.checkBox_mass, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_req_mass.setEnabled)
        QtCore.QObject.connect(self.checkBox_mass, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_mass_deltan.setEnabled)
        QtCore.QObject.connect(self.checkBox_mass, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_mass_deltap.setEnabled)
        QtCore.QObject.connect(self.checkBox_Ax, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_req_Ax.setEnabled)
        QtCore.QObject.connect(self.checkBox_Ax, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Ax_deltan.setEnabled)
        QtCore.QObject.connect(self.checkBox_Ax, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Ax_deltap.setEnabled)
        QtCore.QObject.connect(self.checkBox_Iy, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_req_Iy.setEnabled)
        QtCore.QObject.connect(self.checkBox_Iy, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Iy_deltan.setEnabled)
        QtCore.QObject.connect(self.checkBox_Iy, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Iy_deltap.setEnabled)
        QtCore.QObject.connect(self.checkBox_Iz, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_req_Iz.setEnabled)
        QtCore.QObject.connect(self.checkBox_Iz, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Iz_deltan.setEnabled)
        QtCore.QObject.connect(self.checkBox_Iz, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Iz_deltap.setEnabled)
        QtCore.QObject.connect(self.checkBox_Wy, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_req_Wy.setEnabled)
        QtCore.QObject.connect(self.checkBox_Wy, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Wy_deltan.setEnabled)
        QtCore.QObject.connect(self.checkBox_Wy, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Wy_deltap.setEnabled)
        QtCore.QObject.connect(self.checkBox_Wz, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_req_Wz.setEnabled)
        QtCore.QObject.connect(self.checkBox_Wz, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Wz_deltan.setEnabled)
        QtCore.QObject.connect(self.checkBox_Wz, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Wz_deltap.setEnabled)
        QtCore.QObject.connect(self.checkBox_Nrd, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_req_Nrd.setEnabled)
        QtCore.QObject.connect(self.checkBox_Nrd, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Nrd_deltan.setEnabled)
        QtCore.QObject.connect(self.checkBox_Nrd, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Nrd_deltap.setEnabled)
        QtCore.QObject.connect(self.checkBox_Mrdy, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_req_Mrdy.setEnabled)
        QtCore.QObject.connect(self.checkBox_Mrdy, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Mrdy_deltan.setEnabled)
        QtCore.QObject.connect(self.checkBox_Mrdy, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Mrdy_deltap.setEnabled)
        QtCore.QObject.connect(self.checkBox_Mrdz, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_req_Mrdz.setEnabled)
        QtCore.QObject.connect(self.checkBox_Mrdz, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Mrdz_deltan.setEnabled)
        QtCore.QObject.connect(self.checkBox_Mrdz, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Mrdz_deltap.setEnabled)
        QtCore.QObject.connect(self.checkBox_Vrdy, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_req_Vrdy.setEnabled)
        QtCore.QObject.connect(self.checkBox_Vrdy, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Vrdy_deltan.setEnabled)
        QtCore.QObject.connect(self.checkBox_Vrdy, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Vrdy_deltap.setEnabled)
        QtCore.QObject.connect(self.checkBox_Vrdz, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_req_Vrdz.setEnabled)
        QtCore.QObject.connect(self.checkBox_Vrdz, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Vrdz_deltan.setEnabled)
        QtCore.QObject.connect(self.checkBox_Vrdz, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_Vrdz_deltap.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "STRUTHON.STEEL.SECTIONBROWSER", None))
        self.pushButton_FIND.setText(_translate("MainWindow", "FIND SECTIONS", None))
        self.pushButton_loadparamas.setText(_translate("MainWindow", "load to  required", None))
        self.label_29.setText(_translate("MainWindow", "Base name:", None))
        self.label_basename.setText(_translate("MainWindow", "Base name", None))
        self.label_33.setText(_translate("MainWindow", "Current selected", None))
        self.label_34.setText(_translate("MainWindow", "Required", None))
        self.pushButton_loadsecnameaslected.setText(_translate("MainWindow", " > ", None))
        self.label_47.setText(_translate("MainWindow", "Capacities", None))
        self.label_currentselected.setText(_translate("MainWindow", "--------", None))
        self.label_info.setText(_translate("MainWindow", "StruthonSteelSectionBrowser ver.0.2 ( www.struthon.org)                                                                                 ", None))
        self.label_39.setText(_translate("MainWindow", "-/+ margin [ ]", None))
        self.label_50.setText(_translate("MainWindow", "Properties of selected", None))
        self.label_40.setText(_translate("MainWindow", "-/+ margin [ ]", None))
        self.comboBox_Iz_deltan.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Iz_deltan.setItemText(1, _translate("MainWindow", "-0.1", None))
        self.comboBox_Iz_deltan.setItemText(2, _translate("MainWindow", "-0.2", None))
        self.comboBox_Iz_deltan.setItemText(3, _translate("MainWindow", "-0.5", None))
        self.comboBox_Iz_deltan.setItemText(4, _translate("MainWindow", "-1.0", None))
        self.lineEdit_req_b.setText(_translate("MainWindow", "100", None))
        self.label_31.setText(_translate("MainWindow", "h[cm]=", None))
        self.lineEdit_req_h.setText(_translate("MainWindow", "100", None))
        self.comboBox_b_deltan.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_b_deltan.setItemText(1, _translate("MainWindow", "-0.1", None))
        self.comboBox_b_deltan.setItemText(2, _translate("MainWindow", "-0.2", None))
        self.comboBox_b_deltan.setItemText(3, _translate("MainWindow", "-0.5", None))
        self.comboBox_b_deltan.setItemText(4, _translate("MainWindow", "-1.0", None))
        self.comboBox_b_deltap.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_b_deltap.setItemText(1, _translate("MainWindow", "+0.1", None))
        self.comboBox_b_deltap.setItemText(2, _translate("MainWindow", "+0.2", None))
        self.comboBox_b_deltap.setItemText(3, _translate("MainWindow", "+0.5", None))
        self.comboBox_b_deltap.setItemText(4, _translate("MainWindow", "+inf", None))
        self.label_is_mass.setText(_translate("MainWindow", "------------", None))
        self.label_is_Ax.setText(_translate("MainWindow", "------------", None))
        self.comboBox_h_deltap.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_h_deltap.setItemText(1, _translate("MainWindow", "+0.1", None))
        self.comboBox_h_deltap.setItemText(2, _translate("MainWindow", "+0.2", None))
        self.comboBox_h_deltap.setItemText(3, _translate("MainWindow", "+0.5", None))
        self.comboBox_h_deltap.setItemText(4, _translate("MainWindow", "+inf", None))
        self.label_is_b.setText(_translate("MainWindow", "------------", None))
        self.comboBox_h_deltan.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_h_deltan.setItemText(1, _translate("MainWindow", "-0.1", None))
        self.comboBox_h_deltan.setItemText(2, _translate("MainWindow", "-0.2", None))
        self.comboBox_h_deltan.setItemText(3, _translate("MainWindow", "-0.5", None))
        self.comboBox_h_deltan.setItemText(4, _translate("MainWindow", "-1.0", None))
        self.comboBox_mass_deltan.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_mass_deltan.setItemText(1, _translate("MainWindow", "-0.1", None))
        self.comboBox_mass_deltan.setItemText(2, _translate("MainWindow", "-0.2", None))
        self.comboBox_mass_deltan.setItemText(3, _translate("MainWindow", "-0.5", None))
        self.comboBox_mass_deltan.setItemText(4, _translate("MainWindow", "-1.0", None))
        self.lineEdit_req_mass.setText(_translate("MainWindow", "350", None))
        self.label_52.setText(_translate("MainWindow", "Ax[cm2]=", None))
        self.comboBox_mass_deltap.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_mass_deltap.setItemText(1, _translate("MainWindow", "+0.1", None))
        self.comboBox_mass_deltap.setItemText(2, _translate("MainWindow", "+0.2", None))
        self.comboBox_mass_deltap.setItemText(3, _translate("MainWindow", "+0.5", None))
        self.comboBox_mass_deltap.setItemText(4, _translate("MainWindow", "+inf", None))
        self.label_35.setText(_translate("MainWindow", "b[cm]=", None))
        self.label_is_Iz.setText(_translate("MainWindow", "------------", None))
        self.comboBox_Wz_deltan.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Wz_deltan.setItemText(1, _translate("MainWindow", "-0.1", None))
        self.comboBox_Wz_deltan.setItemText(2, _translate("MainWindow", "-0.2", None))
        self.comboBox_Wz_deltan.setItemText(3, _translate("MainWindow", "-0.5", None))
        self.comboBox_Wz_deltan.setItemText(4, _translate("MainWindow", "-1.0", None))
        self.comboBox_Wz_deltap.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Wz_deltap.setItemText(1, _translate("MainWindow", "+0.1", None))
        self.comboBox_Wz_deltap.setItemText(2, _translate("MainWindow", "+0.2", None))
        self.comboBox_Wz_deltap.setItemText(3, _translate("MainWindow", "+0.5", None))
        self.comboBox_Wz_deltap.setItemText(4, _translate("MainWindow", "+inf", None))
        self.comboBox_Iy_deltan.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Iy_deltan.setItemText(1, _translate("MainWindow", "-0.1", None))
        self.comboBox_Iy_deltan.setItemText(2, _translate("MainWindow", "-0.2", None))
        self.comboBox_Iy_deltan.setItemText(3, _translate("MainWindow", "-0.5", None))
        self.comboBox_Iy_deltan.setItemText(4, _translate("MainWindow", "-1.0", None))
        self.label_is_Wz.setText(_translate("MainWindow", "------------", None))
        self.lineEdit_req_Wz.setText(_translate("MainWindow", "120", None))
        self.label_42.setText(_translate("MainWindow", "Wz[cm3]=", None))
        self.comboBox_Wy_deltap.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Wy_deltap.setItemText(1, _translate("MainWindow", "+0.1", None))
        self.comboBox_Wy_deltap.setItemText(2, _translate("MainWindow", "+0.2", None))
        self.comboBox_Wy_deltap.setItemText(3, _translate("MainWindow", "+0.5", None))
        self.comboBox_Wy_deltap.setItemText(4, _translate("MainWindow", "+inf", None))
        self.comboBox_Wy_deltan.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Wy_deltan.setItemText(1, _translate("MainWindow", "-0.1", None))
        self.comboBox_Wy_deltan.setItemText(2, _translate("MainWindow", "-0.2", None))
        self.comboBox_Wy_deltan.setItemText(3, _translate("MainWindow", "-0.5", None))
        self.comboBox_Wy_deltan.setItemText(4, _translate("MainWindow", "-1.0", None))
        self.lineEdit_req_Wy.setText(_translate("MainWindow", "450", None))
        self.label_is_Wy.setText(_translate("MainWindow", "------------", None))
        self.label_41.setText(_translate("MainWindow", "Wy[cm3]=", None))
        self.comboBox_Iz_deltap.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Iz_deltap.setItemText(1, _translate("MainWindow", "+0.1", None))
        self.comboBox_Iz_deltap.setItemText(2, _translate("MainWindow", "+0.2", None))
        self.comboBox_Iz_deltap.setItemText(3, _translate("MainWindow", "+0.5", None))
        self.comboBox_Iz_deltap.setItemText(4, _translate("MainWindow", "+inf", None))
        self.label_is_h.setText(_translate("MainWindow", "------------", None))
        self.label_51.setText(_translate("MainWindow", "mass[kg/m]=", None))
        self.lineEdit_req_Iz.setText(_translate("MainWindow", "350", None))
        self.lineEdit_req_Ax.setText(_translate("MainWindow", "350", None))
        self.lineEdit_req_Iy.setText(_translate("MainWindow", "350", None))
        self.comboBox_Ax_deltap.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Ax_deltap.setItemText(1, _translate("MainWindow", "+0.1", None))
        self.comboBox_Ax_deltap.setItemText(2, _translate("MainWindow", "+0.2", None))
        self.comboBox_Ax_deltap.setItemText(3, _translate("MainWindow", "+0.5", None))
        self.comboBox_Ax_deltap.setItemText(4, _translate("MainWindow", "+inf", None))
        self.label_is_Iy.setText(_translate("MainWindow", "------------", None))
        self.label_38.setText(_translate("MainWindow", "Iy[cm4]=", None))
        self.comboBox_Ax_deltan.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Ax_deltan.setItemText(1, _translate("MainWindow", "-0.1", None))
        self.comboBox_Ax_deltan.setItemText(2, _translate("MainWindow", "-0.2", None))
        self.comboBox_Ax_deltan.setItemText(3, _translate("MainWindow", "-0.5", None))
        self.comboBox_Ax_deltan.setItemText(4, _translate("MainWindow", "-1.0", None))
        self.label_36.setText(_translate("MainWindow", "Iz[cm4]=", None))
        self.comboBox_Iy_deltap.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Iy_deltap.setItemText(1, _translate("MainWindow", "+0.1", None))
        self.comboBox_Iy_deltap.setItemText(2, _translate("MainWindow", "+0.2", None))
        self.comboBox_Iy_deltap.setItemText(3, _translate("MainWindow", "+0.5", None))
        self.comboBox_Iy_deltap.setItemText(4, _translate("MainWindow", "+inf", None))
        self.label_is_Vrdz.setText(_translate("MainWindow", "------------", None))
        self.comboBox_Vrdy_deltan.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Vrdy_deltan.setItemText(1, _translate("MainWindow", "-0.1", None))
        self.comboBox_Vrdy_deltan.setItemText(2, _translate("MainWindow", "-0.2", None))
        self.comboBox_Vrdy_deltan.setItemText(3, _translate("MainWindow", "-0.5", None))
        self.comboBox_Vrdy_deltan.setItemText(4, _translate("MainWindow", "-1.0", None))
        self.comboBox_Nrd_deltan.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Nrd_deltan.setItemText(1, _translate("MainWindow", "-0.1", None))
        self.comboBox_Nrd_deltan.setItemText(2, _translate("MainWindow", "-0.2", None))
        self.comboBox_Nrd_deltan.setItemText(3, _translate("MainWindow", "-0.5", None))
        self.comboBox_Nrd_deltan.setItemText(4, _translate("MainWindow", "-1.0", None))
        self.comboBox_Mrdz_deltap.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Mrdz_deltap.setItemText(1, _translate("MainWindow", "+0.1", None))
        self.comboBox_Mrdz_deltap.setItemText(2, _translate("MainWindow", "+0.2", None))
        self.comboBox_Mrdz_deltap.setItemText(3, _translate("MainWindow", "+0.5", None))
        self.comboBox_Mrdz_deltap.setItemText(4, _translate("MainWindow", "+inf", None))
        self.lineEdit_req_Vrdz.setText(_translate("MainWindow", "800", None))
        self.comboBox_Mrdz_deltan.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Mrdz_deltan.setItemText(1, _translate("MainWindow", "-0.1", None))
        self.comboBox_Mrdz_deltan.setItemText(2, _translate("MainWindow", "-0.2", None))
        self.comboBox_Mrdz_deltan.setItemText(3, _translate("MainWindow", "-0.5", None))
        self.comboBox_Mrdz_deltan.setItemText(4, _translate("MainWindow", "-1.0", None))
        self.comboBox_Mrdy_deltap.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Mrdy_deltap.setItemText(1, _translate("MainWindow", "+0.1", None))
        self.comboBox_Mrdy_deltap.setItemText(2, _translate("MainWindow", "+0.2", None))
        self.comboBox_Mrdy_deltap.setItemText(3, _translate("MainWindow", "+0.5", None))
        self.comboBox_Mrdy_deltap.setItemText(4, _translate("MainWindow", "+inf", None))
        self.label_is_Vrdy.setText(_translate("MainWindow", "------------", None))
        self.lineEdit_req_Vrdy.setText(_translate("MainWindow", "500", None))
        self.label_46.setText(_translate("MainWindow", "Vrdy[kN]=", None))
        self.label_is_Mrdz.setText(_translate("MainWindow", "------------", None))
        self.label_48.setText(_translate("MainWindow", "Mrdz[kNm]=", None))
        self.lineEdit_req_Mrdz.setText(_translate("MainWindow", "400", None))
        self.comboBox_Mrdy_deltan.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Mrdy_deltan.setItemText(1, _translate("MainWindow", "-0.1", None))
        self.comboBox_Mrdy_deltan.setItemText(2, _translate("MainWindow", "-0.2", None))
        self.comboBox_Mrdy_deltan.setItemText(3, _translate("MainWindow", "-0.5", None))
        self.comboBox_Mrdy_deltan.setItemText(4, _translate("MainWindow", "-1.0", None))
        self.lineEdit_req_Nrd.setText(_translate("MainWindow", "500", None))
        self.label_44.setText(_translate("MainWindow", "Nrd[kN]=", None))
        self.label_is_Nrd.setText(_translate("MainWindow", "------------", None))
        self.lineEdit_req_Mrdy.setText(_translate("MainWindow", "800", None))
        self.comboBox_Nrd_deltap.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Nrd_deltap.setItemText(1, _translate("MainWindow", "+0.1", None))
        self.comboBox_Nrd_deltap.setItemText(2, _translate("MainWindow", "+0.2", None))
        self.comboBox_Nrd_deltap.setItemText(3, _translate("MainWindow", "+0.5", None))
        self.comboBox_Nrd_deltap.setItemText(4, _translate("MainWindow", "+inf", None))
        self.label_is_Mrdy.setText(_translate("MainWindow", "------------", None))
        self.label_45.setText(_translate("MainWindow", "Mrdy[kNm]=", None))
        self.label_49.setText(_translate("MainWindow", "Vrdz[kN]=", None))
        self.comboBox_Vrdz_deltan.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Vrdz_deltan.setItemText(1, _translate("MainWindow", "-0.1", None))
        self.comboBox_Vrdz_deltan.setItemText(2, _translate("MainWindow", "-0.2", None))
        self.comboBox_Vrdz_deltan.setItemText(3, _translate("MainWindow", "-0.5", None))
        self.comboBox_Vrdz_deltan.setItemText(4, _translate("MainWindow", "-1.0", None))
        self.comboBox_Vrdy_deltap.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Vrdy_deltap.setItemText(1, _translate("MainWindow", "+0.1", None))
        self.comboBox_Vrdy_deltap.setItemText(2, _translate("MainWindow", "+0.2", None))
        self.comboBox_Vrdy_deltap.setItemText(3, _translate("MainWindow", "+0.5", None))
        self.comboBox_Vrdy_deltap.setItemText(4, _translate("MainWindow", "+inf", None))
        self.comboBox_Vrdz_deltap.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Vrdz_deltap.setItemText(1, _translate("MainWindow", "+0.1", None))
        self.comboBox_Vrdz_deltap.setItemText(2, _translate("MainWindow", "+0.2", None))
        self.comboBox_Vrdz_deltap.setItemText(3, _translate("MainWindow", "+0.5", None))
        self.comboBox_Vrdz_deltap.setItemText(4, _translate("MainWindow", "+inf", None))
        self.label_27.setText(_translate("MainWindow", "steel grade -", None))
        self.label_28.setText(_translate("MainWindow", "instability[ ]~", None))
        self.comboBox_instalility.setItemText(0, _translate("MainWindow", "1.0", None))
        self.comboBox_instalility.setItemText(1, _translate("MainWindow", "0.9", None))
        self.comboBox_instalility.setItemText(2, _translate("MainWindow", "0.8", None))
        self.comboBox_instalility.setItemText(3, _translate("MainWindow", "0.7", None))
        self.comboBox_instalility.setItemText(4, _translate("MainWindow", "0.6", None))
        self.comboBox_instalility.setItemText(5, _translate("MainWindow", "0.5", None))
        self.comboBox_instalility.setItemText(6, _translate("MainWindow", "0.4", None))
        self.comboBox_instalility.setItemText(7, _translate("MainWindow", "0.3", None))
        self.pushButton_zoom_in.setText(_translate("MainWindow", "+", None))
        self.pushButton_zoom_out.setText(_translate("MainWindow", "-", None))
        self.checkBox_PropertiesDescription.setText(_translate("MainWindow", "Properties description", None))
        self.menuBase.setTitle(_translate("MainWindow", "Base", None))
        self.actionLoad.setText(_translate("MainWindow", "Load...", None))

