
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0358b527dabedac432d4cba660f530480b3aff97",
 "version": "v0.1.1-alpha.post.dev53"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
