# Generated by Django 2.0.5 on 2018-05-22 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_auto_20180522_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='TargetState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('OK', 'OK'), ('NG', 'NG')], max_length=10, verbose_name='State label')),
                ('begin_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='monitors.Target')),
            ],
            options={
                'ordering': ['-begin_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='targetstate',
            unique_together={('target', 'begin_at')},
        ),
    ]
