language: python
python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"

sudo: false
dist: trusty

env:
- WITH_EXTRAS="fast,icu"
- WITH_EXTRAS=""

addons:
  apt:
    packages:
    - libicu-dev
    - language-pack-de
    - language-pack-en

install:
- pip install -U pip
- pip install tox-travis codacy-coverage codecov

script:
- tox

after_success:
- coverage xml
- python-codacy-coverage -r coverage.xml
- codecov
