import six
from ipywidgets import Widget, DOMWidget, widget_serialization, Color, register
from traitlets import (
    Unicode, Int, CInt, Instance, ForwardDeclaredInstance, This, Enum,
    Tuple, List, Dict, Float, CFloat, Bool, Union, Any,
    )

from .._base.Three import ThreeWidget
from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget


@register
class JSONLoader(ThreeWidget):
    """JSONLoader

    Autogenerated by generate-wrappers.js
    See https://threejs.org/docs/#api/loaders/JSONLoader
    """

    def __init__(self, **kwargs):
        super(JSONLoader, self).__init__(**kwargs)

    _model_name = Unicode('JSONLoaderModel').tag(sync=True)


if six.PY3:
    import inspect
    # Include explicit signature since the metaclass screws it up
    JSONLoader.__signature__ = inspect.signature(JSONLoader.__init__)
