# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0006_allow_blank_files_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='item',
            field=models.FileField(upload_to='sponsors_files'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Url to link back to the sponsor if required'),
        ),
        migrations.AlterField(
            model_name='sponsorshippackage',
            name='currency',
            field=models.CharField(default='$', help_text='Currency symbol for the sponsorship amount.', max_length=16),
        ),
    ]
