
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-17T10:01:07-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "288cb44421c1fc0375a46b79fad51e474ae1ab07",
 "version": "0.39.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
