
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "23610d43f6fa47b5d8a208153581d29e4bfb5ac3",
 "version": "2.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
