
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-13T11:20:59-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b0e9265fc2ba8212267248536fe8976511d59cc1",
 "version": "4.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
