- name: "debug task"
  debug:
    msg: "{{ os_heat_group }}"

- name: "waiting on each job id"
  async_status_custom:
    jid: "{{ os_heat_group['ansible_job_id'] }}"
  register: job_result
  until: job_result.finished
  retries: 30

- name: "Append outputitem to topology_outputs"
  set_fact:
    async_outputs_os_heat: "{{ async_outputs_os_heat + [job_result] }}"
