__version__ = "1.0.9"
__title__ = "dkamotsky.logr"
__description__ = "Logging Utility"
__uri__ = "https://github.com/dkamotsky/wheels/logr/"
__doc__ = __description__ + " <" + __uri__ + ">"
__author__ = "Denis Kamotsky"
__email__ = "denis.kamotsky@macys.com"
__license__ = "PROPRIETARY SOFTWARE, No License Granted"
__copyright__ = "Copyright (c) 2017-2018 macys.com"

