dist: trusty
sudo: false
language: python

python:
- 2.7
- &latest_py3 3.6

jobs:
  fast_finish: true
  include:
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    install: skip
    script: skip
    deploy:
      provider: pypi
      on:
        tags: true
        all_branches: true
      user: jaraco
      password:
        secure: iE+AgX9PCRJrCmmBpAQNpLfZH4KmCQPxqJnHjZS7xLtwL81XqeJuziX+XN0O6JziKXME7PJJplSLCVkdfQfqHVZz5u5ZTrsTCX36bgeD6UYIh5epa0wl+FZvL2EXyFB3vhNzgsp17gXNSWGZWB3Mq4MWzWq4J0y4IvyedjpWPvnTEkBBDsABuBDKKxPak/wQik5dLMY1unavAUTvaxaLFiuAE5GCh8sysCp/0yCmsk2onM/6j2nafa3RGfT2zrfZNyUGxDT5IAOLjnA86Xghinl9KwQndx3z+p3Czs5CZzmFEouEbcZss6Q2NzUBTd9Md7qC6Ct0K38OdEdBH4sNomheM/B54CF1S2vK6CmyAElKKNc3wYZgEnjmzvQ3wubx336SE9FBvFt3qCLsQuXGq/Xh+9DJ3BnjiIyXJOgDlt2ogaJbgaAfQOVW4JLxnYj7b3W8khAAtpAmzEHinY86Fzq0d61rWJUfyMwROEhCY6FuPJk0+8qMG0UhtpXhgCukmO9RWJ6LAItAn/gb0bEPEwxYnIaplvoppLu8EXqeAMVyEcne4oBrKjW+EJMO91mr96U57GMUQ7bB/S6CiJiSeJLOqFeY4cPkpwWtcTvdzUiwTKtRrRzTzw1sAdRAkRZ65d+VZdIhj8wkIvQDpelGDx9fAdkp0E0cU9rOG0K5G9M=
      distributions: dists
      skip_cleanup: true
      skip_upload_docs: true

cache: pip

install:
- pip install tox tox-venv

script: tox
