
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-14T12:08:38+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5750c21bd885bb5ac94d4552f5f63d5244c5d2ac",
 "version": "0.4.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
