{% set name = "pyMaBoSS" %}
{% set version = "0.6.1" %}
package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_rev: v{{ version }}
  git_url: https://github.com/thenlevy/pyMaBoSS.git

channels:
  - colomoto

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - colomoto_jupyter
    - maboss
    - pandas
    - pyparsing
    - python
    - matplotlib

about:
  home: https://github.com/thenlevy/pyMaBoSS
  summary: 'MaBoSS python interface'

