
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-07T18:13:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "375dc7f90d99b070f80edb08b7b5d7a5393b0c31",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
