---
# This playbook provisions the openstack topology.

- name:  "schema check and Pre Provisioning Activities on topology_file"
  hosts: localhost
  gather_facts: True
  roles:
    - { role: 'common' }

- name:  "Provisioning openstack resources"
  hosts: localhost
  gather_facts: True
  roles:
    - { role: 'aws' }

- name: "Writing contents to file"
  hosts: localhost
  gather_facts: True
  roles:
    - { role: 'gather_resources' }

- name: "inventory generation role"
  hosts: localhost
  gather_facts: True
  roles:
    - role: 'inventory_gen'
      when:
        - state == 'present'
        - layout_data is defined
