
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-28T14:31:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "12bda2d8b1e5b4082a322c6140807066f5288d9a",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
