# coding: utf-8

"""
    Fiddle Options Platform

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.mercury.client.model.option_leg import OptionLeg  # noqa: E501
from swagger_client.rest import ApiException


class TestOptionLeg(unittest.TestCase):
    """OptionLeg unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOptionLeg(self):
        """Test OptionLeg"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.option_leg.OptionLeg()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
