version: '2.2'

services:
    adminer:
        image: edyan/adminer
        container_name: ${COMPOSE_PROJECT_NAME}_adminer
        hostname: ${COMPOSE_PROJECT_NAME}_adminer
        networks: [stakkr]
        ports:
            - ${DOCKER_ADMINER_EXPOSE}:80
