
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-29T18:08:27-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a0fe327d47a546f1b87d78a0383a6a18464ad84",
 "version": "0.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
