# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QFreac(object):
    def setupUi(self, QFreac):
        QFreac.setObjectName("QFreac")
        QFreac.resize(636, 799)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/freac"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QFreac.setWindowIcon(icon)
        QFreac.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(QFreac)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(QFreac)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dirEdit = QtWidgets.QLineEdit(self.groupBox)
        self.dirEdit.setObjectName("dirEdit")
        self.gridLayout.addWidget(self.dirEdit, 0, 1, 1, 1)
        self.dirButton = QtWidgets.QToolButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/folder"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dirButton.setIcon(icon1)
        self.dirButton.setObjectName("dirButton")
        self.gridLayout.addWidget(self.dirButton, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.floodEdit = QtWidgets.QLineEdit(self.groupBox)
        self.floodEdit.setObjectName("floodEdit")
        self.gridLayout.addWidget(self.floodEdit, 1, 1, 1, 1)
        self.floodButton = QtWidgets.QToolButton(self.groupBox)
        self.floodButton.setIcon(icon1)
        self.floodButton.setObjectName("floodButton")
        self.gridLayout.addWidget(self.floodButton, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.splineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.splineEdit.setObjectName("splineEdit")
        self.gridLayout.addWidget(self.splineEdit, 2, 1, 1, 1)
        self.splineButton = QtWidgets.QToolButton(self.groupBox)
        self.splineButton.setIcon(icon1)
        self.splineButton.setObjectName("splineButton")
        self.gridLayout.addWidget(self.splineButton, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.darkEdit = QtWidgets.QLineEdit(self.groupBox)
        self.darkEdit.setText("")
        self.darkEdit.setObjectName("darkEdit")
        self.gridLayout.addWidget(self.darkEdit, 3, 1, 1, 1)
        self.darkButton = QtWidgets.QToolButton(self.groupBox)
        self.darkButton.setIcon(icon1)
        self.darkButton.setObjectName("darkButton")
        self.gridLayout.addWidget(self.darkButton, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(QFreac)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.llambdaEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.llambdaEdit.setObjectName("llambdaEdit")
        self.gridLayout_2.addWidget(self.llambdaEdit, 0, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 1, 1, 1)
        self.phiEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.phiEdit.setObjectName("phiEdit")
        self.gridLayout_2.addWidget(self.phiEdit, 1, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 2, 1, 1, 1)
        self.kappaEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.kappaEdit.setObjectName("kappaEdit")
        self.gridLayout_2.addWidget(self.kappaEdit, 2, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 2, 3, 1, 1)
        self.omegaCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.omegaCheckBox.setText("")
        self.omegaCheckBox.setCheckable(True)
        self.omegaCheckBox.setObjectName("omegaCheckBox")
        self.gridLayout_2.addWidget(self.omegaCheckBox, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 1, 1, 1)
        self.omegaEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.omegaEdit.setEnabled(False)
        self.omegaEdit.setObjectName("omegaEdit")
        self.gridLayout_2.addWidget(self.omegaEdit, 3, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 3, 3, 1, 1)
        self.dOmegaCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.dOmegaCheckBox.setText("")
        self.dOmegaCheckBox.setCheckable(True)
        self.dOmegaCheckBox.setObjectName("dOmegaCheckBox")
        self.gridLayout_2.addWidget(self.dOmegaCheckBox, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 1, 1, 1)
        self.dOmegaEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.dOmegaEdit.setEnabled(False)
        self.dOmegaEdit.setObjectName("dOmegaEdit")
        self.gridLayout_2.addWidget(self.dOmegaEdit, 4, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 4, 3, 1, 1)
        self.pixCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.pixCheckBox.setText("")
        self.pixCheckBox.setCheckable(True)
        self.pixCheckBox.setObjectName("pixCheckBox")
        self.gridLayout_2.addWidget(self.pixCheckBox, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 1, 1, 1)
        self.pixEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.pixEdit.setEnabled(False)
        self.pixEdit.setObjectName("pixEdit")
        self.gridLayout_2.addWidget(self.pixEdit, 5, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 5, 3, 1, 1)
        self.distCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.distCheckBox.setText("")
        self.distCheckBox.setCheckable(True)
        self.distCheckBox.setObjectName("distCheckBox")
        self.gridLayout_2.addWidget(self.distCheckBox, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 1, 1, 1)
        self.distEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.distEdit.setEnabled(False)
        self.distEdit.setObjectName("distEdit")
        self.gridLayout_2.addWidget(self.distEdit, 6, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 6, 3, 1, 1)
        self.x0CheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.x0CheckBox.setText("")
        self.x0CheckBox.setCheckable(True)
        self.x0CheckBox.setObjectName("x0CheckBox")
        self.gridLayout_2.addWidget(self.x0CheckBox, 7, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 7, 1, 1, 1)
        self.x0Edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.x0Edit.setEnabled(False)
        self.x0Edit.setObjectName("x0Edit")
        self.gridLayout_2.addWidget(self.x0Edit, 7, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 7, 3, 1, 1)
        self.y0CheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.y0CheckBox.setText("")
        self.y0CheckBox.setCheckable(True)
        self.y0CheckBox.setObjectName("y0CheckBox")
        self.gridLayout_2.addWidget(self.y0CheckBox, 8, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 8, 1, 1, 1)
        self.y0Edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.y0Edit.setEnabled(False)
        self.y0Edit.setObjectName("y0Edit")
        self.gridLayout_2.addWidget(self.y0Edit, 8, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 8, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runButton = QtWidgets.QPushButton(QFreac)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/run"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runButton.setIcon(icon2)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.stopButton = QtWidgets.QPushButton(QFreac)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/stop"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon3)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.progressBar = QtWidgets.QProgressBar(QFreac)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(QFreac)
        QtCore.QMetaObject.connectSlotsByName(QFreac)

    def retranslateUi(self, QFreac):
        _translate = QtCore.QCoreApplication.translate
        QFreac.setWindowTitle(_translate("QFreac", "Freac"))
        self.groupBox.setTitle(_translate("QFreac", "Files"))
        self.label.setText(_translate("QFreac", "Base dir:"))
        self.dirButton.setText(_translate("QFreac", "..."))
        self.label_2.setText(_translate("QFreac", "Flood:"))
        self.floodButton.setText(_translate("QFreac", "..."))
        self.label_3.setText(_translate("QFreac", "Spline:"))
        self.splineButton.setText(_translate("QFreac", "..."))
        self.label_4.setText(_translate("QFreac", "Dark:"))
        self.darkButton.setText(_translate("QFreac", "..."))
        self.groupBox_2.setTitle(_translate("QFreac", "Parameters"))
        self.label_5.setText(_translate("QFreac", "<html><head/><body><p>λ:</p></body></html>"))
        self.label_18.setText(_translate("QFreac", "<html><head/><body><p>&Aring;</p></body></html>"))
        self.label_12.setText(_translate("QFreac", "<html><head/><body><p>&phi;:</p></body></html>"))
        self.label_17.setText(_translate("QFreac", "<html><head/><body><p>deg</p></body></html>"))
        self.label_21.setText(_translate("QFreac", "<html><head/><body><p>&kappa;:</p></body></html>"))
        self.label_22.setText(_translate("QFreac", "<html><head/><body><p>deg</p></body></html>"))
        self.label_6.setText(_translate("QFreac", "<html><head/><body><p>ω<span style=\" vertical-align:sub;\">0</span>:</p></body></html>"))
        self.label_16.setText(_translate("QFreac", "<html><head/><body><p>deg</p></body></html>"))
        self.label_7.setText(_translate("QFreac", "<html><head/><body><p>&Delta;&omega;:</p></body></html>"))
        self.label_15.setText(_translate("QFreac", "<html><head/><body><p>deg</p></body></html>"))
        self.label_8.setText(_translate("QFreac", "<html><head/><body><p>Pixel size:</p></body></html>"))
        self.label_14.setText(_translate("QFreac", "<html><head/><body><p>m</p></body></html>"))
        self.label_9.setText(_translate("QFreac", "<html><head/><body><p>Distance:</p></body></html>"))
        self.label_13.setText(_translate("QFreac", "<html><head/><body><p>m</p></body></html>"))
        self.label_10.setText(_translate("QFreac", "<html><head/><body><p>x<span style=\" vertical-align:sub;\">0</span>:</p></body></html>"))
        self.label_19.setText(_translate("QFreac", "<html><head/><body><p>px</p></body></html>"))
        self.label_11.setText(_translate("QFreac", "<html><head/><body><p>y<span style=\" vertical-align:sub;\">0</span>:</p></body></html>"))
        self.label_20.setText(_translate("QFreac", "<html><head/><body><p>px</p></body></html>"))
        self.runButton.setText(_translate("QFreac", "Run"))
        self.stopButton.setText(_translate("QFreac", "Stop"))

from . import resources_rc
