import six
from ipywidgets import Widget, DOMWidget, widget_serialization, Color, register
from traitlets import (
    Unicode, Int, CInt, Instance, ForwardDeclaredInstance, This, Enum,
    Tuple, List, Dict, Float, CFloat, Bool, Union, Any,
    )

from ..._base.Three import ThreeWidget
from ...enums import *
from ...traits import *

from ..._base.Three import ThreeWidget


@register
class WebGLIndexedBufferRenderer(ThreeWidget):
    """WebGLIndexedBufferRenderer

    Autogenerated by generate-wrappers.js
    See https://threejs.org/docs/#api/renderers/webgl/WebGLIndexedBufferRenderer
    """

    def __init__(self, **kwargs):
        super(WebGLIndexedBufferRenderer, self).__init__(**kwargs)

    _model_name = Unicode('WebGLIndexedBufferRendererModel').tag(sync=True)


if six.PY3:
    import inspect
    # Include explicit signature since the metaclass screws it up
    WebGLIndexedBufferRenderer.__signature__ = inspect.signature(WebGLIndexedBufferRenderer.__init__)
