# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ava_engine/ava/engine_core.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ava_engine/ava/engine_core.proto',
  package='ava_engine',
  syntax='proto3',
  serialized_pb=_b('\n ava_engine/ava/engine_core.proto\x12\nava_engine\"\x12\n\x04\x46\x65\x65\x64\x12\n\n\x02id\x18\x01 \x01(\t\"Q\n\x10\x46\x65\x61tureArguments\x12\x0f\n\x07\x63lasses\x18\x01 \x03(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x1a\n\x12gpu_usage_fraction\x18\x03 \x01(\x02\",\n\tImageItem\x12\x11\n\tcustom_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"I\n\x0b\x42oundingBox\x12\r\n\x05x_min\x18\x01 \x01(\x05\x12\r\n\x05y_min\x18\x02 \x01(\x05\x12\r\n\x05x_max\x18\x03 \x01(\x05\x12\r\n\x05y_max\x18\x04 \x01(\x05\x62\x06proto3')
)




_FEED = _descriptor.Descriptor(
  name='Feed',
  full_name='ava_engine.Feed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ava_engine.Feed.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=66,
)


_FEATUREARGUMENTS = _descriptor.Descriptor(
  name='FeatureArguments',
  full_name='ava_engine.FeatureArguments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='classes', full_name='ava_engine.FeatureArguments.classes', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_id', full_name='ava_engine.FeatureArguments.model_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpu_usage_fraction', full_name='ava_engine.FeatureArguments.gpu_usage_fraction', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=149,
)


_IMAGEITEM = _descriptor.Descriptor(
  name='ImageItem',
  full_name='ava_engine.ImageItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='custom_id', full_name='ava_engine.ImageItem.custom_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ava_engine.ImageItem.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=195,
)


_BOUNDINGBOX = _descriptor.Descriptor(
  name='BoundingBox',
  full_name='ava_engine.BoundingBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_min', full_name='ava_engine.BoundingBox.x_min', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_min', full_name='ava_engine.BoundingBox.y_min', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_max', full_name='ava_engine.BoundingBox.x_max', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_max', full_name='ava_engine.BoundingBox.y_max', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=270,
)

DESCRIPTOR.message_types_by_name['Feed'] = _FEED
DESCRIPTOR.message_types_by_name['FeatureArguments'] = _FEATUREARGUMENTS
DESCRIPTOR.message_types_by_name['ImageItem'] = _IMAGEITEM
DESCRIPTOR.message_types_by_name['BoundingBox'] = _BOUNDINGBOX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Feed = _reflection.GeneratedProtocolMessageType('Feed', (_message.Message,), dict(
  DESCRIPTOR = _FEED,
  __module__ = 'ava_engine.ava.engine_core_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.Feed)
  ))
_sym_db.RegisterMessage(Feed)

FeatureArguments = _reflection.GeneratedProtocolMessageType('FeatureArguments', (_message.Message,), dict(
  DESCRIPTOR = _FEATUREARGUMENTS,
  __module__ = 'ava_engine.ava.engine_core_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.FeatureArguments)
  ))
_sym_db.RegisterMessage(FeatureArguments)

ImageItem = _reflection.GeneratedProtocolMessageType('ImageItem', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEITEM,
  __module__ = 'ava_engine.ava.engine_core_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.ImageItem)
  ))
_sym_db.RegisterMessage(ImageItem)

BoundingBox = _reflection.GeneratedProtocolMessageType('BoundingBox', (_message.Message,), dict(
  DESCRIPTOR = _BOUNDINGBOX,
  __module__ = 'ava_engine.ava.engine_core_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.BoundingBox)
  ))
_sym_db.RegisterMessage(BoundingBox)


# @@protoc_insertion_point(module_scope)
