# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ava_engine/ava/feature_face_recognition.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ava_engine.ava import engine_core_pb2 as ava__engine_dot_ava_dot_engine__core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ava_engine/ava/feature_face_recognition.proto',
  package='ava_engine',
  syntax='proto3',
  serialized_pb=_b('\n-ava_engine/ava/feature_face_recognition.proto\x12\nava_engine\x1a ava_engine/ava/engine_core.proto\"V\n\x17\x41\x64\x64\x46\x61\x63\x65RequestImageItem\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12-\n\x0c\x62ounding_box\x18\x02 \x01(\x0b\x32\x17.ava_engine.BoundingBox\"_\n\x0e\x41\x64\x64\x46\x61\x63\x65Request\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x33\n\x06images\x18\x03 \x03(\x0b\x32#.ava_engine.AddFaceRequestImageItem\"\x11\n\x0f\x41\x64\x64\x46\x61\x63\x65Response\"\x1f\n\x11RemoveFaceRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x14\n\x12RemoveFaceResponse\"K\n\x11\x44\x65tectFaceRequest\x12\x0f\n\x07\x66\x65\x65\x64_id\x18\x01 \x01(\t\x12%\n\x06images\x18\x02 \x03(\x0b\x32\x15.ava_engine.ImageItem\"\x9e\x01\n\x15\x46\x61\x63\x65RecognitionResult\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\x11\n\tcustom_id\x18\x02 \x01(\t\x12\x0f\n\x07\x66\x61\x63\x65_id\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12-\n\x0c\x62ounding_box\x18\x06 \x01(\x0b\x32\x17.ava_engine.BoundingBox\"Y\n\x12\x44\x65tectFaceResponse\x12\x0f\n\x07\x66\x65\x65\x64_id\x18\x01 \x01(\t\x12\x32\n\x07results\x18\x02 \x03(\x0b\x32!.ava_engine.FaceRecognitionResult\"\x12\n\x10ListFacesRequest\"K\n\x15ListFacesResponseItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x18\n\x10\x65mbeddings_count\x18\x03 \x01(\x05\"E\n\x11ListFacesResponse\x12\x30\n\x05\x66\x61\x63\x65s\x18\x01 \x03(\x0b\x32!.ava_engine.ListFacesResponseItemb\x06proto3')
  ,
  dependencies=[ava__engine_dot_ava_dot_engine__core__pb2.DESCRIPTOR,])




_ADDFACEREQUESTIMAGEITEM = _descriptor.Descriptor(
  name='AddFaceRequestImageItem',
  full_name='ava_engine.AddFaceRequestImageItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ava_engine.AddFaceRequestImageItem.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bounding_box', full_name='ava_engine.AddFaceRequestImageItem.bounding_box', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=181,
)


_ADDFACEREQUEST = _descriptor.Descriptor(
  name='AddFaceRequest',
  full_name='ava_engine.AddFaceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ava_engine.AddFaceRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ava_engine.AddFaceRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='ava_engine.AddFaceRequest.images', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=278,
)


_ADDFACERESPONSE = _descriptor.Descriptor(
  name='AddFaceResponse',
  full_name='ava_engine.AddFaceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=297,
)


_REMOVEFACEREQUEST = _descriptor.Descriptor(
  name='RemoveFaceRequest',
  full_name='ava_engine.RemoveFaceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ava_engine.RemoveFaceRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=330,
)


_REMOVEFACERESPONSE = _descriptor.Descriptor(
  name='RemoveFaceResponse',
  full_name='ava_engine.RemoveFaceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=352,
)


_DETECTFACEREQUEST = _descriptor.Descriptor(
  name='DetectFaceRequest',
  full_name='ava_engine.DetectFaceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feed_id', full_name='ava_engine.DetectFaceRequest.feed_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='ava_engine.DetectFaceRequest.images', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=429,
)


_FACERECOGNITIONRESULT = _descriptor.Descriptor(
  name='FaceRecognitionResult',
  full_name='ava_engine.FaceRecognitionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_id', full_name='ava_engine.FaceRecognitionResult.image_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_id', full_name='ava_engine.FaceRecognitionResult.custom_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_id', full_name='ava_engine.FaceRecognitionResult.face_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ava_engine.FaceRecognitionResult.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='ava_engine.FaceRecognitionResult.confidence', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bounding_box', full_name='ava_engine.FaceRecognitionResult.bounding_box', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=590,
)


_DETECTFACERESPONSE = _descriptor.Descriptor(
  name='DetectFaceResponse',
  full_name='ava_engine.DetectFaceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feed_id', full_name='ava_engine.DetectFaceResponse.feed_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='results', full_name='ava_engine.DetectFaceResponse.results', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=592,
  serialized_end=681,
)


_LISTFACESREQUEST = _descriptor.Descriptor(
  name='ListFacesRequest',
  full_name='ava_engine.ListFacesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=683,
  serialized_end=701,
)


_LISTFACESRESPONSEITEM = _descriptor.Descriptor(
  name='ListFacesResponseItem',
  full_name='ava_engine.ListFacesResponseItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ava_engine.ListFacesResponseItem.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ava_engine.ListFacesResponseItem.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='embeddings_count', full_name='ava_engine.ListFacesResponseItem.embeddings_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=703,
  serialized_end=778,
)


_LISTFACESRESPONSE = _descriptor.Descriptor(
  name='ListFacesResponse',
  full_name='ava_engine.ListFacesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='faces', full_name='ava_engine.ListFacesResponse.faces', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=780,
  serialized_end=849,
)

_ADDFACEREQUESTIMAGEITEM.fields_by_name['bounding_box'].message_type = ava__engine_dot_ava_dot_engine__core__pb2._BOUNDINGBOX
_ADDFACEREQUEST.fields_by_name['images'].message_type = _ADDFACEREQUESTIMAGEITEM
_DETECTFACEREQUEST.fields_by_name['images'].message_type = ava__engine_dot_ava_dot_engine__core__pb2._IMAGEITEM
_FACERECOGNITIONRESULT.fields_by_name['bounding_box'].message_type = ava__engine_dot_ava_dot_engine__core__pb2._BOUNDINGBOX
_DETECTFACERESPONSE.fields_by_name['results'].message_type = _FACERECOGNITIONRESULT
_LISTFACESRESPONSE.fields_by_name['faces'].message_type = _LISTFACESRESPONSEITEM
DESCRIPTOR.message_types_by_name['AddFaceRequestImageItem'] = _ADDFACEREQUESTIMAGEITEM
DESCRIPTOR.message_types_by_name['AddFaceRequest'] = _ADDFACEREQUEST
DESCRIPTOR.message_types_by_name['AddFaceResponse'] = _ADDFACERESPONSE
DESCRIPTOR.message_types_by_name['RemoveFaceRequest'] = _REMOVEFACEREQUEST
DESCRIPTOR.message_types_by_name['RemoveFaceResponse'] = _REMOVEFACERESPONSE
DESCRIPTOR.message_types_by_name['DetectFaceRequest'] = _DETECTFACEREQUEST
DESCRIPTOR.message_types_by_name['FaceRecognitionResult'] = _FACERECOGNITIONRESULT
DESCRIPTOR.message_types_by_name['DetectFaceResponse'] = _DETECTFACERESPONSE
DESCRIPTOR.message_types_by_name['ListFacesRequest'] = _LISTFACESREQUEST
DESCRIPTOR.message_types_by_name['ListFacesResponseItem'] = _LISTFACESRESPONSEITEM
DESCRIPTOR.message_types_by_name['ListFacesResponse'] = _LISTFACESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddFaceRequestImageItem = _reflection.GeneratedProtocolMessageType('AddFaceRequestImageItem', (_message.Message,), dict(
  DESCRIPTOR = _ADDFACEREQUESTIMAGEITEM,
  __module__ = 'ava_engine.ava.feature_face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.AddFaceRequestImageItem)
  ))
_sym_db.RegisterMessage(AddFaceRequestImageItem)

AddFaceRequest = _reflection.GeneratedProtocolMessageType('AddFaceRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDFACEREQUEST,
  __module__ = 'ava_engine.ava.feature_face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.AddFaceRequest)
  ))
_sym_db.RegisterMessage(AddFaceRequest)

AddFaceResponse = _reflection.GeneratedProtocolMessageType('AddFaceResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDFACERESPONSE,
  __module__ = 'ava_engine.ava.feature_face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.AddFaceResponse)
  ))
_sym_db.RegisterMessage(AddFaceResponse)

RemoveFaceRequest = _reflection.GeneratedProtocolMessageType('RemoveFaceRequest', (_message.Message,), dict(
  DESCRIPTOR = _REMOVEFACEREQUEST,
  __module__ = 'ava_engine.ava.feature_face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.RemoveFaceRequest)
  ))
_sym_db.RegisterMessage(RemoveFaceRequest)

RemoveFaceResponse = _reflection.GeneratedProtocolMessageType('RemoveFaceResponse', (_message.Message,), dict(
  DESCRIPTOR = _REMOVEFACERESPONSE,
  __module__ = 'ava_engine.ava.feature_face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.RemoveFaceResponse)
  ))
_sym_db.RegisterMessage(RemoveFaceResponse)

DetectFaceRequest = _reflection.GeneratedProtocolMessageType('DetectFaceRequest', (_message.Message,), dict(
  DESCRIPTOR = _DETECTFACEREQUEST,
  __module__ = 'ava_engine.ava.feature_face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.DetectFaceRequest)
  ))
_sym_db.RegisterMessage(DetectFaceRequest)

FaceRecognitionResult = _reflection.GeneratedProtocolMessageType('FaceRecognitionResult', (_message.Message,), dict(
  DESCRIPTOR = _FACERECOGNITIONRESULT,
  __module__ = 'ava_engine.ava.feature_face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.FaceRecognitionResult)
  ))
_sym_db.RegisterMessage(FaceRecognitionResult)

DetectFaceResponse = _reflection.GeneratedProtocolMessageType('DetectFaceResponse', (_message.Message,), dict(
  DESCRIPTOR = _DETECTFACERESPONSE,
  __module__ = 'ava_engine.ava.feature_face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.DetectFaceResponse)
  ))
_sym_db.RegisterMessage(DetectFaceResponse)

ListFacesRequest = _reflection.GeneratedProtocolMessageType('ListFacesRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTFACESREQUEST,
  __module__ = 'ava_engine.ava.feature_face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.ListFacesRequest)
  ))
_sym_db.RegisterMessage(ListFacesRequest)

ListFacesResponseItem = _reflection.GeneratedProtocolMessageType('ListFacesResponseItem', (_message.Message,), dict(
  DESCRIPTOR = _LISTFACESRESPONSEITEM,
  __module__ = 'ava_engine.ava.feature_face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.ListFacesResponseItem)
  ))
_sym_db.RegisterMessage(ListFacesResponseItem)

ListFacesResponse = _reflection.GeneratedProtocolMessageType('ListFacesResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTFACESRESPONSE,
  __module__ = 'ava_engine.ava.feature_face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.ListFacesResponse)
  ))
_sym_db.RegisterMessage(ListFacesResponse)


# @@protoc_insertion_point(module_scope)
