# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ava_engine/ava/feature_classification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ava_engine.ava import engine_core_pb2 as ava__engine_dot_ava_dot_engine__core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ava_engine/ava/feature_classification.proto',
  package='ava_engine',
  syntax='proto3',
  serialized_pb=_b('\n+ava_engine/ava/feature_classification.proto\x12\nava_engine\x1a ava_engine/ava/engine_core.proto\"Z\n\x0f\x43lassifyRequest\x12\x0f\n\x07\x66\x65\x65\x64_id\x18\x01 \x01(\t\x12%\n\x06images\x18\x02 \x03(\x0b\x32\x15.ava_engine.ImageItem\x12\x0f\n\x07\x63lasses\x18\x03 \x03(\t\"P\n\x10\x43lassifyResponse\x12\x0f\n\x07\x66\x65\x65\x64_id\x18\x01 \x01(\t\x12+\n\x07results\x18\x02 \x03(\x0b\x32\x1a.ava_engine.ClassifyResult\"X\n\x0e\x43lassifyResult\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\x11\n\tcustom_id\x18\x02 \x01(\t\x12\r\n\x05\x63lass\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x62\x06proto3')
  ,
  dependencies=[ava__engine_dot_ava_dot_engine__core__pb2.DESCRIPTOR,])




_CLASSIFYREQUEST = _descriptor.Descriptor(
  name='ClassifyRequest',
  full_name='ava_engine.ClassifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feed_id', full_name='ava_engine.ClassifyRequest.feed_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='ava_engine.ClassifyRequest.images', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classes', full_name='ava_engine.ClassifyRequest.classes', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=183,
)


_CLASSIFYRESPONSE = _descriptor.Descriptor(
  name='ClassifyResponse',
  full_name='ava_engine.ClassifyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feed_id', full_name='ava_engine.ClassifyResponse.feed_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='results', full_name='ava_engine.ClassifyResponse.results', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=265,
)


_CLASSIFYRESULT = _descriptor.Descriptor(
  name='ClassifyResult',
  full_name='ava_engine.ClassifyResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_id', full_name='ava_engine.ClassifyResult.image_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_id', full_name='ava_engine.ClassifyResult.custom_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='class', full_name='ava_engine.ClassifyResult.class', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='ava_engine.ClassifyResult.confidence', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=355,
)

_CLASSIFYREQUEST.fields_by_name['images'].message_type = ava__engine_dot_ava_dot_engine__core__pb2._IMAGEITEM
_CLASSIFYRESPONSE.fields_by_name['results'].message_type = _CLASSIFYRESULT
DESCRIPTOR.message_types_by_name['ClassifyRequest'] = _CLASSIFYREQUEST
DESCRIPTOR.message_types_by_name['ClassifyResponse'] = _CLASSIFYRESPONSE
DESCRIPTOR.message_types_by_name['ClassifyResult'] = _CLASSIFYRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClassifyRequest = _reflection.GeneratedProtocolMessageType('ClassifyRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFYREQUEST,
  __module__ = 'ava_engine.ava.feature_classification_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.ClassifyRequest)
  ))
_sym_db.RegisterMessage(ClassifyRequest)

ClassifyResponse = _reflection.GeneratedProtocolMessageType('ClassifyResponse', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFYRESPONSE,
  __module__ = 'ava_engine.ava.feature_classification_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.ClassifyResponse)
  ))
_sym_db.RegisterMessage(ClassifyResponse)

ClassifyResult = _reflection.GeneratedProtocolMessageType('ClassifyResult', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFYRESULT,
  __module__ = 'ava_engine.ava.feature_classification_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.ClassifyResult)
  ))
_sym_db.RegisterMessage(ClassifyResult)


# @@protoc_insertion_point(module_scope)
