# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ava_engine/ava/feature_detection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ava_engine.ava import engine_core_pb2 as ava__engine_dot_ava_dot_engine__core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ava_engine/ava/feature_detection.proto',
  package='ava_engine',
  syntax='proto3',
  serialized_pb=_b('\n&ava_engine/ava/feature_detection.proto\x12\nava_engine\x1a ava_engine/ava/engine_core.proto\"X\n\rDetectRequest\x12\x0f\n\x07\x66\x65\x65\x64_id\x18\x01 \x01(\t\x12%\n\x06images\x18\x02 \x03(\x0b\x32\x15.ava_engine.ImageItem\x12\x0f\n\x07\x63lasses\x18\x03 \x03(\t\"L\n\x0e\x44\x65tectResponse\x12\x0f\n\x07\x66\x65\x65\x64_id\x18\x01 \x01(\t\x12)\n\x07results\x18\x02 \x03(\x0b\x32\x18.ava_engine.DetectResult\"\x85\x01\n\x0c\x44\x65tectResult\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\x11\n\tcustom_id\x18\x02 \x01(\t\x12\r\n\x05\x63lass\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12-\n\x0c\x62ounding_box\x18\x05 \x01(\x0b\x32\x17.ava_engine.BoundingBoxb\x06proto3')
  ,
  dependencies=[ava__engine_dot_ava_dot_engine__core__pb2.DESCRIPTOR,])




_DETECTREQUEST = _descriptor.Descriptor(
  name='DetectRequest',
  full_name='ava_engine.DetectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feed_id', full_name='ava_engine.DetectRequest.feed_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='ava_engine.DetectRequest.images', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classes', full_name='ava_engine.DetectRequest.classes', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=176,
)


_DETECTRESPONSE = _descriptor.Descriptor(
  name='DetectResponse',
  full_name='ava_engine.DetectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feed_id', full_name='ava_engine.DetectResponse.feed_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='results', full_name='ava_engine.DetectResponse.results', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=254,
)


_DETECTRESULT = _descriptor.Descriptor(
  name='DetectResult',
  full_name='ava_engine.DetectResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_id', full_name='ava_engine.DetectResult.image_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_id', full_name='ava_engine.DetectResult.custom_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='class', full_name='ava_engine.DetectResult.class', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='ava_engine.DetectResult.confidence', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bounding_box', full_name='ava_engine.DetectResult.bounding_box', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=390,
)

_DETECTREQUEST.fields_by_name['images'].message_type = ava__engine_dot_ava_dot_engine__core__pb2._IMAGEITEM
_DETECTRESPONSE.fields_by_name['results'].message_type = _DETECTRESULT
_DETECTRESULT.fields_by_name['bounding_box'].message_type = ava__engine_dot_ava_dot_engine__core__pb2._BOUNDINGBOX
DESCRIPTOR.message_types_by_name['DetectRequest'] = _DETECTREQUEST
DESCRIPTOR.message_types_by_name['DetectResponse'] = _DETECTRESPONSE
DESCRIPTOR.message_types_by_name['DetectResult'] = _DETECTRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DetectRequest = _reflection.GeneratedProtocolMessageType('DetectRequest', (_message.Message,), dict(
  DESCRIPTOR = _DETECTREQUEST,
  __module__ = 'ava_engine.ava.feature_detection_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.DetectRequest)
  ))
_sym_db.RegisterMessage(DetectRequest)

DetectResponse = _reflection.GeneratedProtocolMessageType('DetectResponse', (_message.Message,), dict(
  DESCRIPTOR = _DETECTRESPONSE,
  __module__ = 'ava_engine.ava.feature_detection_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.DetectResponse)
  ))
_sym_db.RegisterMessage(DetectResponse)

DetectResult = _reflection.GeneratedProtocolMessageType('DetectResult', (_message.Message,), dict(
  DESCRIPTOR = _DETECTRESULT,
  __module__ = 'ava_engine.ava.feature_detection_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.DetectResult)
  ))
_sym_db.RegisterMessage(DetectResult)


# @@protoc_insertion_point(module_scope)
