# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ava_engine/ava/images_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ava_engine.ava import feature_classification_pb2 as ava__engine_dot_ava_dot_feature__classification__pb2
from ava_engine.ava import feature_detection_pb2 as ava__engine_dot_ava_dot_feature__detection__pb2
from ava_engine.ava import feature_face_recognition_pb2 as ava__engine_dot_ava_dot_feature__face__recognition__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ava_engine/ava/images_api.proto',
  package='ava_engine',
  syntax='proto3',
  serialized_pb=_b('\n\x1f\x61va_engine/ava/images_api.proto\x12\nava_engine\x1a+ava_engine/ava/feature_classification.proto\x1a&ava_engine/ava/feature_detection.proto\x1a-ava_engine/ava/feature_face_recognition.proto\"\x1d\n\x0fGetImageRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x82\x02\n\x10GetImageResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x66\x65\x65\x64_id\x18\x02 \x01(\t\x12\x11\n\tcustom_id\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x32\n\x0e\x63lassification\x18\x06 \x03(\x0b\x32\x1a.ava_engine.ClassifyResult\x12+\n\tdetection\x18\x07 \x03(\x0b\x32\x18.ava_engine.DetectResult\x12;\n\x10\x66\x61\x63\x65_recognition\x18\x08 \x03(\x0b\x32!.ava_engine.FaceRecognitionResult\"e\n\x13SearchImagesRequest\x12\x10\n\x08\x66\x65\x65\x64_ids\x18\x01 \x03(\t\x12\x0e\n\x06\x62\x65\x66ore\x18\x02 \x01(\x03\x12\r\n\x05\x61\x66ter\x18\x03 \x01(\x03\x12\r\n\x05limit\x18\x04 \x01(\x03\x12\x0e\n\x06offset\x18\x05 \x01(\x03\"D\n\x14SearchImagesResponse\x12,\n\x06images\x18\x01 \x03(\x0b\x32\x1c.ava_engine.GetImageResponseb\x06proto3')
  ,
  dependencies=[ava__engine_dot_ava_dot_feature__classification__pb2.DESCRIPTOR,ava__engine_dot_ava_dot_feature__detection__pb2.DESCRIPTOR,ava__engine_dot_ava_dot_feature__face__recognition__pb2.DESCRIPTOR,])




_GETIMAGEREQUEST = _descriptor.Descriptor(
  name='GetImageRequest',
  full_name='ava_engine.GetImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ava_engine.GetImageRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=208,
)


_GETIMAGERESPONSE = _descriptor.Descriptor(
  name='GetImageResponse',
  full_name='ava_engine.GetImageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ava_engine.GetImageResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feed_id', full_name='ava_engine.GetImageResponse.feed_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_id', full_name='ava_engine.GetImageResponse.custom_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='ava_engine.GetImageResponse.created_at', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ava_engine.GetImageResponse.data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classification', full_name='ava_engine.GetImageResponse.classification', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detection', full_name='ava_engine.GetImageResponse.detection', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_recognition', full_name='ava_engine.GetImageResponse.face_recognition', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=469,
)


_SEARCHIMAGESREQUEST = _descriptor.Descriptor(
  name='SearchImagesRequest',
  full_name='ava_engine.SearchImagesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feed_ids', full_name='ava_engine.SearchImagesRequest.feed_ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='before', full_name='ava_engine.SearchImagesRequest.before', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='after', full_name='ava_engine.SearchImagesRequest.after', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit', full_name='ava_engine.SearchImagesRequest.limit', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='ava_engine.SearchImagesRequest.offset', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=572,
)


_SEARCHIMAGESRESPONSE = _descriptor.Descriptor(
  name='SearchImagesResponse',
  full_name='ava_engine.SearchImagesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='ava_engine.SearchImagesResponse.images', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=574,
  serialized_end=642,
)

_GETIMAGERESPONSE.fields_by_name['classification'].message_type = ava__engine_dot_ava_dot_feature__classification__pb2._CLASSIFYRESULT
_GETIMAGERESPONSE.fields_by_name['detection'].message_type = ava__engine_dot_ava_dot_feature__detection__pb2._DETECTRESULT
_GETIMAGERESPONSE.fields_by_name['face_recognition'].message_type = ava__engine_dot_ava_dot_feature__face__recognition__pb2._FACERECOGNITIONRESULT
_SEARCHIMAGESRESPONSE.fields_by_name['images'].message_type = _GETIMAGERESPONSE
DESCRIPTOR.message_types_by_name['GetImageRequest'] = _GETIMAGEREQUEST
DESCRIPTOR.message_types_by_name['GetImageResponse'] = _GETIMAGERESPONSE
DESCRIPTOR.message_types_by_name['SearchImagesRequest'] = _SEARCHIMAGESREQUEST
DESCRIPTOR.message_types_by_name['SearchImagesResponse'] = _SEARCHIMAGESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetImageRequest = _reflection.GeneratedProtocolMessageType('GetImageRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETIMAGEREQUEST,
  __module__ = 'ava_engine.ava.images_api_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.GetImageRequest)
  ))
_sym_db.RegisterMessage(GetImageRequest)

GetImageResponse = _reflection.GeneratedProtocolMessageType('GetImageResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETIMAGERESPONSE,
  __module__ = 'ava_engine.ava.images_api_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.GetImageResponse)
  ))
_sym_db.RegisterMessage(GetImageResponse)

SearchImagesRequest = _reflection.GeneratedProtocolMessageType('SearchImagesRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHIMAGESREQUEST,
  __module__ = 'ava_engine.ava.images_api_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.SearchImagesRequest)
  ))
_sym_db.RegisterMessage(SearchImagesRequest)

SearchImagesResponse = _reflection.GeneratedProtocolMessageType('SearchImagesResponse', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHIMAGESRESPONSE,
  __module__ = 'ava_engine.ava.images_api_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.SearchImagesResponse)
  ))
_sym_db.RegisterMessage(SearchImagesResponse)


# @@protoc_insertion_point(module_scope)
