
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7912c132f3d464614e5afb2b0ac4ffe36e0ee0ab",
 "version": "1962"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
