__version__ = '0.0.1'
__url__ = 'https://github.com/obernard/argmanager'
__description__ = 'Wrapper around ArgumentParser handling configuration files.'
__license__ = 'MIT'
__author__ = 'Olivier BERNARD'
__email__ = 'obernard78+github@gmail.com'
