language: python
dist: trusty
sudo: false
cache:
  ccache: true
  directories:
  - $HOME/Library/Caches/Homebrew


env:
  global:
    - QPDF_RELEASE=https://github.com/qpdf/qpdf/releases/download/release-qpdf-8.0.2/qpdf-8.0.2.tar.gz
    - TWINE_USERNAME=ocrmypdf-travis
    - secure: "d1PfCVoqvFFwAqm0QEozLLoUdEHaY0kAvawfc4lKdLSjI+yOJYoNdknU0r3TdwttNEF2VV+aY9q/4wVnYrEiF4L13E3s+UtDqIXwGk/b14JrdExIx/0yj642kbCJPycZqqRZgvGwYuhb6EF7e/QrsNYMwZ95E9oTyWa0ZaEkiPrrVJh9XSNDpw9I8REL3GecpfvF/GpHWX0VBHoaJfCgDzDDvHQPdfIXAZg+OLJOLNrR2ivvUD3gR371376fYPMPNsqMNqBghLdX8lnX2zkEc67An9ZBLi1dx46PhHjn8c06QOBQ25wcwtCxSnaXygkq5HXUXnpWmCbPcy3n98bJBE1P86M1eWo5c3KV4zwY3pvC6/ldFFAX0nC5Qr8xVpiBZIZKhqBEsX7HlCIRdN5OzmWXTkRhO05GtloH+IPuS8PH09vlaGfdCmBdJkvQjnkXL9Jdw5JJcIt9c//CgRjJ4CtHySA3I0XEnqbLHRhsYAyfJfM4ya3ou+eETpWVpnkZ4kbn8fuUkIpZL6YS9XtJCVCfh5uNpJ7BV0DzlZqdV//K3s9CTNyFac0L521YcFRwl0Nb72AlzbtGwWgWh1C8qmlJ/ENf0XI3dafvcqzPL61rwBlo0sah9DWxwUDWMUicUtp8qP5GK8VxHse+QlolJQVSb07jD6bf7+mILX0B3Mg="

matrix:
  include:
  - os: linux
    sudo: required
    python: "3.5"
    addons: &gcc48
      apt:
        sources: [ubuntu-toolchain-r-test]
        packages: [g++-4.8]  # g++-4.8 supports c++11 but not c++14 at all; g++-4.9 won't work
    env: 
      - MATRIX_EVAL="GCC=4.8"  # defer setting CC to gcc- etc until before_install

  - os: linux
    sudo: required
    python: "3.6"
    addons: *gcc48
    env: 
      - MATRIX_EVAL="GCC=4.8"  # defer setting CC to gcc- etc until before_install

  - os: linux
    sudo: required
    python: "3.6"  # test other versions here
    addons: &gcc7
      apt:
        sources: [ubuntu-toolchain-r-test]
        packages: [g++-7]  # g++-7 supports c++14
    env: 
      - MATRIX_EVAL="GCC=7"  # defer setting CC to gcc- etc until before_install

  - os: osx
    osx_image: xcode8.3
    language: generic

  - stage: wheels
    os: osx
    osx_image: xcode8.3
    language: cpp  # osx + language: python is broken
    install:
      - clang --version
      - $PYTHON_CMD --version
      - echo "CC=$CC CXX=$CXX"
      - $PYTHON_CMD -m pip install pybind11 cibuildwheel==0.7.1 setuptools_scm
    script:
      - $PYTHON_CMD setup.py sdist -d wheelhouse
      - export CCACHE_BASEDIR=`python3 -c "import tempfile; import os; print(os.path.realpath(tempfile.gettempdir()))"`
      - export CIBW_BEFORE_BUILD='{pip} install --upgrade setuptools certifi && {pip} install pybind11 setuptools_scm pytest-runner'
      - export CIBW_SKIP="cp27-* cp33-* cp34-*"
      - cibuildwheel --output-dir wheelhouse
      - |
        if [[ $TRAVIS_TAG ]]; then
          $PYTHON_CMD -m pip install twine
          $PYTHON_CMD -m twine upload wheelhouse/*.whl wheelhouse/*.tar.gz
        fi

  - stage: wheels
    os: linux
    python: "3.6"  # only need one environment to build all linux wheels
    sudo: required
    services:
      - docker
    install:
      - $PYTHON_CMD -m pip install cibuildwheel==0.7.1
      #- mkdir gcc-x86_64 && wget -q https://github.com/Noctem/pogeo-toolchain/releases/download/v1.4/gcc-7.2-binutils-2.29-centos5-x86-64.tar.bz2 -O - | tar xj -C gcc-x86_64 --strip-components=1
      #- mkdir ccache && wget -q https://www.samba.org/ftp/ccache/ccache-3.3.4.tar.bz2 -O - | tar xj -C ccache --strip-components=1
      - mkdir qpdf && wget -q $QPDF_RELEASE -O - | tar xz -C qpdf --strip-components=1
    script:
      #- export CIBW_ENVIRONMENT='ARCH=x86_64 PATH="`pwd`/gcc-$ARCH/bin:$PATH" CC="ccache cc" CXX="ccache c++" CXXFLAGS="-static-libstdc++" LD_LIBRARY_PATH="`pwd`/gcc-$ARCH/lib" CCACHE_BASEDIR=`python -c "import tempfile; import os; print(os.path.realpath(tempfile.gettempdir()))"` CCACHE_DIR=/host'$HOME'/.ccache'
      #- export CIBW_BEFORE_BUILD='{pip} install pybind11 && [ -d ccache/$ARCH ] || (unset CC CXX CXXFLAGS && mkdir ccache/$ARCH && cd ccache/$ARCH && ../configure && make install)'
      #- export CIBW_ENVIRONMENT='ARCH=x86_64 PATH="`pwd`/gcc-$ARCH/bin:$PATH" CC="cc" CXX="c++" CXXFLAGS="-static-libstdc++" LD_LIBRARY_PATH="`pwd`/gcc-$ARCH/lib:$LD_LIBRARY_PATH"'
      - export CIBW_BEFORE_BUILD='yum install -y libjpeg-devel zlib-devel && cd qpdf && ./autogen.sh && ./configure && make install && cd .. && {pip} install pybind11'
      - export CIBW_SKIP="cp27-* cp33-* cp34-* *i686"
      - cibuildwheel --output-dir wheelhouse
      - |
        if [[ $TRAVIS_TAG ]]; then
          $PYTHON_CMD -m pip install twine
          $PYTHON_CMD -m twine upload wheelhouse/*.whl
        fi

stages:
  - name: test
  - name: wheels


before_install:
- eval "${MATRIX_EVAL}"
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    if [ -n "$GCC" ]; then
      export CC="gcc-$GCC"
      export CXX="g++-$GCC"
      export LD_LIBRARY_PATH="/lib:/usr/lib:/usr/local/lib"
    elif [ -n "$CLANG" ]; then
      CC="ccache clang-$CLANG"
      CXX="ccache clang++-$CLANG"
      export CFLAGS="-Qunused-arguments"
      export CXXFLAGS="-Qunused-arguments -stdlib=libc++"
    fi
    if [ "$PYTHON" == "3.5" ]; then
      python$PYTHON -m ensurepip
    elif [ "$PYTHON" = "3.6" ]; then
      pyenv global system $PYTHON # https://github.com/travis-ci/travis-ci/issues/8363
    fi
    PYTHON_CMD=python$PYTHON
  elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update -q
    brew bundle --file=.travis/Brewfile
    export PATH=/usr/local/opt/ccache/libexec:/usr/local/bin:$PATH
    CC=clang
    CXX=clang++
    PYTHON_CMD=python3
  fi
  $PYTHON_CMD -m pip install --upgrade pip wheel

install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    mkdir qpdf
    wget -q $QPDF_RELEASE -O - | tar xz -C qpdf --strip-components=1
    cd qpdf/
    ./configure CC="ccache $CC" CXX="ccache $CXX"
    make -j 2
    sudo make install
    cd ..
  elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
    : # no op for now
  fi
- $PYTHON_CMD setup.py sdist
- $PYTHON_CMD -m pip install pybind11
- $PYTHON_CMD -m pip install --verbose dist/*.tar.gz
- $PYTHON_CMD -m pip install -r test_requirements.txt 

script:
- python3 -m pytest

