apiVersion: "kubeflow.org/v1alpha1"
kind: TFJob
metadata:
  name: $app-$run
  labels:
    mlt-app-name: $app
spec:
  replicaSpecs:
    - replicas: $num_ps
      tfReplicaType: PS
      template:
        spec:
          containers:
            - image: $image
              name: tensorflow
          restartPolicy: OnFailure
    - replicas: $num_workers
      tfReplicaType: WORKER
      template:
        spec:
          containers:
            - image: $image
              name: tensorflow
          restartPolicy: OnFailure
  terminationPolicy:
    chief:
      replicaName: WORKER
      replicaIndex: 0
