
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-08T08:18:06+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "fcf973456aa0e79ebedf0027dd5fabadb69c4df8",
 "version": "0.0.64"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
