runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  login: admin

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  login: admin
