dist: trusty
sudo: false
language: python

python:
- 3.5
- &latest_py3 3.6

jobs:
  fast_finish: true
  include:
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    install: skip
    script: skip
    deploy:
      provider: pypi
      on:
        tags: true
        all_branches: true
      user: jaraco
      password:
        secure: Gqg0voupRGGoR+K5ToSLLn6UIUPTNHBGd1IS+4tmtQauBilv1Q84F981ZKxbwNH0iofxTlZkzyvCEgggJNuxmYBAWaeH1BpT0RV+p0bssGV4xaIiAdvxQQStMP6KCjfph/CtOtE/yzsvvJEYYewY55MMxENK0gDnQJNgwDf+6AwiQL6SJcey+Fgz8bJhi74juugyd8VUBV/jtAaoFVvwLyPpjFXoFIPBo5QN01IjQnTUgsfkTOPw+f1NniNExKhw/q8PDlHAZsEEPYBL5zFpn8rZ/rvU1+/cyQQ111W7+KgWD4TXqjEOxg6WC0vwbhDmV2zwp49tBO01UPflxU7hAPU8NfANKlmB5iwrEpo3xeQkQDj+Vvp8x7cpdb4YoD7Aui8ShMRiygYwPzBT+kmDFNIm31XYz6u01BMI3CyxukhSAifkQRvT1i+33miBkztmd/yi2ji7ijn5FFb8K28DAGZH0W40TAxZZUqE6w9F4E5Oa7Si6j84mgJZhd+yxiW/FPlrxtAbOuAooGmpkWYMYX6E0I4mWIFcQg9wJJmOQOhNW2LWQRl9qGGPju7PNTogeM13G5XT/RY/Yyu+FdDiGReWKBX+1RshaHgs9j6U+0VelGlaQV0yRmxyLe/OlHp8UA6Sxke9Dr+rf9NX2yVZ2Jt+C15KEeSSXRqOhM6NcLg=
      distributions: dists
      skip_cleanup: true
      skip_upload_docs: true

notifications:
  slack:
    secure: aePyoqjYFjdooYpJB5GE9IfmNuQVdHMR7vYg0dAQIDktW0O133UfeAdEbsOWY7IVNapCBNILrZKfxc94hBIM1tSKpCmU6NRmpL2uqVB5dK1BHsD2LWFf9RDk5NvtEbyCkgGya7UfU4FX2bY4DkHfv54CiuGtTsWLNDBVKpIEzc8V2evMyvMsKJbetigm/Ay71M0wBwctDyUn/rZHhu4HWTCkAr47z9mGxF0W6TG55FsyOY2C/mf9cah42v6w22vPCKOdyEq90FSWyAHq11jfc5oww2QUigq6V7ullt1CVSz+UMTs7UAQ8uPDH9eH26ckPIqzzT0dvbnsrRaKYx6V8MihIULuVRgPus4tx4N+NJQeGFidmo7ryLJOpeIb/CzxXCODj5EIKOgXxsxh6F9DMmkQsD/489vJpa3dke/oA+gG8edafA2uRUNDQcdMp+0NODOE1P6+gPsmXzEpohYq+rYkTfCvduVz1vHN4Zb4O05NZwcGJx0jUqlEnpxfATut+yB1ANDXHBknjbdkuUGtPRxkMRbn0nuGW3rdxkZ8Kwoc9NP0iBV2V6slUn+yMAOUjo06fiua3juNJNDM1yB1P2ElPfKiv/ePwLVr6OxSl9OEjE7UT8UlmSHCw6ACMftySVf56+Xkc8Lry/euEknRfFX/kLtAZucXt9/CO/3ENjI=

cache: pip

install:
- pip install tox tox-venv

script: tox
