# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0078_auto_20171003_1650'),
        ('pretix_mabel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MabelSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sheet_url', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TicketLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_student_limit', models.IntegerField()),
                ('alumnus_limit', models.IntegerField()),
                ('external_limit', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Event')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Item')),
            ],
        ),
    ]
