# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_mabel', '0002_mabelsettings_ticketlimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketlimit',
            name='event',
        ),
    ]
