# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat Dec 12 20:34:55 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(720, 863)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton_loadAddCase = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loadAddCase.setGeometry(QtCore.QRect(10, 430, 141, 23))
        self.pushButton_loadAddCase.setObjectName(_fromUtf8("pushButton_loadAddCase"))
        self.layoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 701, 24))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.line_2 = QtGui.QFrame(self.layoutWidget_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_7.addWidget(self.line_2, 2, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 1, 0, 1, 1)
        self.layoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 530, 701, 24))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.line_4 = QtGui.QFrame(self.layoutWidget_4)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_8.addWidget(self.line_4, 2, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget_4)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_8.addWidget(self.label_17, 1, 0, 1, 1)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(10, 790, 701, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_info = QtGui.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(10, 800, 701, 20))
        self.label_info.setObjectName(_fromUtf8("label_info"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 380, 291, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 0, 3, 1, 1)
        self.lineEdit_Msd = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_Msd.setObjectName(_fromUtf8("lineEdit_Msd"))
        self.gridLayout_5.addWidget(self.lineEdit_Msd, 1, 0, 1, 1)
        self.lineEdit_Nsd = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_Nsd.setObjectName(_fromUtf8("lineEdit_Nsd"))
        self.gridLayout_5.addWidget(self.lineEdit_Nsd, 1, 1, 1, 1)
        self.lineEdit_Vsd = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_Vsd.setEnabled(False)
        self.lineEdit_Vsd.setAutoFillBackground(False)
        self.lineEdit_Vsd.setObjectName(_fromUtf8("lineEdit_Vsd"))
        self.gridLayout_5.addWidget(self.lineEdit_Vsd, 1, 2, 1, 1)
        self.lineEdit_Tsd = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_Tsd.setEnabled(False)
        self.lineEdit_Tsd.setObjectName(_fromUtf8("lineEdit_Tsd"))
        self.gridLayout_5.addWidget(self.lineEdit_Tsd, 1, 3, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 350, 701, 24))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.line = QtGui.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_6.addWidget(self.line, 2, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget1)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_6.addWidget(self.label_15, 1, 0, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 560, 421, 51))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_reinforce = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_reinforce.setObjectName(_fromUtf8("pushButton_reinforce"))
        self.horizontalLayout_2.addWidget(self.pushButton_reinforce)
        self.textBrowser_sectprop = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser_sectprop.setGeometry(QtCore.QRect(10, 190, 281, 151))
        self.textBrowser_sectprop.setObjectName(_fromUtf8("textBrowser_sectprop"))
        self.pushButton_apllytosec = QtGui.QPushButton(self.centralwidget)
        self.pushButton_apllytosec.setGeometry(QtCore.QRect(10, 40, 701, 23))
        self.pushButton_apllytosec.setObjectName(_fromUtf8("pushButton_apllytosec"))
        self.textBrowser_solveresults = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser_solveresults.setGeometry(QtCore.QRect(440, 560, 261, 211))
        self.textBrowser_solveresults.setObjectName(_fromUtf8("textBrowser_solveresults"))
        self.layoutWidget3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 620, 161, 92))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_9 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.pushButton_momentresist = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_momentresist.setObjectName(_fromUtf8("pushButton_momentresist"))
        self.gridLayout_9.addWidget(self.pushButton_momentresist, 1, 0, 1, 1)
        self.pushButton_forceresist = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_forceresist.setObjectName(_fromUtf8("pushButton_forceresist"))
        self.gridLayout_9.addWidget(self.pushButton_forceresist, 1, 1, 1, 1)
        self.pushButton_momentforceresist = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_momentforceresist.setObjectName(_fromUtf8("pushButton_momentforceresist"))
        self.gridLayout_9.addWidget(self.pushButton_momentforceresist, 3, 0, 1, 2)
        self.label = QtGui.QLabel(self.layoutWidget3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.layoutWidget3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_9.addWidget(self.label_2, 2, 0, 1, 2)
        self.layoutWidget_5 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(300, 700, 131, 73))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.gridLayout_11 = QtGui.QGridLayout(self.layoutWidget_5)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_19 = QtGui.QLabel(self.layoutWidget_5)
        self.label_19.setEnabled(False)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_11.addWidget(self.label_19, 0, 0, 1, 2)
        self.pushButton_10 = QtGui.QPushButton(self.layoutWidget_5)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_11.addWidget(self.pushButton_10, 2, 0, 1, 2)
        self.pushButton_8 = QtGui.QPushButton(self.layoutWidget_5)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_11.addWidget(self.pushButton_8, 1, 0, 1, 2)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 720, 251, 71))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.layoutWidget4 = QtGui.QWidget(self.frame_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 10, 231, 48))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.gridLayout_13 = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_23 = QtGui.QLabel(self.layoutWidget4)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_13.addWidget(self.label_23, 0, 0, 1, 1)
        self.lineEdit_Mmin = QtGui.QLineEdit(self.layoutWidget4)
        self.lineEdit_Mmin.setObjectName(_fromUtf8("lineEdit_Mmin"))
        self.gridLayout_13.addWidget(self.lineEdit_Mmin, 0, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.layoutWidget4)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_13.addWidget(self.label_22, 0, 2, 1, 1)
        self.lineEdit_Mmax = QtGui.QLineEdit(self.layoutWidget4)
        self.lineEdit_Mmax.setObjectName(_fromUtf8("lineEdit_Mmax"))
        self.gridLayout_13.addWidget(self.lineEdit_Mmax, 0, 3, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget4)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_13.addWidget(self.label_25, 1, 0, 1, 1)
        self.lineEdit_Nmin = QtGui.QLineEdit(self.layoutWidget4)
        self.lineEdit_Nmin.setObjectName(_fromUtf8("lineEdit_Nmin"))
        self.gridLayout_13.addWidget(self.lineEdit_Nmin, 1, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.layoutWidget4)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_13.addWidget(self.label_24, 1, 2, 1, 1)
        self.lineEdit_Nmax = QtGui.QLineEdit(self.layoutWidget4)
        self.lineEdit_Nmax.setObjectName(_fromUtf8("lineEdit_Nmax"))
        self.gridLayout_13.addWidget(self.lineEdit_Nmax, 1, 3, 1, 1)
        self.layoutWidget5 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(180, 620, 251, 73))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.gridLayout_10 = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_18 = QtGui.QLabel(self.layoutWidget5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_10.addWidget(self.label_18, 0, 0, 1, 2)
        self.pushButton_Asforcefunction = QtGui.QPushButton(self.layoutWidget5)
        self.pushButton_Asforcefunction.setObjectName(_fromUtf8("pushButton_Asforcefunction"))
        self.gridLayout_10.addWidget(self.pushButton_Asforcefunction, 1, 0, 1, 1)
        self.pushButton_Asmomentfunction = QtGui.QPushButton(self.layoutWidget5)
        self.pushButton_Asmomentfunction.setObjectName(_fromUtf8("pushButton_Asmomentfunction"))
        self.gridLayout_10.addWidget(self.pushButton_Asmomentfunction, 1, 1, 1, 1)
        self.pushButton_Asforcemomentfunction = QtGui.QPushButton(self.layoutWidget5)
        self.pushButton_Asforcemomentfunction.setObjectName(_fromUtf8("pushButton_Asforcemomentfunction"))
        self.gridLayout_10.addWidget(self.pushButton_Asforcemomentfunction, 2, 0, 1, 2)
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(300, 70, 251, 271))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(560, 200, 141, 16))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(14, 80, 40, 20))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.lineEdit_b_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_b_2.setEnabled(False)
        self.lineEdit_b_2.setGeometry(QtCore.QRect(60, 80, 221, 20))
        self.lineEdit_b_2.setObjectName(_fromUtf8("lineEdit_b_2"))
        self.layoutWidget6 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 110, 181, 22))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget6)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.layoutWidget6)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit_b = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_b.setObjectName(_fromUtf8("lineEdit_b"))
        self.gridLayout_4.addWidget(self.lineEdit_b, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget6)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 2, 1, 1)
        self.lineEdit_h = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_h.setObjectName(_fromUtf8("lineEdit_h"))
        self.gridLayout_4.addWidget(self.lineEdit_h, 0, 3, 1, 1)
        self.listWidget_loadcases = QtGui.QListWidget(self.centralwidget)
        self.listWidget_loadcases.setGeometry(QtCore.QRect(310, 400, 401, 121))
        self.listWidget_loadcases.setObjectName(_fromUtf8("listWidget_loadcases"))
        self.label_35 = QtGui.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(310, 380, 381, 20))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.pushButton_loadEditSelected = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loadEditSelected.setGeometry(QtCore.QRect(160, 430, 141, 23))
        self.pushButton_loadEditSelected.setObjectName(_fromUtf8("pushButton_loadEditSelected"))
        self.pushButton_loadDelSelected = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loadDelSelected.setGeometry(QtCore.QRect(90, 470, 81, 23))
        self.pushButton_loadDelSelected.setObjectName(_fromUtf8("pushButton_loadDelSelected"))
        self.pushButton_loadDelAll = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loadDelAll.setGeometry(QtCore.QRect(10, 470, 71, 23))
        self.pushButton_loadDelAll.setObjectName(_fromUtf8("pushButton_loadDelAll"))
        self.pushButton_loadAllON = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loadAllON.setGeometry(QtCore.QRect(260, 470, 41, 23))
        self.pushButton_loadAllON.setObjectName(_fromUtf8("pushButton_loadAllON"))
        self.pushButton_loadAllOFF = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loadAllOFF.setGeometry(QtCore.QRect(260, 500, 41, 23))
        self.pushButton_loadAllOFF.setObjectName(_fromUtf8("pushButton_loadAllOFF"))
        self.pushButton_loadSeletedON = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loadSeletedON.setGeometry(QtCore.QRect(10, 500, 71, 23))
        self.pushButton_loadSeletedON.setObjectName(_fromUtf8("pushButton_loadSeletedON"))
        self.pushButton_loadSeletedOFF = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loadSeletedOFF.setGeometry(QtCore.QRect(90, 500, 81, 23))
        self.pushButton_loadSeletedOFF.setObjectName(_fromUtf8("pushButton_loadSeletedOFF"))
        self.layoutWidget7 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 140, 162, 48))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget7)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_26 = QtGui.QLabel(self.layoutWidget7)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_3.addWidget(self.label_26, 0, 0, 1, 1)
        self.comboBox__concreteclass = QtGui.QComboBox(self.layoutWidget7)
        self.comboBox__concreteclass.setObjectName(_fromUtf8("comboBox__concreteclass"))
        self.gridLayout_3.addWidget(self.comboBox__concreteclass, 0, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.layoutWidget7)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 1, 0, 1, 1)
        self.comboBox_steelclass = QtGui.QComboBox(self.layoutWidget7)
        self.comboBox_steelclass.setObjectName(_fromUtf8("comboBox_steelclass"))
        self.gridLayout_3.addWidget(self.comboBox_steelclass, 1, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(560, 210, 81, 20))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(560, 70, 81, 20))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.pushButton_zoom_out = QtGui.QPushButton(self.centralwidget)
        self.pushButton_zoom_out.setGeometry(QtCore.QRect(310, 110, 21, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_zoom_out.setPalette(palette)
        self.pushButton_zoom_out.setObjectName(_fromUtf8("pushButton_zoom_out"))
        self.pushButton_zoom_in = QtGui.QPushButton(self.centralwidget)
        self.pushButton_zoom_in.setGeometry(QtCore.QRect(310, 80, 21, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_zoom_in.setPalette(palette)
        self.pushButton_zoom_in.setObjectName(_fromUtf8("pushButton_zoom_in"))
        self.layoutWidget8 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget8.setGeometry(QtCore.QRect(562, 318, 150, 22))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_12 = QtGui.QLabel(self.layoutWidget8)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.comboBox_cracklimn = QtGui.QComboBox(self.layoutWidget8)
        self.comboBox_cracklimn.setObjectName(_fromUtf8("comboBox_cracklimn"))
        self.horizontalLayout_5.addWidget(self.comboBox_cracklimn)
        self.layoutWidget9 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget9.setGeometry(QtCore.QRect(562, 231, 141, 25))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_21 = QtGui.QLabel(self.layoutWidget9)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout.addWidget(self.label_21)
        self.lineEdit_An = QtGui.QLineEdit(self.layoutWidget9)
        self.lineEdit_An.setObjectName(_fromUtf8("lineEdit_An"))
        self.horizontalLayout.addWidget(self.lineEdit_An)
        self.pushButton_setAndn_nd = QtGui.QPushButton(self.layoutWidget9)
        self.pushButton_setAndn_nd.setMinimumSize(QtCore.QSize(12, 0))
        self.pushButton_setAndn_nd.setMaximumSize(QtCore.QSize(12, 20))
        self.pushButton_setAndn_nd.setObjectName(_fromUtf8("pushButton_setAndn_nd"))
        self.horizontalLayout.addWidget(self.pushButton_setAndn_nd)
        self.pushButton_setAndn_ns = QtGui.QPushButton(self.layoutWidget9)
        self.pushButton_setAndn_ns.setMinimumSize(QtCore.QSize(12, 0))
        self.pushButton_setAndn_ns.setMaximumSize(QtCore.QSize(12, 20))
        self.pushButton_setAndn_ns.setObjectName(_fromUtf8("pushButton_setAndn_ns"))
        self.horizontalLayout.addWidget(self.pushButton_setAndn_ns)
        self.layoutWidget10 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget10.setGeometry(QtCore.QRect(562, 290, 111, 22))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_8 = QtGui.QLabel(self.layoutWidget10)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.lineEdit_an = QtGui.QLineEdit(self.layoutWidget10)
        self.lineEdit_an.setObjectName(_fromUtf8("lineEdit_an"))
        self.horizontalLayout_4.addWidget(self.lineEdit_an)
        self.layoutWidget11 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget11.setGeometry(QtCore.QRect(562, 262, 128, 22))
        self.layoutWidget11.setObjectName(_fromUtf8("layoutWidget11"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget11)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_10 = QtGui.QLabel(self.layoutWidget11)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.comboBox_dn = QtGui.QComboBox(self.layoutWidget11)
        self.comboBox_dn.setObjectName(_fromUtf8("comboBox_dn"))
        self.horizontalLayout_3.addWidget(self.comboBox_dn)
        self.layoutWidget12 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget12.setGeometry(QtCore.QRect(560, 149, 111, 22))
        self.layoutWidget12.setObjectName(_fromUtf8("layoutWidget12"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget12)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(self.layoutWidget12)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lineEdit_ap = QtGui.QLineEdit(self.layoutWidget12)
        self.lineEdit_ap.setObjectName(_fromUtf8("lineEdit_ap"))
        self.horizontalLayout_7.addWidget(self.lineEdit_ap)
        self.layoutWidget13 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget13.setGeometry(QtCore.QRect(560, 177, 150, 22))
        self.layoutWidget13.setObjectName(_fromUtf8("layoutWidget13"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget13)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_11 = QtGui.QLabel(self.layoutWidget13)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.comboBox_cracklimp = QtGui.QComboBox(self.layoutWidget13)
        self.comboBox_cracklimp.setObjectName(_fromUtf8("comboBox_cracklimp"))
        self.horizontalLayout_6.addWidget(self.comboBox_cracklimp)
        self.layoutWidget14 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget14.setGeometry(QtCore.QRect(560, 121, 128, 22))
        self.layoutWidget14.setObjectName(_fromUtf8("layoutWidget14"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget14)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(self.layoutWidget14)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.comboBox_dp = QtGui.QComboBox(self.layoutWidget14)
        self.comboBox_dp.setObjectName(_fromUtf8("comboBox_dp"))
        self.horizontalLayout_8.addWidget(self.comboBox_dp)
        self.layoutWidget15 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget15.setGeometry(QtCore.QRect(560, 90, 141, 25))
        self.layoutWidget15.setObjectName(_fromUtf8("layoutWidget15"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget15)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_20 = QtGui.QLabel(self.layoutWidget15)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_9.addWidget(self.label_20)
        self.lineEdit_Ap = QtGui.QLineEdit(self.layoutWidget15)
        self.lineEdit_Ap.setObjectName(_fromUtf8("lineEdit_Ap"))
        self.horizontalLayout_9.addWidget(self.lineEdit_Ap)
        self.pushButton_setApdp_nd = QtGui.QPushButton(self.layoutWidget15)
        self.pushButton_setApdp_nd.setMinimumSize(QtCore.QSize(12, 0))
        self.pushButton_setApdp_nd.setMaximumSize(QtCore.QSize(12, 20))
        self.pushButton_setApdp_nd.setObjectName(_fromUtf8("pushButton_setApdp_nd"))
        self.horizontalLayout_9.addWidget(self.pushButton_setApdp_nd)
        self.pushButton_setApdp_ns = QtGui.QPushButton(self.layoutWidget15)
        self.pushButton_setApdp_ns.setMinimumSize(QtCore.QSize(12, 0))
        self.pushButton_setApdp_ns.setMaximumSize(QtCore.QSize(12, 20))
        self.pushButton_setApdp_ns.setObjectName(_fromUtf8("pushButton_setApdp_ns"))
        self.horizontalLayout_9.addWidget(self.pushButton_setApdp_ns)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(530, 810, 181, 16))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setEnabled(False)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout_STRUTHON_CENCRERE_MONO = QtGui.QAction(MainWindow)
        self.actionAbout_STRUTHON_CENCRERE_MONO.setObjectName(_fromUtf8("actionAbout_STRUTHON_CENCRERE_MONO"))
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "STRUTHON.CONCRETE.MONO.SECTION", None))
        self.pushButton_loadAddCase.setText(_translate("MainWindow", "Add loadcase", None))
        self.label_16.setText(_translate("MainWindow", "Section properties", None))
        self.label_17.setText(_translate("MainWindow", "To solve", None))
        self.label_info.setText(_translate("MainWindow", "StruthonConcreteMonoSection ver.0.1.2 ( www.struthon.org)                                                                                   ", None))
        self.label_3.setText(_translate("MainWindow", "Msd[kNm]", None))
        self.label_4.setText(_translate("MainWindow", "Nsd[kN]", None))
        self.label_13.setText(_translate("MainWindow", "Vsd[kN]", None))
        self.label_14.setText(_translate("MainWindow", "Tsd[kNm]", None))
        self.lineEdit_Msd.setText(_translate("MainWindow", "0.0", None))
        self.lineEdit_Nsd.setText(_translate("MainWindow", "0.0", None))
        self.lineEdit_Vsd.setText(_translate("MainWindow", "0.0", None))
        self.lineEdit_Tsd.setText(_translate("MainWindow", "0.0", None))
        self.label_15.setText(_translate("MainWindow", "Section loads", None))
        self.pushButton_reinforce.setText(_translate("MainWindow", "Reinforce section", None))
        self.pushButton_apllytosec.setText(_translate("MainWindow", "Apply to section ", None))
        self.pushButton_momentresist.setText(_translate("MainWindow", "Moment resist", None))
        self.pushButton_forceresist.setText(_translate("MainWindow", "Force resist", None))
        self.pushButton_momentforceresist.setText(_translate("MainWindow", "Moment/force resist (2D)", None))
        self.label.setText(_translate("MainWindow", "Resist values", None))
        self.label_2.setText(_translate("MainWindow", "Resist chart", None))
        self.label_19.setText(_translate("MainWindow", "Other charts", None))
        self.pushButton_10.setText(_translate("MainWindow", "xxx", None))
        self.pushButton_8.setText(_translate("MainWindow", "xxx", None))
        self.label_23.setText(_translate("MainWindow", "Mmin[kNm] -", None))
        self.lineEdit_Mmin.setText(_translate("MainWindow", "-100", None))
        self.label_22.setText(_translate("MainWindow", "Mmax[kNm] -", None))
        self.lineEdit_Mmax.setText(_translate("MainWindow", "100", None))
        self.label_25.setText(_translate("MainWindow", "Nmin[kN] -", None))
        self.lineEdit_Nmin.setText(_translate("MainWindow", "-100", None))
        self.label_24.setText(_translate("MainWindow", "Nmax[kN] -", None))
        self.lineEdit_Nmax.setText(_translate("MainWindow", "100", None))
        self.label_18.setText(_translate("MainWindow", "As area charts", None))
        self.pushButton_Asforcefunction.setText(_translate("MainWindow", "as forcefunction (2D)", None))
        self.pushButton_Asmomentfunction.setText(_translate("MainWindow", "as momentfunction(2D)", None))
        self.pushButton_Asforcemomentfunction.setText(_translate("MainWindow", "as force to moment function (3D)", None))
        self.label_28.setText(_translate("MainWindow", "Name - ", None))
        self.lineEdit_b_2.setText(_translate("MainWindow", "Sec_1", None))
        self.label_5.setText(_translate("MainWindow", "b[mm] - ", None))
        self.label_6.setText(_translate("MainWindow", "h[mm] - ", None))
        self.label_35.setText(_translate("MainWindow", "No.,  Name,  Msd[kNm],  Nsd[kN],  Vsd[kN],  Tsd[kNm],  active[]", None))
        self.pushButton_loadEditSelected.setText(_translate("MainWindow", "Edit selected", None))
        self.pushButton_loadDelSelected.setText(_translate("MainWindow", "Delete selected", None))
        self.pushButton_loadDelAll.setText(_translate("MainWindow", "Delete all", None))
        self.pushButton_loadAllON.setText(_translate("MainWindow", "All ON", None))
        self.pushButton_loadAllOFF.setText(_translate("MainWindow", "All OFF", None))
        self.pushButton_loadSeletedON.setText(_translate("MainWindow", "Selected ON", None))
        self.pushButton_loadSeletedOFF.setText(_translate("MainWindow", "Selected OFF", None))
        self.label_26.setText(_translate("MainWindow", "Concrete class - ", None))
        self.label_27.setText(_translate("MainWindow", "Steel class - ", None))
        self.label_29.setText(_translate("MainWindow", "Side n (negative)", None))
        self.label_30.setText(_translate("MainWindow", "Side p (positive)", None))
        self.pushButton_zoom_out.setText(_translate("MainWindow", "-", None))
        self.pushButton_zoom_in.setText(_translate("MainWindow", "+", None))
        self.label_12.setText(_translate("MainWindow", "wmaxn[mm] - ", None))
        self.label_21.setText(_translate("MainWindow", "An[cm2] - ", None))
        self.pushButton_setAndn_nd.setText(_translate("MainWindow", "..", None))
        self.pushButton_setAndn_ns.setText(_translate("MainWindow", "..", None))
        self.label_8.setText(_translate("MainWindow", "an[mm] - ", None))
        self.label_10.setText(_translate("MainWindow", "dn[mm] - ", None))
        self.label_7.setText(_translate("MainWindow", "ap[mm] - ", None))
        self.label_11.setText(_translate("MainWindow", "wmaxp[mm] - ", None))
        self.label_9.setText(_translate("MainWindow", "dp[mm] - ", None))
        self.label_20.setText(_translate("MainWindow", "Ap[cm2] - ", None))
        self.pushButton_setApdp_nd.setText(_translate("MainWindow", "..", None))
        self.pushButton_setApdp_ns.setText(_translate("MainWindow", "..", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.actionAbout_STRUTHON_CENCRERE_MONO.setText(_translate("MainWindow", "About STRUTHON CENCRERE MONO", None))

