
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-17T09:08:33-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "54902ccf497511d7b56f5b5c8c77944a1f7572a2",
 "version": "v2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
