# Generated by Django 2.0.5 on 2018-05-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_add_first_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targetstate',
            options={'ordering': ['begin_at']},
        ),
    ]
