version: '2.2'

services:
    maildev:
        image: djfarrelly/maildev
        container_name: ${COMPOSE_PROJECT_NAME}_maildev
        hostname: ${COMPOSE_PROJECT_NAME}_maildev
        networks: [stakkr]
        ports:
            - ${DOCKER_MAILDEV_EXPOSE}:80
