sudo: false
language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
install:
    - pip install mock coverage coveralls flake8
    - pip install .
script:
    - coverage run --source=src/restview setup.py test -q
    - flake8 src setup.py
after_success:
    - coveralls
    - coverage report -m --fail-under=100
notifications:
    email: false
