apiVersion: batch/v1
kind: Job
metadata:
  name: $app-$run
spec:
  template:
    spec:
      containers:
      - name: $app
        image: $image
        env:
        - name: GREETING
          value: $greeting
      restartPolicy: Never
