# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppCustomization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=50)),
                ('color_hex', models.CharField(max_length=6, verbose_name="your product's main brand color (Hex)")),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('app_favicon', models.ImageField(blank=True, null=True, upload_to='')),
                ('app_background_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('app_background_options', models.CharField(choices=[('C', 'Cover'), ('T', 'Tiled')], max_length=1)),
                ('custom_helpdesk_link', models.CharField(blank=True, default='', max_length=100)),
                ('display_language_toggle', models.BooleanField(default=True)),
                ('email_language_toggle', models.BooleanField(default=True, verbose_name='Display all system languages in emails')),
                ('display_logo_title', models.BooleanField(default=True, verbose_name='Display Logo and Title together')),
                ('footer_image_left', models.FileField(blank=True, null=True, upload_to='')),
                ('footer_image_right', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
