# Generated by Django 2.0.5 on 2018-05-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_auto_20180522_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
