
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-05-18T05:53:52-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "57f04abc172e1b023277966a70f0e3bbb27d6ecc",
 "version": "0.9.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
