
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-06T08:14:30-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "224285eacc1d4c7eb913142ff4b39ebdeb092861",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
