version: '3'
services:
  mistral:
    build:
      context: ../../..
      dockerfile: "tools/docker/Dockerfile"
      args:
        BUILD_TEST_DEPENDENCIES: "false"
    restart: always
    ports:
      - "8989:8989"
    networks:
      - database
      - message-broker
      - mistral
    env_file:
     - mistral.env
#    volumes:
#      - "/path/to/mistral.conf:/etc/mistral/mistral.conf"
    environment:
      - UPGRADE_DB=true

  cloud-flow:
    image: mcdoker18/cloud-flow:0.5.0
    restart: always
    networks:
      - mistral
    ports:
      - "8000:8000"
    networks:
      - mistral
    environment:
      - CF_MISTRAL_URL=http://mistral:8989


networks:
  database:
  message-broker:
  mistral:
