- name: "register var for async_outputs_os_obj"
  set_fact:
    async_outputs_os_obj: []
  
- name: "Wait on jobs"
  include: wait_on_os_obj.yml
  vars:
    os_obj_group: "{{ item }}"
  with_items:  "{{ topology_outputs['os_obj_res'] }}"
