__name__ = 'mountapi'
__description__ = 'Loosely coupled, typed web framework for modern Python'
__url__ = 'https://mountapi.org'
__version__ = '0.1.0-alpha'
__author__ = 'Piotr Szpetkowski'
__author_email__ = 'piotr.szpetkowski@pyquest.space'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 Piotr Szpetkowski'
