
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-15T16:01:45+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "09a6e211bd840b521889a8d77fb09b4d0f9695ba",
 "version": "0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
