language: python

sudo: false
dist: trusty

python:
    - "3.6"

cache:
    apt: true
    pip: true
    ccache: true

before_install:
    - set -e  # fail on any error

install:
    - pip install pyqt5==5.7.1
    # Update pip to be able to install wheel dependencies
    - pip install -U pip wheel
    - pip install git+https://github.com/biolab/orange3.git
    - pip install .
    - pip install codecov

script:
    - catchsegv xvfb-run -a -s "-screen 0 800x600x24" coverage run setup.py test

after_success:
    codecov
