# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scanner/sampler_args.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scanner/sampler_args.proto',
  package='scanner.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x1ascanner/sampler_args.proto\x12\rscanner.proto\"$\n\x12StridedSamplerArgs\x12\x0e\n\x06stride\x18\x01 \x01(\x03\"G\n\x17StridedRangeSamplerArgs\x12\x0e\n\x06stride\x18\x01 \x01(\x03\x12\x0e\n\x06starts\x18\x02 \x03(\x03\x12\x0c\n\x04\x65nds\x18\x03 \x03(\x03\"%\n\x11GatherSamplerArgs\x12\x10\n\x04rows\x18\x01 \x03(\x03\x42\x02\x10\x01\"\'\n\x14SpaceNullSamplerArgs\x12\x0f\n\x07spacing\x18\x01 \x01(\x03\")\n\x16SpaceRepeatSamplerArgs\x12\x0f\n\x07spacing\x18\x01 \x01(\x03\"<\n\x16StridedPartitionerArgs\x12\x0e\n\x06stride\x18\x01 \x01(\x03\x12\x12\n\ngroup_size\x18\x02 \x01(\x03\"K\n\x1bStridedRangePartitionerArgs\x12\x0e\n\x06stride\x18\x01 \x01(\x03\x12\x0e\n\x06starts\x18\x02 \x03(\x03\x12\x0c\n\x04\x65nds\x18\x03 \x03(\x03\"x\n\x15GatherPartitionerArgs\x12?\n\x06groups\x18\x01 \x03(\x0b\x32/.scanner.proto.GatherPartitionerArgs.GatherList\x1a\x1e\n\nGatherList\x12\x10\n\x04rows\x18\x01 \x03(\x03\x42\x02\x10\x01\x62\x06proto3')
)




_STRIDEDSAMPLERARGS = _descriptor.Descriptor(
  name='StridedSamplerArgs',
  full_name='scanner.proto.StridedSamplerArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stride', full_name='scanner.proto.StridedSamplerArgs.stride', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=81,
)


_STRIDEDRANGESAMPLERARGS = _descriptor.Descriptor(
  name='StridedRangeSamplerArgs',
  full_name='scanner.proto.StridedRangeSamplerArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stride', full_name='scanner.proto.StridedRangeSamplerArgs.stride', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='starts', full_name='scanner.proto.StridedRangeSamplerArgs.starts', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ends', full_name='scanner.proto.StridedRangeSamplerArgs.ends', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=154,
)


_GATHERSAMPLERARGS = _descriptor.Descriptor(
  name='GatherSamplerArgs',
  full_name='scanner.proto.GatherSamplerArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='scanner.proto.GatherSamplerArgs.rows', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=193,
)


_SPACENULLSAMPLERARGS = _descriptor.Descriptor(
  name='SpaceNullSamplerArgs',
  full_name='scanner.proto.SpaceNullSamplerArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spacing', full_name='scanner.proto.SpaceNullSamplerArgs.spacing', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=234,
)


_SPACEREPEATSAMPLERARGS = _descriptor.Descriptor(
  name='SpaceRepeatSamplerArgs',
  full_name='scanner.proto.SpaceRepeatSamplerArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spacing', full_name='scanner.proto.SpaceRepeatSamplerArgs.spacing', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=277,
)


_STRIDEDPARTITIONERARGS = _descriptor.Descriptor(
  name='StridedPartitionerArgs',
  full_name='scanner.proto.StridedPartitionerArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stride', full_name='scanner.proto.StridedPartitionerArgs.stride', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_size', full_name='scanner.proto.StridedPartitionerArgs.group_size', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=339,
)


_STRIDEDRANGEPARTITIONERARGS = _descriptor.Descriptor(
  name='StridedRangePartitionerArgs',
  full_name='scanner.proto.StridedRangePartitionerArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stride', full_name='scanner.proto.StridedRangePartitionerArgs.stride', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='starts', full_name='scanner.proto.StridedRangePartitionerArgs.starts', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ends', full_name='scanner.proto.StridedRangePartitionerArgs.ends', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=416,
)


_GATHERPARTITIONERARGS_GATHERLIST = _descriptor.Descriptor(
  name='GatherList',
  full_name='scanner.proto.GatherPartitionerArgs.GatherList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='scanner.proto.GatherPartitionerArgs.GatherList.rows', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=538,
)

_GATHERPARTITIONERARGS = _descriptor.Descriptor(
  name='GatherPartitionerArgs',
  full_name='scanner.proto.GatherPartitionerArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groups', full_name='scanner.proto.GatherPartitionerArgs.groups', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GATHERPARTITIONERARGS_GATHERLIST, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=538,
)

_GATHERPARTITIONERARGS_GATHERLIST.containing_type = _GATHERPARTITIONERARGS
_GATHERPARTITIONERARGS.fields_by_name['groups'].message_type = _GATHERPARTITIONERARGS_GATHERLIST
DESCRIPTOR.message_types_by_name['StridedSamplerArgs'] = _STRIDEDSAMPLERARGS
DESCRIPTOR.message_types_by_name['StridedRangeSamplerArgs'] = _STRIDEDRANGESAMPLERARGS
DESCRIPTOR.message_types_by_name['GatherSamplerArgs'] = _GATHERSAMPLERARGS
DESCRIPTOR.message_types_by_name['SpaceNullSamplerArgs'] = _SPACENULLSAMPLERARGS
DESCRIPTOR.message_types_by_name['SpaceRepeatSamplerArgs'] = _SPACEREPEATSAMPLERARGS
DESCRIPTOR.message_types_by_name['StridedPartitionerArgs'] = _STRIDEDPARTITIONERARGS
DESCRIPTOR.message_types_by_name['StridedRangePartitionerArgs'] = _STRIDEDRANGEPARTITIONERARGS
DESCRIPTOR.message_types_by_name['GatherPartitionerArgs'] = _GATHERPARTITIONERARGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StridedSamplerArgs = _reflection.GeneratedProtocolMessageType('StridedSamplerArgs', (_message.Message,), dict(
  DESCRIPTOR = _STRIDEDSAMPLERARGS,
  __module__ = 'scanner.sampler_args_pb2'
  # @@protoc_insertion_point(class_scope:scanner.proto.StridedSamplerArgs)
  ))
_sym_db.RegisterMessage(StridedSamplerArgs)

StridedRangeSamplerArgs = _reflection.GeneratedProtocolMessageType('StridedRangeSamplerArgs', (_message.Message,), dict(
  DESCRIPTOR = _STRIDEDRANGESAMPLERARGS,
  __module__ = 'scanner.sampler_args_pb2'
  # @@protoc_insertion_point(class_scope:scanner.proto.StridedRangeSamplerArgs)
  ))
_sym_db.RegisterMessage(StridedRangeSamplerArgs)

GatherSamplerArgs = _reflection.GeneratedProtocolMessageType('GatherSamplerArgs', (_message.Message,), dict(
  DESCRIPTOR = _GATHERSAMPLERARGS,
  __module__ = 'scanner.sampler_args_pb2'
  # @@protoc_insertion_point(class_scope:scanner.proto.GatherSamplerArgs)
  ))
_sym_db.RegisterMessage(GatherSamplerArgs)

SpaceNullSamplerArgs = _reflection.GeneratedProtocolMessageType('SpaceNullSamplerArgs', (_message.Message,), dict(
  DESCRIPTOR = _SPACENULLSAMPLERARGS,
  __module__ = 'scanner.sampler_args_pb2'
  # @@protoc_insertion_point(class_scope:scanner.proto.SpaceNullSamplerArgs)
  ))
_sym_db.RegisterMessage(SpaceNullSamplerArgs)

SpaceRepeatSamplerArgs = _reflection.GeneratedProtocolMessageType('SpaceRepeatSamplerArgs', (_message.Message,), dict(
  DESCRIPTOR = _SPACEREPEATSAMPLERARGS,
  __module__ = 'scanner.sampler_args_pb2'
  # @@protoc_insertion_point(class_scope:scanner.proto.SpaceRepeatSamplerArgs)
  ))
_sym_db.RegisterMessage(SpaceRepeatSamplerArgs)

StridedPartitionerArgs = _reflection.GeneratedProtocolMessageType('StridedPartitionerArgs', (_message.Message,), dict(
  DESCRIPTOR = _STRIDEDPARTITIONERARGS,
  __module__ = 'scanner.sampler_args_pb2'
  # @@protoc_insertion_point(class_scope:scanner.proto.StridedPartitionerArgs)
  ))
_sym_db.RegisterMessage(StridedPartitionerArgs)

StridedRangePartitionerArgs = _reflection.GeneratedProtocolMessageType('StridedRangePartitionerArgs', (_message.Message,), dict(
  DESCRIPTOR = _STRIDEDRANGEPARTITIONERARGS,
  __module__ = 'scanner.sampler_args_pb2'
  # @@protoc_insertion_point(class_scope:scanner.proto.StridedRangePartitionerArgs)
  ))
_sym_db.RegisterMessage(StridedRangePartitionerArgs)

GatherPartitionerArgs = _reflection.GeneratedProtocolMessageType('GatherPartitionerArgs', (_message.Message,), dict(

  GatherList = _reflection.GeneratedProtocolMessageType('GatherList', (_message.Message,), dict(
    DESCRIPTOR = _GATHERPARTITIONERARGS_GATHERLIST,
    __module__ = 'scanner.sampler_args_pb2'
    # @@protoc_insertion_point(class_scope:scanner.proto.GatherPartitionerArgs.GatherList)
    ))
  ,
  DESCRIPTOR = _GATHERPARTITIONERARGS,
  __module__ = 'scanner.sampler_args_pb2'
  # @@protoc_insertion_point(class_scope:scanner.proto.GatherPartitionerArgs)
  ))
_sym_db.RegisterMessage(GatherPartitionerArgs)
_sym_db.RegisterMessage(GatherPartitionerArgs.GatherList)


_GATHERSAMPLERARGS.fields_by_name['rows'].has_options = True
_GATHERSAMPLERARGS.fields_by_name['rows']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_GATHERPARTITIONERARGS_GATHERLIST.fields_by_name['rows'].has_options = True
_GATHERPARTITIONERARGS_GATHERLIST.fields_by_name['rows']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
